### ISSUE TITLE
Network Manager: no informations about speed (Bugzilla Bug 1393)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#1393]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 1393
Date: 2015-10-16 12:07:51 +0000
From: Giorgio &lt;<gio_6b@yahoo.it>&gt;
To:   OpenMandriva QA &lt;<bugs@openmandriva.org>&gt;
CC:   @benbullard79, @cris-b

Last updated: 2018-08-20 18:36:58 +0000

## Comment 10497
Date: 2015-10-16 12:07:51 +0000
From: Giorgio &lt;<gio_6b@yahoo.it>&gt;

Wired connections (tethering) don't show any information about speed.
No coloured (blue and green) graph, only graph background with horizontal lines. Nor numbers regarding speed too.

Samsung mobile phone connected in tethering, network manager 0.9.8.8

I had same problem with Mobile Broadband (gsm) and usb key Huawei E353.

## Comment 10539
Date: 2015-10-20 14:35:02 +0000
From: @cris-b

is this still the case with network manager 1.0.6?

## Comment 10540
Date: 2015-10-20 14:42:07 +0000
From: Giorgio &lt;<gio_6b@yahoo.it>&gt;

I update regularly but I still have 0.9.8.8 version.

## Comment 10541
Date: 2015-10-20 17:08:16 +0000
From: @cris-b

ok 1.0.6 was published on the 16th, you may want to check your mirror is being updated?

## Comment 10545
Date: 2015-10-20 23:34:08 +0000
From: @cris-b

i've tried a tethered connection with nm 1.0.6 and everything seemed fine I could see the speed ad graph.

please re-open if this still does not work after you've updated.

## Comment 10568
Date: 2015-10-21 23:21:56 +0000
From: Giorgio &lt;<gio_6b@yahoo.it>&gt;

Installed networkmanager version1.0.6 and tried with two different mobiles (my Samsung and a borrowed Sony Xperia) bug still valid.

## Comment 10569
Date: 2015-10-21 23:26:54 +0000
From: @cris-b

is this using plasma-nm?

## Comment 10570
Date: 2015-10-22 08:34:01 +0000
From: Giorgio &lt;<gio_6b@yahoo.it>&gt;

(In reply to comment #6)
> is this using plasma-nm?

I've plasma-nm version 0.9.3.6-0.1:2014.0 installed. Is this what you asked for?

## Comment 10571
Date: 2015-10-22 09:26:18 +0000
From: @cris-b

yes i was wondering what gui you were using when you see this.

can you attach a screenshot of the issue?

## Comment 10575
Date: 2015-10-23 11:33:49 +0000
From: Giorgio &lt;<gio_6b@yahoo.it>&gt;

Created attachment 915
Network Manager speed graph

Here's my Network Manager speed graph when using tethering. Note that connection works, I'm using it to write this comment.

> Attached file: tehtering_1.png (image/png, 24832 bytes)
> Description:   Network Manager speed graph

## Comment 10588
Date: 2015-10-23 21:43:38 +0000
From: @cris-b

can you try updating  	
lib64NetworkManagerQt0 to 0.9.8.4 (it is currently in main testing repo), log out and in and let me know if that resolves things?

## Comment 10599
Date: 2015-10-24 19:50:28 +0000
From: Giorgio &lt;<gio_6b@yahoo.it>&gt;

I haven't "main testing" among my repos in MCC.
Browsing the web I found this repo 
http://mirror.yandex.ru/openmandriva/openmandriva2014.0/repository/x86_64/main/testing/ 
but here I don't find lib64NetworkManagerQt0.

Please show where can I find this packet.

## Comment 10600
Date: 2015-10-24 19:56:41 +0000
From: @cris-b

try:

http://mirror.yandex.ru/openmandriva/openmandriva2014.0/repository/x86_64/main/testing/lib64NetworkManagerQt0-0.9.8.4-0.1-omv2014.0.x86_64.rpm

## Comment 10604
Date: 2015-10-25 08:40:15 +0000
From: Giorgio &lt;<gio_6b@yahoo.it>&gt;

Installed lib64NetworkManagerQt0 version 0.9.8.4-0.1:2014.0 but the problem is worsened.
Now when tethering connection is working it don't appear in Network Manager window. If I disconnect and reconnect it appears. But information speed is still unavailable.

Strange behaviour: if I connect any wireless connection then tethering speed information appears. It seems that starting a wireless connection "enable" sped graph of tethering.

## Comment 13998
Date: 2016-06-25 23:20:28 +0000
From: Giorgio &lt;<gio_6b@yahoo.it>&gt;

Still valid in 2014 and in OMLx3 beta 2 candidate (build 374)

## Comment 14033
Date: 2016-06-27 16:18:22 +0000
From: Giorgio &lt;<gio_6b@yahoo.it>&gt;

I see same behaviour in Linux Mint 17 KDE: no speed indications (numbers and graph) but if I connect any wireless connection tethering speed informations appears. 
It could be a KDE issue.

**Comment by rugyada** [comment]
Closing, as 2014 and OMLx3 really EOL.
