### ISSUE TITLE
pymol (Bugzilla Bug 2469)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2469]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2469
Date: 2019-04-24 22:48:44 +0000
From: Nicolas TAULIER &lt;<nicolas.taulier@gmail.com>&gt;
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, nicolas.taulier@gmail.com, nix.or.die@gmail.com, nobodydead@gmail.com, @tpgxyz

Last updated: 2019-06-13 15:49:44 +0000

## Comment 19426
Date: 2019-04-24 22:48:44 +0000
From: Nicolas TAULIER &lt;<nicolas.taulier@gmail.com>&gt;

Please package pymol for OMLx 4

## Comment 19430
Date: 2019-04-25 01:44:16 +0000
From: @benbullard79

We got it:

$ rpm -qa pymol
pymol-1.8-1.x86_64

and it installs here. There is an update upstream to v. 2.3:

https://pymol.org/2/

## Comment 19432
Date: 2019-04-25 01:49:02 +0000
From: @benbullard79

Confirming as I believe OP is asking to upgrade this software.

**Comment by mandian** [comment]
Thanks to @berolinux  @benbullard79 now version 2.5.0 is in repo.
