### ISSUE TITLE
[Package Request] opentoonz - open source 2D animation software (Bugzilla Bug 2540)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2540]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2540
Date: 2019-08-29 00:19:53 +0000
From: luzpaz &lt;<chitty_cloud@me.com>&gt;
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, chitty_cloud@me.com, nix.or.die@gmail.com, nobodydead@gmail.com, @tpgxyz

Last updated: 2019-08-29 00:20:13 +0000

## Comment 19758
Date: 2019-08-29 00:19:53 +0000
From: luzpaz &lt;<chitty_cloud@me.com>&gt;

OpenToonz is a 2D animation software published by DWANGO. It is based on Toonz Studio Ghibli Version, originally developed in Italy by Digital Video, Inc., and customized by Studio Ghibli over many years of production.
 
Website: ​https://opentoonz.github.io/e/
Github: ​https://github.com/opentoonz/opentoonz
Latest stable: ​https://github.com/opentoonz/opentoonz/releases/tag/v1.3.0
Building on Linux: https://github.com/opentoonz/opentoonz/blob/master/doc/how_to_build_linux.md

**Comment by rugyada** [comment]
Closing, as no follow-up since too much time.

**Comment by davidebeatrici** [comment]
I can package it if needed.
