### ISSUE TITLE
Package Update Request - Ardour (DAW) v5.12.1 (Bugzilla Bug 2544)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2544]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2544
Date: 2019-09-07 16:26:12 +0000
From: luzpaz &lt;<chitty_cloud@me.com>&gt;
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, chitty_cloud@me.com, nix.or.die@gmail.com, nobodydead@gmail.com, @tpgxyz

Last updated: 2019-09-07 16:26:28 +0000

## Comment 19770
Date: 2019-09-07 16:26:12 +0000
From: luzpaz &lt;<chitty_cloud@me.com>&gt;

Please update Ardour from 5.9 to 5.12.1

Changelog: https://ardour.org/whatsnew.html

Building on Linux: https://ardour.org/building_linux.html

https://github.com/OpenMandrivaAssociation/ardour

**Comment by mandian** [comment]
Ardour 6.9.0 in in repo.
