### ISSUE TITLE
[Package Request] QGIS (Bugzilla Bug 2636)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2636]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2636
Date: 2020-07-10 12:10:03 +0000
From: @rugyada
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, nix.or.die@gmail.com, nobodydead@gmail.com, @tpgxyz

Last updated: 2021-03-06 19:54:53 +0000

## Comment 20292
Date: 2020-07-10 12:10:03 +0000
From: @rugyada

Request to package QGIS
A Free and Open Source Geographic Information System

Website:
https://qgis.org/

Source download:
https://qgis.org/downloads/qgis-latest.tar.bz2

Request by user:
https://forum.openmandriva.org/t/qgis/3675/

Thanks.

## Comment 20330
Date: 2020-08-29 01:28:48 +0000
From: @benbullard79

Confirming.

## Comment 20611
Date: 2021-03-06 19:54:53 +0000
From: @benbullard79

I believe the original request for this was from an OM Lx 4.1 user.

**Comment by rugyada** [comment]
Closing, as no follow-up since long time and 4.1 EOL.
