### ISSUE TITLE
om-repo-picker is not localized (Bugzilla Bug 2647)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2647]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2647
Date: 2020-09-06 11:39:49 +0000
From: @rugyada
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, nix.or.die@gmail.com, nobodydead@gmail.com, @tpgxyz

Last updated: 2021-06-14 20:49:08 +0000

## Comment 20362
Date: 2020-09-06 11:39:49 +0000
From: @rugyada

Created attachment 1915
Software Repository Selector

We have translations available, but for some reasons om-repo-picker does not show the user's language.

> Attached file: screenshot_20200906_132519.jpg (image/jpeg, 207583 bytes)
> Description:   Software Repository Selector

## Comment 20369
Date: 2020-09-06 21:09:08 +0000
From: @benbullard79

onfirmed

## Comment 20451
Date: 2020-11-20 14:06:26 +0000
From: @tpgxyz

Ok i've released new version with updated translations. Seems does not work.

Bero can you please take a look on your code ?

## Comment 20739
Date: 2021-06-14 20:49:08 +0000
From: @benbullard79

Need information on this.

**Comment by rugyada** [comment]
> We have translations available, but for some reasons om-repo-picker does not show the user's language.

Still valid.

**Comment by rugyada** [comment]
Fixed with om-repo-picker-1.3.1
