### ISSUE TITLE
om-welcome is not localized (Bugzilla Bug 2648)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2648]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2648
Date: 2020-09-06 11:46:12 +0000
From: @rugyada
To:   Gabriel Craciunescu &lt;<nix.or.die@gmail.com>&gt;
CC:   @benbullard79, bugs@openmandriva.org, nix.or.die@gmail.com, nobodydead@gmail.com, @rugyada, @tpgxyz

Last updated: 2021-06-14 20:49:43 +0000

## Comment 20363
Date: 2020-09-06 11:46:12 +0000
From: @rugyada

Created attachment 1916
om-welcome

We have translations available, but for some reasons om-welcome does not show the user's language.
For comparison, om-cc does show the user's language properly.

> Attached file: screenshot_20200906_132646.jpg (image/jpeg, 196143 bytes)
> Description:   om-welcome

## Comment 20364
Date: 2020-09-06 11:46:44 +0000
From: @rugyada

Created attachment 1917
om-welcome and om-cc

> Attached file: screenshot_20200906_133039.jpg (image/jpeg, 222762 bytes)
> Description:   om-welcome and om-cc

## Comment 20372
Date: 2020-09-06 21:12:07 +0000
From: @benbullard79

Confirming.

## Comment 20740
Date: 2021-06-14 20:49:43 +0000
From: @benbullard79

Any information on this report?

**Comment by rugyada** [comment]
> Any information on this report?

Cooker ISO 381

![screenshot_20210925_155301](https://user-images.githubusercontent.com/46781309/134773990-a368a820-cc7b-4cd4-8993-8cfd23aa850f.jpg)

**Comment by rugyada** [comment]
In progress
![screenshot_20220126_094800](https://user-images.githubusercontent.com/46781309/151137659-7fab76c3-e935-4e57-ba58-afa5306630f0.jpg)

**Comment by rugyada** [comment]
Fixed
