### ISSUE TITLE
path not set for the java virtual machine (Bugzilla Bug 2665)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2665]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2665
Date: 2021-01-04 17:28:29 +0000
From: @filjob
To:   @berolinux
CC:   @benbullard79, @berolinux, bugs@openmandriva.org, nix.or.die@gmail.com, nobodydead@gmail.com, @filjob

Last updated: 2021-05-24 03:22:39 +0000

## Comment 20517
Date: 2021-01-04 17:28:29 +0000
From: @filjob

Hello and Happy New Year

I have recently switch to Rolling from Rock. Works pretty well. I wanted to run "freeplane" (mind mapping) but java cannot be found. I have removed openjdk-13 and installed openjdk-15 (may be this last should be installed by default or is not part of the Rolling install yet?) and updated PATH

$ ./freeplane.sh 
which: no java in (/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:/usr/local/games:/home/olivier/.local/bin:/home/olivier/bin)
ERROR:   Couldn't find a java virtual machine,
         define JAVACMD, JAVA_BINDIR, JAVA_HOME or PATH.
$ export PATH=$PATH:/usr/lib/jvm/java-openjdk/bin
$ ./freeplane.sh
It works!

I suppose this or similar should be added in the Rolling installation script.

At your disposal for testing.

Olivier

PS: I will open another bug around ffmpeg and libx265 that is both in Lx4 and Rolling

## Comment 20520
Date: 2021-01-04 17:32:21 +0000
From: @filjob

*** Bug #2666 has been marked as a duplicate of this bug. ***

## Comment 20525
Date: 2021-01-04 19:38:50 +0000
From: @berolinux

$ cat /etc/profile.d/90java.sh 
export JAVA_HOME=/usr/lib/jvm/java-15-openjdk
export PATH=$PATH:$JAVA_HOME/bin
$ rpm -qf /etc/profile.d/90java.sh
java-15-openjdk-15.0.0-1.x86_64

Looks to me like everything is set up correctly, did you start a new shell after updating the package? Stuff in /etc/profile.d is only run when a new shell session is opened, so I could see this failing if you launch freeplane.sh from the same shell used to install the update without restarting the shell.

## Comment 20527
Date: 2021-01-05 16:07:15 +0000
From: @filjob

I have also removed the java path from PATH and I have removed and resinstalled java-15-openjdk from shell. After restarting the shell I can see the java path in PATH.

Initially I have removed the the Rock java-14 and installed the Rolling java-15 using the dnfdragora application. Would that be that the rolling script updating PATH does not work when using dnfdragora?

## Comment 20704
Date: 2021-05-24 03:22:39 +0000
From: @benbullard79

(In reply to Olivier Bézie from comment #3)
> I have also removed the java path from PATH and I have removed and
> resinstalled java-15-openjdk from shell. After restarting the shell I can
> see the java path in PATH.
> 
> Initially I have removed the the Rock java-14 and installed the Rolling
> java-15 using the dnfdragora application. Would that be that the rolling
> script updating PATH does not work when using dnfdragora?

It is possible that some script does not run properly when using dnfdragora.

Please re-install java-15-openjdk-15.0.0-1 from Konsole. This should work:

$ sudo dnf reinstall java-15-openjdk lib64javascriptcoregtk3.0_0 lib64javascriptcore-gir3.0

That will install all the java packages on a default Rolling system.

You could run:

$ rpm -qa | grep java

to get a list of all installed java packages and reinstall all of them.

**Comment by berolinux** [comment]
Doesn't seem to be a real bug (see comment 20525 and 20527)
