### ISSUE TITLE
openvpn exiting due to fatal error (Bugzilla Bug 2670)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2670]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2670
Date: 2021-01-12 15:48:47 +0000
From: @filjob
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, nix.or.die@gmail.com, nobodydead@gmail.com, @filjob, @tpgxyz

Blocker for:  #2672
Last updated: 2021-09-05 17:15:41 +0000

## Comment 20538
Date: 2021-01-12 15:48:47 +0000
From: @filjob

Hello,

I am using Rolling with latest update. I fail to establish a vpn connection (openvpn). The errors are the following:

>$ sudo openvpn openvpn.ovpn
>(...)
>Tue Jan 12 16:28:08 2021 us=492519 OpenVPN 2.4.9 x86_64-openmandriva-linux-gnu >[SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Nov  8 2020
> .Tue Jan 12 16:28:08 2021 us=492559 library versions: OpenSSL 3.0.0-alpha9 26 Nov 2020, LZO 2.10
>🔐 Enter Auth Username: 9rwnEzUPvb
>🔐 Enter Auth Password: **********              
>Tue Jan 12 16:28:29 2021 us=963931 OpenSSL: error:12800067:DSO support >routines::could not load the shared library
>Tue Jan 12 16:28:29 2021 us=963983 OpenSSL: error:12800067:DSO support >routines::could not load the shared library
>Tue Jan 12 16:28:29 2021 us=964003 OpenSSL: error:0480006C:PEM routines::no start line
>Tue Jan 12 16:28:29 2021 us=964019 Error reading extra certificate
>Tue Jan 12 16:28:29 2021 us=964043 Exiting due to fatal error>

The same is working properly with Rock e.i. the vpn connection is established.

Could you have a look at what could be wrong? I can help trying/testing with a little guidance :)

Thank you

Olivier

## Comment 20541
Date: 2021-01-12 18:36:58 +0000
From: @benbullard79

This bug added to:

QA: Bugs to be fixed for 4.2
https://issues.openmandriva.org/show_bug.cgi?id=2644

I don't use vpn so can not confirm or be of much help with this bug report.

## Comment 20562
Date: 2021-01-30 16:53:57 +0000
From: @tpgxyz

Hi Olivier, this message says that your certificate does not meet certificate file standard.

Please try with different certificate, or regenerate your own.

## Comment 20578
Date: 2021-02-03 13:43:10 +0000
From: @tpgxyz

Reducing priority as there is no response.

## Comment 20590
Date: 2021-02-03 18:53:20 +0000
From: @filjob

Hello Tomasz,

sorry for the late response.

I have 2 machines. On the one with Rock 4.1, openvpn works successfully with the same certificate.

I have tried with another one, same result. I can try with a self-signed but I will need more time for that. This week-end hopefully.

openssl3 is alpha. Could it be reverted to a more stable version?

Olivier

## Comment 20591
Date: 2021-02-03 19:29:34 +0000
From: @tpgxyz

Thanks Olivier for more information. Now things looks different.
I have feeling you are hit by the same issue which i had with certificate, but for OpenSSH https://github.com/openssl/openssl/issues/13443

Things sounds like OpenSSL3 may be the potential culprit here.

You may follow my github issue, and try to conver your key, as it helped me.
Ofcourse OpenSSH linked against pre-OpenSSL3 is accepting my original key.

## Comment 20592
Date: 2021-02-03 20:09:31 +0000
From: @tpgxyz

Raising severity

## Comment 20596
Date: 2021-02-06 22:40:40 +0000
From: @filjob

FYI - I have rolled back to openssl-1.1.1c-1 and openvpn-2.4.8-1 (used in lx4.1 Rock) and it works well.

## Comment 20690
Date: 2021-05-24 02:44:37 +0000
From: @benbullard79

(In reply to Olivier Bézie from comment #7)
> FYI - I have rolled back to openssl-1.1.1c-1 and openvpn-2.4.8-1 (used in
> lx4.1 Rock) and it works well.

Also this should be fixed with most recent software.

Closing as RESOLVED/FIXED.

If this issue persists please re-open bug report and provide updated information or better start a new report with up to date information.

## Comment 20758
Date: 2021-09-05 17:15:41 +0000
From: @filjob

I have installed lx4.3 and everything works well again.
By the way great job as usual for this new release!
Olivier

**Comment by mandian** [comment]
It wokrs well here too.
I close this issue.
