### ISSUE TITLE
Localized OM Welcome display issue (Bugzilla Bug 2675)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2675]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2675
Date: 2021-01-30 16:54:04 +0000
From: @ashledombos
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, nix.or.die@gmail.com, nobodydead@gmail.com, @ashledombos

Last updated: 2021-05-24 03:15:09 +0000

## Comment 20563
Date: 2021-01-30 16:54:04 +0000
From: @ashledombos

Created attachment 1943
French on the left, English on the right

I guess it may be the same for other locale, but at least for French:
Buttons at the top are on two lines, not only it's not very beautiful, but it also hides a part of the top text.

See picture as attachment.

> Attached file: Screenshot_20210130_174757.png (image/png, 598341 bytes)
> Description:   French on the left, English on the right

## Comment 20564
Date: 2021-01-30 16:56:15 +0000
From: @ashledombos

Created attachment 1944
omv-bug-report

> Attached file: omv-bug-report.log.xz (application/x-xz, 76800 bytes)
> Description:   omv-bug-report

## Comment 20703
Date: 2021-05-24 03:15:09 +0000
From: @benbullard79

Is this bug report still valid?

**Comment by rugyada** [comment]
> Is this bug report still valid?

Yes.

**Comment by ashledombos** [comment]
![image](https://user-images.githubusercontent.com/513335/134767608-348d4b0c-be61-489f-b1ad-25cdaaf739f7.png)

In case the pictures is no more available

**Comment by rugyada** [comment]
WIP

**Comment by rugyada** [comment]
It should be solved.
