### ISSUE TITLE
Package Request: linphone-desktop (Bugzilla Bug 2679)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2679]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2679
Date: 2021-02-12 23:12:04 +0000
From: @mandian
To:   @berolinux
CC:   angrypenguinpoland@gmail.com, @benbullard79, bugs@openmandriva.org, @itchka, @mandian, nix.or.die@gmail.com, nobodydead@gmail.com, @tpgxyz

Last updated: 2021-05-29 12:30:55 +0000

## Comment 20598
Date: 2021-02-12 23:12:04 +0000
From: @mandian

Hi,

recently linphoneqt, which is not working even in 4.2 has been renamed in linphone-desktop.

I've already update all the specs on github and built packages on ABF for cooker and rolling except for

lime
linphone
linphone-desktop

because on ABF I can build lime for openmandriva_personal repository only (my fault when I create this project) and linphone-desktop project is not in ABF

Also here is the list of the packages to build (in this order to fit all dependencies) on ABF to add linphone-desktop into 4.2

xsd
soci
bctoolbox
ortp
bzrtp
belr
belcard
mediastreamer2
belle-sip
lime
linphone
linphone-desktop

After that the package linphoneqt can be safety removed.

## Comment 20604
Date: 2021-03-02 11:59:25 +0000
From: @tpgxyz

We have some issues with ABF. When it will be back again i'll take care of it.

## Comment 20633
Date: 2021-04-10 17:34:08 +0000
From: @mandian

Hi,

I fixed linphone-desktop.spec so it now works again.

Please could you push it in 4.2 too (linphoneqt is still broken)?

## Comment 20634
Date: 2021-04-12 13:26:14 +0000
From: AngryPenguin &lt;<angrypenguinpoland@gmail.com>&gt;

Hi. Few days ago I updated stack of this packages but without linphone-desktop.
Thanks for fix, I built your version for cooker yesterday.

We plan copy Cooker to Rolling soon and then release LX 4.3 from Rolling. So updated linphone-desktop should be here in LX 4.3 at release time (in few days).

Thanks.

## Comment 20685
Date: 2021-05-24 02:30:03 +0000
From: @benbullard79

Anything going on with this bug report? NEED_INFO.

## Comment 20710
Date: 2021-05-29 12:30:55 +0000
From: @mandian

Hi Ben, I'am waiting for 4.3 release to do some test.

**Comment by mandian** [comment]
Hi,

_linphone_ is still unstable so I update it and all its dependencies and now is stable again. Here is the list of packages to rebuild for cooker and rolling or 4.3 (I can't build directly on ABF yet):

xsd
soci
libdecaf
bctoolbox
ortp
bzrtp
belr
belcard
lime
mediastreamer2
belle-sip
linphone
linphone-desktop

after that _linphoneqt_ and _bcmatroska2_ can be dismissed.

**Comment by rugyada** [comment]
Closing, as no follow-up since long time.
Feel free to re-open if you so desire.

**Comment by mandian** [comment]
@rugyada I updated it recently even in rock and it worked locally. I'll open a new bug if needed.

**Comment by rugyada** [comment]
Great. Thanks for reply.
