### ISSUE TITLE
Grub menu to launch the live iso (Bugzilla Bug 2680)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2680]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2680
Date: 2021-02-13 12:23:07 +0000
From: Benoit THIBAUD &lt;<b_thibaud@laposte.net>&gt;
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, nix.or.die@gmail.com, nobodydead@gmail.com, @tpgxyz

Last updated: 2021-06-14 23:18:10 +0000

## Comment 20599
Date: 2021-02-13 12:23:07 +0000
From: Benoit THIBAUD &lt;<b_thibaud@laposte.net>&gt;

these menu don't work in grub:
menuentry "OpenMandriva 4.2" {
  set iso_path=/isos/OpenMandrivaLx.4.2-plasma.x86_64.iso
  search --set=root --file $iso_path
  loopback loop $iso_path
  echo  'Lancement en cours, veuillez patienter ...'
  linux (loop)/boot/vmlinuz0 root=live:UUID=2021-02-12-01-11-19-00 iso-scan/filename=${iso_path} locale.LANG=fr_FR.utf8 vconsole.keymap=fr rd.live.image --
  initrd (loop)/boot/liveinitrd.img
}
menuentry "..    OpenMandrivaLx" {
   iso_path=/isos/OpenMandrivaLx.4.2-plasma.x86_64.iso
   export iso_path
   search --set=root --file $iso_path
   loopback loop $iso_path
   root=(loop)
   configfile /boot/grub/grub.cfg
   loopback --delete loop
}
for the second one, I tried too the configfile start.cfg instead of grub.cfg.
The first menu worked with the previous version:
menuentry "OpenMandriva" {
	set iso_path=/isos/OpenMandrivaLx.4.1-2020.05-plasma.x86_64.iso
	loopback loop $iso_path
	echo	'Lancement en cours, patientez ...'
	linux (loop)/boot/vmlinuz0 root=live:UUID=2020-05-04-16-00-01-00 iso-scan/filename=${iso_path} locale.LANG=fr_FR.utf8 vconsole.keymap=fr rd.live.image --
	initrd (loop)/boot/liveinitrd.img
}
When I test a Linux distribution, I don't use at all external devices (USB, DVD,..).

## Comment 20742
Date: 2021-06-14 20:58:22 +0000
From: @benbullard79

Have you tried the "Booting from ISO file" in the Release Notes?

https://wiki.openmandriva.org/en/releases/omlx42/notes

## Comment 20743
Date: 2021-06-14 23:18:10 +0000
From: @benbullard79

I got the following entry to show the Live ISO grub2 menu and it boots until 
"Basic system" and stops. Not sure what is missing or incorrect.

    menuentry "OpenMandriva Lx 4.2 B" {
       iso_path=/isos/OpenMandrivaLx.4.2-plasma.x86_64.iso
       export iso_path
       search --set=root --file $iso_path
       loopback loop $iso_path
       root=(loop)
       configfile /boot/grub/grub.cfg
       loopback --delete loop
}

**Comment by rugyada** [comment]
Closing, as no follow-up since long time.
Feel free to re-open if you so desire.
