### ISSUE TITLE
[Package Request] rott-expr (Bugzilla Bug 2691)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2691]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2691
Date: 2021-06-15 22:52:03 +0000
From: Zombie Ryushu &lt;<zombie.ryushu@zoho.com>&gt;
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, nix.or.die@gmail.com, nobodydead@gmail.com, @tpgxyz

Last updated: 2021-06-15 22:52:03 +0000

## Comment 20744
Date: 2021-06-15 22:52:03 +0000
From: Zombie Ryushu &lt;<zombie.ryushu@zoho.com>&gt;

Please Package Rott-Expr. as it improves stability of Rise of the Triad.

**Comment by rugyada** [comment]
Closing, as no follow-up.
