### ISSUE TITLE
[Package Request] commandergenius 2.8.1 (Bugzilla Bug 2692)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2692]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2692
Date: 2021-06-15 23:03:36 +0000
From: Zombie Ryushu &lt;<zombie.ryushu@zoho.com>&gt;
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, nix.or.die@gmail.com, nobodydead@gmail.com, @tpgxyz

Last updated: 2021-06-15 23:03:36 +0000

## Comment 20745
Date: 2021-06-15 23:03:36 +0000
From: Zombie Ryushu &lt;<zombie.ryushu@zoho.com>&gt;

Please import the Package Commander Genius from Mageia, or Rosa, and update to version 2.8.1

**Comment by rugyada** [comment]
Closing, as no follow-up.
