### ISSUE TITLE
[Update Request] bubbros 1.6.2 (Bugzilla Bug 2693)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2693]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2693
Date: 2021-06-16 02:11:33 +0000
From: Zombie Ryushu &lt;<zombie.ryushu@zoho.com>&gt;
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, nix.or.die@gmail.com, nobodydead@gmail.com, @tpgxyz

Last updated: 2021-06-16 02:11:33 +0000

## Comment 20746
Date: 2021-06-16 02:11:33 +0000
From: Zombie Ryushu &lt;<zombie.ryushu@zoho.com>&gt;

Please update bubbros to 1.6.2

**Comment by mandian** [comment]
I updated the spec but this package requires python2 version of pygame and pygtk2 so maybe it is better it to exclude from repo.
