### ISSUE TITLE
wx python module fails to load (Bugzilla Bug 2696)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2696]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2696
Date: 2021-09-06 17:59:12 +0000
From: @mandian
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, @itchka, nix.or.die@gmail.com, nobodydead@gmail.com, @tpgxyz

Last updated: 2021-09-14 02:33:54 +0000

## Comment 20759
Date: 2021-09-06 17:59:12 +0000
From: @mandian

Hi,

wx module from pacage python-wxpython4-4.1.1-1.x86_64 makes python3 crash when i try to load it.

How to reproduce:
$ python -c "import wx"
Here is the python traceback:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.9/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/usr/lib64/python3.9/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 261: invalid continuation byte
free(): invalid pointer
Aborted (core dumped)

Here is the coredump:
$ sudo coredumpctl info 16589
           PID: 16589 (python)
           PID: 16589 (python)
           UID: 1000 (mandian)
           GID: 1000 (mandian)
        Signal: 6 (ABRT)
  Command Line: python -c import wx
    Executable: /usr/bin/python3.9
 Control Group: /user.slice/user-1001.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1001.slice
       Session: 2
     Owner UID: 1000 (mandian)
       Boot ID: c0b93ff1b5474a81bc0b137f135857d5
    Machine ID: 9df729ab030'26f99c9e98872f29e948
      Hostname: mandian-vpc
       Storage: /var/lib/systemd/coredump/core.python.1001.c0b93ff1b5474a81bc0b137f135857d5.16589.1630949980000000.zst
       Message: Process 16589 (python) of user 1000 dumped core.
                
                Stack trace of thread 16589:
                #0  0x00007f4a1440a397 raise (libc.so.6 + 0x40397)
                #1  0x00007f4a143f0538 abort (libc.so.6 + 0x26538)
                #2  0x00007f4a144517a6 __libc_message (libc.so.6 + 0x877a6)
                #3  0x00007f4a1445a16c malloc_printerr (libc.so.6 + 0x9016c)
                #4  0x00007f4a1445b87c _int_free (libc.so.6 + 0x9187c)
                #5  0x00007f4a1445efe4 __libc_free (libc.so.6 + 0x94fe4)
                #6  0x00007f4a1479fa08 _PyMem_RawFree (libpython3.9.so.1.0 + 0x1f3a08)
                #7  0x00007f4a1479fd4e _PyObject_Free (libpython3.9.so.1.0 + 0x1f3d4e)
                #8  0x00007f4a147be93b type_dealloc (libpython3.9.so.1.0 + 0x21293b)
                #9  0x00007f4a14899315 collect (libpython3.9.so.1.0 + 0x2ed315)
                #10 0x00007f4a14898be5 collect_with_callback (libpython3.9.so.1.0 + 0x2ecbe5)
                #11 0x00007f4a14899f8a PyGC_Collect (libpython3.9.so.1.0 + 0x2edf8a)
                #12 0x00007f4a14872d45 Py_FinalizeEx (libpython3.9.so.1.0 + 0x2c6d45)
                #13 0x00007f4a1489672e Py_RunMain (libpython3.9.so.1.0 + 0x2ea72e)
                #14 0x00007f4a148978ba pymain_main (libpython3.9.so.1.0 + 0x2eb8ba)
                #15 0x00007f4a14897a82 Py_BytesMain (libpython3.9.so.1.0 + 0x2eba82)
                #16 0x0000000000201884 main (python3.9 + 0x1884)
                #17 0x00007f4a143f252d __libc_start_main (libc.so.6 + 0x2852d)
                #18 0x000000000020175a _start (python3.9 + 0x175a)

## Comment 20775
Date: 2021-09-14 02:33:54 +0000
From: @benbullard79

This is confirmed and changed to Cooker. It is to late to fix this for Lx 4.2.

**Comment by mandian** [comment]
this bug is still in all branches.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/wxpython-4-1-1-issue-om-lx-4-3/4369/3

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/wxpython-4-1-1-issue-om-lx-4-3/4369/22

**Comment by itchka** [comment]
This package has been patched and is now available in our repos. Further maintenance is required to clean up the sources and remove the need to patch the generated c++ code.

**Comment by mandian** [comment]
@itchka Thank you. it works now so i close this bug report.
