### ISSUE TITLE
freecad don't install (Bugzilla Bug 2699)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/distribution#2699]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2699
Date: 2021-09-10 11:59:10 +0000
From: daraf &lt;<angelob1@gmail.com>&gt;
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, @itchka

Last updated: 2021-09-10 17:46:04 +0000

## Comment 20764
Date: 2021-09-10 11:59:10 +0000
From: daraf &lt;<angelob1@gmail.com>&gt;

I can't install FREECAD why

['\n Problema: conflicting requests\n - nothing provides libpython3.8.so.1.0()(64bit) needed by freecad-0.18.4-1.x86_64\n - nothing provides libboost_filesystem.so.1.72.0()(64bit) needed by freecad-0.18.4-1.x86_64\n - nothing provides libboost_program_options.so.1.72.0()(64bit) needed by freecad-0.18.4-1.x86_64\n - nothing provides libboost_regex.so.1.72.0()(64bit) needed by freecad-0.18.4-1.x86_64\n - nothing provides libboost_python38.so.1.72.0()(64bit) needed by freecad-0.18.4-1.x86_64\n - nothing provides libboost_thread.so.1.72.0()(64bit) needed by freecad-0.18.4-1.x86_64']

## Comment 20765
Date: 2021-09-10 17:18:19 +0000
From: @benbullard79

Confirming. Also freecad needs a package maintainer. Since OpenMandriva is a community distro that means someone from the OM community will need to volunteer to maintain the package. 

I am not a developer but I try to help with issues like this if I am able.

The errors look like software that simply needs rebuilding to update dependencies. So I started freecad rebuilds for Cooker and Rolling/Lx 4.3 in ABF. We shall see what happens.

Also latest version of freecad is 19.2 so this software needs updating. My thought is to do the simple thing first and see if that results in working software.

## Comment 20766
Date: 2021-09-10 17:46:04 +0000
From: @benbullard79

The rebuild attempts failed. OpenMandriva devs are doing mass rebuild of all Cooker packages. Fixing freecad will likely need to wait until that is done. Also freecad probably will have to be updated to build with current versions of dependent packages.

So back to freecad needs a package maintainer.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/freecad-wont-install/4262/2

**Comment by benbullard79** [comment]
freecad-0.19.2-3 is available in Cooker, Rolling and will be in Lx 4.3. I am trying to build it for Lx 4.2 right now.
The new package is reported to be working in Cooker so it *should* be working in Rolling also.

**Comment by benbullard79** [comment]
Checking new freecad packages it installs and opens but gives errors shown in attached file.

[freecad-errors.txt](https://github.com/OpenMandrivaAssociation/distribution/files/7937141/freecad-errors.txt)

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/programmi-cad-in-omlx-4-5-cooker/4325/10

**Comment by mandian** [comment]
Hi,
thanks @berolinux package freecad-0.19.4-0.20220205.3, which is now in testing repository, should fix this. Please test it if you can.

**Comment by rugyada** [comment]
Reopened

Freecad won't install both in cooker and in ROME

```
$ sudo dnf --refresh install freecad
OpenMandriva Rolling - x86_64                                                  23 kB/s | 4.3 kB     00:00    
OpenMandriva Rolling - Unsupported - x86_64                                   456  B/s | 4.3 kB     00:09    
Errore: 
 Problema: conflicting requests
  - nothing provides libboost_filesystem.so.1.78.0()(64bit) needed by freecad-0.19.4-0.20220205.6.x86_64
  - nothing provides libboost_python39.so.1.78.0()(64bit) needed by freecad-0.19.4-0.20220205.6.x86_64
  - nothing provides libboost_program_options.so.1.78.0()(64bit) needed by freecad-0.19.4-0.20220205.6.x86_64
  - nothing provides libboost_thread.so.1.78.0()(64bit) needed by freecad-0.19.4-0.20220205.6.x86_64
  - nothing provides libpyside2.cpython-39-x86_64-linux-gnu.so.5.15()(64bit) needed by freecad-0.19.4-0.20220205.6.x86_64
  - nothing provides libshiboken2.cpython-39-x86_64-linux-gnu.so.5.15()(64bit) needed by freecad-0.19.4-0.20220205.6.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/non-si-installa-freecad/4647/5

**Comment by mandian** [comment]
DEBUG: Error: 
Unfortunately freecad fail to build because it requires shiboken2 (from pyside2) is not compatible with python 3.11 so pyside2 should be fixed first.

DEBUG:  Problem: package pyside2-devel-5.15.2-3.x86_64 requires shiboken2 = 5.15.2-3, but none of the providers can be installed
DEBUG:   - conflicting requests
DEBUG:   - nothing provides libclang.so.13()(64bit) needed by shiboken2-5.15.2-3.x86_64
DEBUG:   - nothing provides libclang.so.13(LLVM_13)(64bit) needed by shiboken2-5.15.2-3.x86_64

**Comment by mandian** [comment]
Update: @berolinux fixed pyside2 and I updated freecad to 0.20.1 but there is still some problems with python 3.11

DEBUG: /builddir/build/BUILD/FreeCAD-0.20.1/src/Base/ConsoleObserver.cpp:269:41: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
DEBUG:             src = PyUnicode_AsUTF8(frame->f_code->co_filename);
DEBUG:                                         ^
DEBUG: /usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
DEBUG: typedef struct _frame PyFrameObject;
DEBUG:                ^
DEBUG: 1 error generated.

**Comment by mandian** [comment]
In a few time FreeCAD 0.20.1 should be in repo.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/non-si-installa-freecad/4647/8
