### ISSUE TITLE
Some packages failed to build due Empty %files debugsourcefiles.list

### ISSUE THREAD

**Issue by AngryPenguinPL** [OpenMandrivaAssociation/distribution#2731]
# Issue Report #

### OpenMandriva Version ###
Cooker/Rolling

### Description ###

Following a few weeks, a lot of packages not built properly. This error appears:
`error: Empty %files file /builddir/build/BUILD/qownnotes-20.7.4/debugsourcefiles.list`

Example here: https://abf.openmandriva.org/build_lists/810270

Workaround is define in spec:
`%global debug_package %{nil}`

Can we fix this at some point? I suspect that if we do a mass rebuild a lot of packages will be broken due to this problem.

**Comment by tpgxyz** [comment]
Debug generator is fixed. Now packages with %global debug_package %{nil}  will fail.
