### ISSUE TITLE
Change omv-bug-report.log.zst to file type recognized by Github Issues

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2740]
I attempted to attach omv-bug-report.log.zst to a report here and discoved that the file type is not supported here. Also it does not seem like Ark is capable of extracting a .zst file. This all tends to make attaching the bug report log here a very technical process for our technically challenged users.

This issue is related to this one: #2739

**Comment by benbullard79** [comment]
I wrote assuming that adding other file types here would be difficult or impossible. I do not know for a fact if that is/is not true.
Obviously it would be a better solution is we could just add .zst and perhaps a few other file types.

**Comment by benbullard79** [comment]
https://github.com/OpenRefine/OpenRefine/pull/4155

**Comment by benbullard79** [comment]
Test to see if I can attach the decompressed omv-bug-report.log here.

[omv-bug-report.log](https://github.com/OpenMandrivaAssociation/distribution/files/7230209/omv-bug-report.log)

**Comment by benbullard79** [comment]
For now I think we leave it up to QA or whoever responds to a issue report to request user to attach the decompressed omv-bug-report.log file. Something like: 

To provide more technical information for developers open OM-Welcome, go to OM Features, click on Bug Report Tool and enter administrator password when prompted. Next open Konsole. Konsole should open to your /home directory if not cd to your /home and type (or copy and paste):

`unzstd omv-bug-report.log.zst`

That will create the file omv-bug-report.log. Attach that log file here.

**Comment by tpgxyz** [comment]
Well I'll make it uncompressed as it is easier for everyone.

**Comment by tpgxyz** [comment]
@benbullard79 @rugyada new omdv-bug-report-004 is available for cooker

**Comment by rugyada** [comment]
>  new omdv-bug-report-004 is available for cooker, rolling and 4.2

Thank you @tpgxyz

**Comment by benbullard79** [comment]
Thanks tpgxyz and rugyada. This is fixed or resolved.
