### ISSUE TITLE
Cooker/Lx 4.3 ISO's EFI boot to shell in VirtualBox

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2744]
**OpenMandriva version**:
recent Cooker and Rolling ISO's

**Describe the bug**:
EFI boot in VirtualBox boots to the uefi interactive shell

**Steps to reproduce**:
In Cooker host system using OM virtualbox-6.1.26-1 create a new ISO and use the Cooker ISO build 396 or 397. In settings for the new VM set System>Extended features to Enable EFI. Now start the VM. You should then get the uefi interactive shell.

**Observed behavior**:
Now start the VM. You should then get the uefi interactive shell.

**Expected behavior**:
The ISO should EFI boot directly to the OM Lx grub2 menu

**Additional comment**:
I will double check this but as I recall these ISO's will boot on older version of OM virtualbox like 6.16.x. I *think* this issue *may* have started with recent version of OM virtualbox.

**Logs and screenshots if relevant**
I am not sure how to provide logs for this. I will do whatever developers suggest to provide logs or test possible fix. I do have screen-shots of the workaround for this. The workaround is easy if you know the code:

The workaround to boot in VirtualBox Cooker ISO's from interactive the shell:

1. At the prompt type `FS1:` and hit enter

2. At the prompt type `EFI\BOOT\BOOTX64.efi` and hit enter

Screen-shot of the procedure:

![Screenshot_20211004_182958](https://user-images.githubusercontent.com/5704386/135938345-8767dbad-d2e0-44ed-862e-3bc7979cdaaa.jpeg)

Result:

![Screenshot_20211004_183748](https://user-images.githubusercontent.com/5704386/135938432-98e7104d-7791-46a8-a251-086ededd40af.jpeg)

**Comment by benbullard79** [comment]
When I assign people to these bug reports I admit that I am trying for an educated guess as to who to include.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/new-cooker-om-lx-4-3-preview-isos/4222/5

**Comment by benbullard79** [comment]
I can now confirm the OM Lx Cooker ISO # 396 will EFI boot with the old OM virtualbox-6.1.16-4 but it will not EFI boot with the most recent virtualbox-6.1.26-1 package. That *might* provide a key as to how to correct this issue.

**Comment by tpgxyz** [comment]
@benbullard79  have you tried to burn ISO

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/om-lx-4-3-live-mode-doesnt-launch-in-virtualbox-6-1-32/4352/4

**Comment by benbullard79** [comment]
itchka made some work around for this. I do not know what that work around was.
