### ISSUE TITLE
Graphical boot failure after `dnf distro-sync`

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2745]
**OpenMandriva version**:
Cooker

**Describe the bug**:
After installing sddm-0.19.0-10 vbox and hardware systems fail to boot.

**Steps to reproduce**:
Install sddm-0.19.0-10. After the script runs select either to keep the old sddm.conf or accept the new package maintainers version.

**Observed behavior**: 
Reboot. Booting stops to quick to see much. I was able to boot in console and recovery modes.

**Expected behavior**:
System boots normally.

**Additional comment**:
Let me know if there is any other log or info to provide or test to do. I will be on citizenship duty over next day. So my availability may be limited.
**Logs and screenshots if relevant**
Logs from VBox failed boot: 
[VBox.log](https://github.com/OpenMandrivaAssociation/distribution/files/7305679/VBox.log)

Log from hardware system failed boot: 
[journalctl-b-3.txt](https://github.com/OpenMandrivaAssociation/distribution/files/7305688/journalctl-b-3.txt)

**Comment by benbullard79** [comment]
With fully distro-synced cooker if I boot in to recovery mode and try to start sddm I get this error:
`Failed to read display number from pipe`
`attempt 1 starting the Display server on vt 2 failed`

That error basically repeats as many times as I try to start sddm.service.

Should it be starting Display server on vt 2?

**Comment by benbullard79** [comment]
Booting in to console mode. login and `systemctl start sddm` and it is definitely starting display server on tty2. I don't care about that but it may explain this issue. Before it was being started on tty1 here.

**Comment by rugyada** [comment]
Noticed that by pressing Esc at plymouth, or adding `plymouth.enable=0` at GRUB entry make sddm to display properly.

**Comment by rugyada** [comment]
> Good to know this is Plymouth issue then :)

Yet triggered by sddm update.
There must be something interfering..

**Comment by tpgxyz** [comment]
Fixing in Plymouth and sddm.

**Comment by tpgxyz** [comment]
Should be fixed now.

**Comment by tpgxyz** [comment]
It is not fixed as it is related to https://github.com/OpenMandrivaAssociation/distribution/issues/2746

**Comment by rugyada** [comment]
> It is not fixed as it is related to #2746 I'm building plymouth with workaround

Working in virtualbox here

**Comment by tpgxyz** [comment]
Fixed.
