### ISSUE TITLE
KDE isoimagewriter works not

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2750]
**OpenMandriva version**:

Cooker znver1 fully distro-synced

**Describe the bug**:

KDE isoimagewriter does not burn image to flash drive. instead it gives this `error: ("error", QVariant(QString, "The last block was not fully written (22,528 of 1,048,576 bytes)!\nAborting.")))`

**Steps to reproduce**:

Try to burn any recent OM Lx .iso file to a flash drive with KDE isoimagewriter-0.8-0.20211015.1

**Expected behavior**:

Expect a bootable image to burned to flash drive

**Additional comment**:

Konsole output:

```
$ isoimagewriter
org.kde.isoimagewriter: statusChanged:  KAuth::Action::AuthorizedStatus
org.kde.isoimagewriter: progressStep(QVariantMap) QMap(("error", QVariant(QString, "The last block was not fully written (22,528 of 1,048,576 bytes)!\nAborting.")))
org.kde.isoimagewriter: finished()  0
org.kde.isoimagewriter: finished()  QMap()
```

**Logs and screenshots if relevant**

[omdv-bug-report-20211024123615.log](https://github.com/OpenMandrivaAssociation/distribution/files/7405970/omdv-bug-report-20211024123615.log)

I have tried this with many different OM Lx .iso files. I always check checksums. Also all of the .iso files have been used to install in VBox or in hardware using previous v. of KDE isoimagewriter or ROSA imagewriter to burn. 

Previous version isoimagewriter-0.8-0.20210514.1 is working here.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/rolling-users-major-distribution-upgrade/4258/4

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/kde-isoimagewriter-broken-in-cooker-and-rolling/4263/1

**Comment by benbullard79** [comment]
This issue confirmed as a bug by user on IRC and on forum.

**Comment by benbullard79** [comment]
I filled an upstream issue report: https://bugs.kde.org/show_bug.cgi?id=445036

I will admit I wished I knew if this was really an issue with isoimagewriter and not something with some OM Lx system package? Or something like how OM Lx mounts or does not mount flash drives when they are plugged in?

**Comment by benbullard79** [comment]
I wonder if this has anything to do with why KDE isoimagewriter stopped working for us:

https://invent.kde.org/utilities/isoimagewriter/-/commit/18803a15408f322fc07912984b89706921f7c1ef

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/new-rolling-lx-4-3-isos/4271/1

**Comment by tpgxyz** [comment]
@benbullard79 Well it works. I just finished with success burning an iso on my usb stick
![Screenshot_20220218_205911](https://user-images.githubusercontent.com/13415195/154753334-2ff8ec77-5080-45c4-957a-c6a0ace54023.png)

**Comment by benbullard79** [comment]
It is working now in Lx 4.3 with:

```
$ rpm -qa isoimagewriter
isoimagewriter-0.8-0.20211015.1.x86_64
```
And that is a good thing. Bug report was filed against Cooker isoimagewriter-0.8-0.20211015.1.znver1. 

I don't think whether is Cooker, Rolling, or Lx 4.3 is a factor. Being znver1 may be the problem. I'll check this in a bit.

**Comment by benbullard79** [comment]
And this is working now in znver1 system as well. I checked with both x86_64 and znver1 .iso files. (Checked that the flash drive so made boots also.)

I wish I knew what changed. This bug was extensively tested before and after filing this report. So if the package version did not change something else must have to correct this issue. 

Any it seems fixed. Thanks to whoever fixed it.

**Comment by tpgxyz** [comment]
My guess is that issue was inside KFSolid framework.

**Comment by benbullard79** [comment]
![image](https://user-images.githubusercontent.com/5704386/189963717-73a20073-7d90-4491-ad8c-84dd43ead43b.png)

This seems to be  an issue that keeps coming back.

**Comment by rugyada** [comment]
This looks like an upstream bug and we have other tools well working available.
