### ISSUE TITLE
Patched: cppcheck doesn't work and is not up-to-date

### ISSUE THREAD

**Issue by bogdro** [OpenMandrivaAssociation/distribution#2751]
The cppecheck utility's package in OpenMandriva installs software that doesn't work, because important configuration files are missing.
Furthermore, the package is not up-to-date (v1.88 while 2.6 is already out).
I'm attaching a patch for the 1.88 version and a full spec file for the 2.6 version. It's only the parameter name that is changed + I've fixed the SF download URL. Hope you can see the patches.
[omv-cppcheck-spec.zip](https://github.com/OpenMandrivaAssociation/distribution/files/7433902/omv-cppcheck-spec.zip)

**Comment by AngryPenguinPL** [comment]
Thanks. I updated package with your spec file.

Fixed by https://github.com/OpenMandrivaAssociation/cppcheck/pull/1
