### ISSUE TITLE
Firefox localization packages do not work.

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2752]
**OpenMandriva version**: 

All

**Describe the bug**:

OpenMandriva Firefox localization packages do not work.

**Steps to reproduce**:

Install Firefox with a localization package such as firefox-it or firefox-de.

**Observed behavior**:

Firefox remains very much English.

**Expected behavior**:

Firefox menu's etc. should switch to the language of the language pack and pages should render in the new language. If OM is making all these packages they should work.

**Additional comment**:

There is a work around. User can install languages from within Firefox in settings/preferences.

**Logs and screenshots if relevant**

Using OM Lx 4.2 as an example:
To reproduce issue:

![Screenshot_20211123_113052](https://user-images.githubusercontent.com/5704386/143275038-f1a67984-ca8b-4eef-8970-bbf011916b22.jpeg)

Firefox very much remains in English:

![Screenshot_20211124_101806](https://user-images.githubusercontent.com/5704386/143275608-f8f6c67a-c74d-4d28-ac82-eacd3229a520.jpeg)

_Note:_ I do not know for sure if it is better to have separate reports for Firefox and Thunderbird for the same issue but that was my guess.

**Comment by benbullard79** [comment]
This is confirmed in this forum post: https://forum.openmandriva.org/t/firefox-italian-localization-doesnt-works/4282

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/firefox-italian-localization-doesnt-works/4282/9

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/firefox-and-thunderbird-locale/4154/7

**Comment by benbullard79** [comment]
The language packages work like this:

1. Install the language package of your choice, for example:

`sudo dnf in firefox-de-103.0-3-omv4090.noarch.rpm`

2. Reboot computer

3. Start Firefox and go to Settings>General>Language and Appearance and select the language.
