### ISSUE TITLE
Thunderbird localization packages do not work.

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2753]
**OpenMandriva version**:

All

**Describe the bug**:

OpenMandriva Thunderbird localization packages do not work.

**Steps to reproduce**:

Install Thunderbird with a localization package such as thunderbird-it or thunderbird-de.

**Observed behavior**:

Thunderbird remains very much English.

**Expected behavior**:

Thunderbird menu's etc. should switch to the language of the language pack. I am not sure but I believe the e-mails will still render in the language they were sent. If OM is making all these packages they should work.

**Additional comment**:

There is a work around. User can install languages from within Thunderbird in settings/preferences. My observed behavior of this work around is that the menu's, ect. are rendered in the new language and e-mails remain in the language they were sent. I do not know if that is expected but it makes sense to me. It is possible that I missed a setting.

**Logs and screenshots if relevant**

![Screenshot_20211124_105105](https://user-images.githubusercontent.com/5704386/143281205-494edda4-7fbd-4350-a69d-98b1ce45ad82.jpeg)

Thunderbird remains very much in English.

![Screenshot_20211124_105349](https://user-images.githubusercontent.com/5704386/143281502-80d6206b-da02-4145-acc1-f1841a529b59.jpeg)

_Note:_ I do not know for sure if it is better to have separate reports for Firefox and Thunderbird for the same issue but that was my guess.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/firefox-and-thunderbird-locale/4154/17

**Comment by benbullard79** [comment]
This report is confirmed by user here: https://forum.openmandriva.org/t/firefox-and-thunderbird-locale/4154

**Comment by benbullard79** [comment]
The language packages work like this:

1. Install the language package of your choice, for example:

`sudo dnf in thunderbird-de-102.1.0-1-omv4050.noarch.rpm`

2. Reboot computer

3. Start Thunderbird and go to Settings>General>Language and Appearance and select the language.
