### ISSUE TITLE
Compiling apcupsd cannot find -lpthread

### ISSUE THREAD

**Issue by christann404** [OpenMandrivaAssociation/distribution#2754]
When compiling apcupsd-3.14.14 (the software that connects to my UPS) I get the following error:

 LD    src/apcupsd
/usr/bin/x86_64-openmandriva-linux-gnu-ld.bfd: cannot find -lpthread
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:33: apcupsd] Error 1
make[1]: *** [../autoconf/targets.mak:55: all] Error 2
make: *** [autoconf/targets.mak:111: src_DIR] Error 2
[omdv-bug-report-20211125092607.log](https://github.com/OpenMandrivaAssociation/distribution/files/7603661/omdv-bug-report-20211125092607.log)

**Comment by AngryPenguinPL** [comment]
Try install `glibc-static-devel`

**Comment by mandian** [comment]
Hi @christann404,
the packages is now in testing repo. Also I added some more features and gui as apcupsd-gui. Please could you test it?

**Comment by christann404** [comment]
Hi Mandian. 
Thanks. I have tested the apcupsd packages and they do work.

**Comment by benbullard79** [comment]
Then closing issue.
