### ISSUE TITLE
Firefox: broken all extensions

### ISSUE THREAD

**Issue by AngryPenguinPL** [OpenMandrivaAssociation/distribution#2755]
**OpenMandriva version**: Cooker and Rolling

**Describe the bug**: in Firefox 94.0.1 from the OpenMandriva repo and also those unbranded 94.0.2 from Mozilla.com all extensions are not working e.g. adblocks. Also one of two previous releases of Firefox was affected too. But looks like this is a bug with OM system component and not with browser.

**Steps to reproduce**:
1. Install OM Cooker or Rolling
2. Download from mozilla.com website prebuild firefox binary or from openmandriva repo via ` sudo dnf install firefox`
3. Open Firefox
4. Download/install any extension for example uBlock or Adbock.
5. Open any website with add and see that no ad is blocked
6. Open config window for example in uBlock (this red shield in right corner)
  * instead of displaying the entire configuration window, only a white vertical line appears.
7. Cry because without blocking ads it is impossible to browse the internet in 2021 ... without destroying your nerves.

**Additional comment**:

- Worth to add this issue appears in Rolling and Cooker and not in stable Lx 4.2 but with the new release - lx 4.3 it will be affected also.
- This happens both on firefox from our repository and on prebuild binary from mozilla.
- Issue confirmed by few ppl on IRC/matrix openmandriva-cooker chat.

**Logs and screenshots if relevant**
![ksnip_20211128-165002](https://user-images.githubusercontent.com/3121142/143776216-5ff5aa90-8736-4e45-90f7-da1874242187.png)

Log from running firefox from om repo:
```
[x@OpenMandriva-Cooker ~]$ firefox
Gtk-Message: 17:14:11.287: Failed to load module "xapp-gtk3-module"
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.

###!!! [Parent][MessageChannel] Error: (msgtype=0x390144,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

JavaScript error: , line 0: AbortError: Actor 'Conduits' destroyed before query 'RunListener' was resolved

###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost


###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost


###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
```

**Comment by cris-b** [comment]
seems this could be something to do with glibc 2.34:

https://forums.gentoo.org/viewtopic-p-8650991.html?sid=30f593c8b7d401d9b8a22662ebed0cb3

suggestion there (which works for me) is to set MOZ_DISABLE_CONTENT_SANDBOX=1 env var before running firefox.  its just a workaround though, not a real solution.

**Comment by cris-b** [comment]
lowering the config setting security.sandbox.content.level from 4 to 2 also fixes it for me, related:

https://www.mail-archive.com/pld-cvs-commit@lists.pld-linux.org/msg480169.html

**Comment by AngryPenguinPL** [comment]
Thanks for workaround. Just tested MOZ_DISABLE_CONTENT_SANDBOX=1 and works fine.

**Comment by benbullard79** [comment]
Cooker with FF 95 and Adblocker Ultimate extension and the adblocker is working here.

**Comment by AngryPenguinPL** [comment]
Is still broken here. FF from OMV repo and from mozilla binary. Extension not working. So it it still not fixed by upstream. We need use workaround provided by cris-b

**Comment by AngryPenguinPL** [comment]
Workarounded by @berolinux in https://github.com/OpenMandrivaAssociation/glibc/commit/5bf14603909ffafd2bae632f65b9e1a5c6f02dde
