### ISSUE TITLE
Opening LO from file in Dolphin opens very tiny window.

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2756]
**OpenMandriva version**:

All, as far as I know anyway.

**Describe the bug**:

Opening LO from any file in Dolphin results in a very tiny window.

**Steps to reproduce**:

Go to Dolphin, open any file with LO Writer, Calc, ect.

**Observed behavior**:

Very tiny window.

**Expected behavior**:

A normal sized window

**Additional comment**:

I will endeavor to provide more info or logs when I have some time.
**Logs and screenshots if relevant**

![Screenshot_20211208_143949](https://user-images.githubusercontent.com/5704386/145281615-c819deff-1fe5-4b9c-a6a9-550c1d11d114.jpeg)

**Comment by benbullard79** [comment]
This bug was well confirmed in Cooker IRC today. Users have mentioned this on forum also.

There is a workaround. Click on the title bar of the application and open More Action>Configure Special Application Settings>Add Property and select Minimize Size.

![Screenshot_20211208_192313](https://user-images.githubusercontent.com/5704386/145317488-a46bb6bc-082a-4b1b-a400-19350e2d3d2b.jpeg)

**Comment by benbullard79** [comment]
bero added a workaround or fix to libreoffice 7.3.0-3.

**Comment by AngryPenguinPL** [comment]
For clarification, it's about commit https://github.com/OpenMandrivaAssociation/libreoffice/commit/4498c8585e0662e09f6d7cbc9799d8969eadc6be
