### ISSUE TITLE
Firefox ESR for Rock

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2757]
Official package name: 

Firefox ESR

License (must be an OSI approved Open Source license): 

https://www.mozilla.org/en-US/MPL/2.0/
Same as for Firefox RR

Download URL of latest release: 

https://ftp.mozilla.org/pub/firefox/releases/
https://ftp.mozilla.org/pub/firefox/releases/91.4.1esr/source/

Latest release date (must be recent):

16-Dec-2021

Description: 

Given the difficulty we have keeping Firefox up to date in Rock release several users have requested this on forum.

https://forum.openmandriva.org/t/why-does-firefox-stuck-in-version-84-in-rock/4296/14

As a practical goal would like to see this for OM Lx 4.3 release. If this gets done after OM Lx 4.3 release that would be OK as long as we get this added for Lx 4.3.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/why-does-firefox-stuck-in-version-84-in-rock/4296/14

**Comment by benbullard79** [comment]
This should be closed.
