### ISSUE TITLE
Weird error messages from hplip

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2764]
**OpenMandriva version**:
OM Lx 4.2 x86_64
**Describe the bug**:
I see these weird error messages when trying to install a printer using `kcmshell5 kcm_printer_manager`.
**Steps to reproduce**:
You would need an HP printer and hplip installed. Then install printer with `kcmshell5 kcm_printer_manager`.
**Observed behavior**:
Weird error messages but the software works and printer is successfully installed.
**Expected behavior**:
Printer installation without the error messages.
**Additional comment**:
This is an irritating problem but not hugely important to me. However the errors may scare some users. 
**Logs and screenshots if relevant**

![Screenshot_20220206_205816](https://user-images.githubusercontent.com/5704386/152851574-f661f0c6-50c3-45f6-81d8-5cf4097aea71.png)

![Screenshot_20220206_210033](https://user-images.githubusercontent.com/5704386/152851602-49bc8732-aed2-4a1f-81d8-8faa8f664707.png)

![Screenshot_20220206_210630](https://user-images.githubusercontent.com/5704386/152851636-f847d998-cedb-4b0e-ae45-3a779b9fecdb.png)

Printer installs and test page was printed. Also printed page of this report from Firefox.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/weird-error-messages-from-hplip/4342/1

**Comment by benbullard79** [comment]
This was fixed some time ago.
