### ISSUE TITLE
Kalendar Office

### ISSUE THREAD

**Issue by quadransmuralis** [OpenMandrivaAssociation/distribution#2766]
Official package name: Kalandar

License (must be an OSI approved Open Source license): [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html)

Download URL of latest release: appstream://org.kde.kalendar

Latest release date (must be recent): 2021-12-26

Description: Kalendar is a calendar application that allows you to manage your tasks and events. Kalendar supports both local calendars as well as a multitude of online calendars: Nextcloud, Google® Calendar, Outlook®, Caldav, and many more.

**Comment by AngryPenguinPL** [comment]
Done.

Kalendar 1.0.0 added to:
cooker/main
rolling/main/testing
4.3/main/testing

Please test it and back with feedback.
