### ISSUE TITLE
No audio devices after updating to Lx 4.3

### ISSUE THREAD

**Issue by RDKRACZ** [OpenMandrivaAssociation/distribution#2767]
**Describe the bug**:
I just restarted after all updates were installed (about 2,5 GB of packages I think) and after seeing the new wallpaper I noticed the volume icon in the panel is crossed out. After clicking there all I can see is "No output or input devices found"

**Logs and screenshots if relevant**

**Comment by AngryPenguinPL** [comment]
In lx 4.3 we switch from PulseAudio to PipeWire by default. This mean that if you install 4.3 from ISO then Pipe is installed by default but if you upgrade system from previous release you need insta Pipe manually.

Try:` sudo dnf install pipewire-pulse`
Then restart system 

There is also possible to switch back to use PulseAudio. You you prefer pulse, then you should install pulseaudio-server.
