### ISSUE TITLE
pipeware.pulse bug

### ISSUE THREAD

**Issue by alangean** [OpenMandrivaAssociation/distribution#2769]
**OpenMandriva version**: OMLx4.3

**Describe the bug**:  with Piperware -pulse server simulraneous audio from multiple deviceas doesn't work. You must set up them seprately,. With old Pulse server it works fine, instead.

**Comment by tpgxyz** [comment]
@AngryPenguinPL by a chance can you take a look on this? You are PipeWire expert here :)

**Comment by AngryPenguinPL** [comment]
Looks like this is similar issues to this https://gitlab.freedesktop.org/pulseaudio/paprefs/-/issues/13#note_1192318
Loading the sink module seems to be the solution
`pactl load-module module-combine-sink`
https://askubuntu.com/questions/1379376/how-to-achieve-automated-simultaneous-outputs-with-pipewire

**Comment by alangean** [comment]
Seems work. Thank you very much for the suggestion. @AngryPenguinPL
