### ISSUE TITLE
Package reques: LibreDWG

### ISSUE THREAD

**Issue by luzpaz** [OpenMandrivaAssociation/distribution#2771]
Official package name:
LibreDWG

License (must be an OSI approved Open Source license):  
GNU General Public License v3.0

Download URL of latest release:
https://github.com/LibreDWG/libredwg/releases/tag/0.12.5  

Latest release date (must be recent):
Feb 6, 2022

Description:
C library to handle DWG (CAD-related) files
homepage: [savannah.gnu.org/projects/libredwg/](https://savannah.gnu.org/projects/libredwg/)

**Comment by mandian** [comment]
Hi @luzpaz 
LibreDWG has been packaged. Please could you test it?
