### ISSUE TITLE
qdirstat

### ISSUE THREAD

**Issue by RDKRACZ** [OpenMandrivaAssociation/distribution#2772]
Official package name:
qdirstat

License (must be an OSI approved Open Source license):
[GPL-2.0](https://github.com/shundhammer/qdirstat/blob/master/LICENSE)

Download URL of the latest release:
https://github.com/shundhammer/qdirstat/releases

Latest release date (must be recent):
Aug 28, 2021
[And many commits from this time](https://github.com/shundhammer/qdirstat/commits/master)

Description:
Qt-based directory statistics: KDirStat without any KDE -- from the author of the original KDirStat.

**Comment by tpgxyz** [comment]
Done https://github.com/OpenMandrivaAssociation/qdirstat
