### ISSUE TITLE
k4dirstat

### ISSUE THREAD

**Issue by RDKRACZ** [OpenMandrivaAssociation/distribution#2773]
The latest version is 3.4.0 from Jan 2, 2022. The last version in OMA repository is 3.1.3-1 (unknown to me release date) whereas 3.2.0 was released on Nov 23, 2019.

Source: https://github.com/jeromerobert/k4dirstat

**Comment by AngryPenguinPL** [comment]
Package updated to 3.4.0 in repos:

cooker/unsupported
rolling/unsupported/testing
4.3/unsupported/testing

**Comment by RDKRACZ** [comment]
About how long it will take for the package to get updated in the stable repo?

**Comment by AngryPenguinPL** [comment]
Depends on the Q/A Team. Usually a few days.
You can turn on repo testing on your own at any time in the om-repo-picker program.
Or download package directly from ABF: https://abf.openmandriva.org/build_lists/129151
