### ISSUE TITLE
phoronix-test-suite - current version from repository can't be installed

### ISSUE THREAD

**Issue by RDKRACZ** [OpenMandrivaAssociation/distribution#2774]
Also a bug because:
```
Error: 
 Problem: conflicting requests
  - nothing provides php-json needed by phoronix-test-suite-9.0.1-1.noarch
(try to add '--skip-broken' to skip uninstallable packages)

```
v9.0.1 is from Oct 01, 2019

https://github.com/phoronix-test-suite/phoronix-test-suite/releases

**Comment by tpgxyz** [comment]
phoronix-test-suite really needs some attention. Feel free to provide PR with updates and fixes :)

**Comment by RDKRACZ** [comment]
So I tried to register on https://abf.openmandriva.org/users/sign_up and after waiting 20 minutes it looks like an account creation confirmation email is not being sent.
I even tried a different email address a minute ago and still no message.

**Comment by tpgxyz** [comment]
@fedya can you please help here with abf?

**Comment by fedya** [comment]
done

**Comment by fedya** [comment]
confirmation disabled time ago due to bot's rush
here is a guide to enable acc by hands
https://github.com/OpenMandrivaSoftware/docker-abf/

**Comment by rugyada** [comment]
Closing, as no follow-up since long time.
Feel free to re-open if you so desire.
