### ISSUE TITLE
Can't remove vim without braking the system

### ISSUE THREAD

**Issue by RDKRACZ** [OpenMandrivaAssociation/distribution#2775]
**OpenMandriva version**: 4.3

**Describe the bug**: When I try to remove `vim` dnf wants to destroy my OS.

**Steps to reproduce**: `sudo dnf rm vim`

**Observed behavior**:
```
Dependencies resolved.
================================================================================
 Package                Arch       Version               Repository        Size
================================================================================
Removing:
 vim                    x86_64     2:8.2.4310-1          @rock-x86_64      32 M
Removing dependent packages:
 basesystem             x86_64     1:4-19                @rock-x86_64       0  
Removing unused dependencies:
 lib64gpm2              x86_64     1:1.20.7-4            @rock-x86_64      28 k
 libutempter            x86_64     1.2.1-1               @rock-x86_64     9.3 k
 logrotate              x86_64     3.19.0-1              @rock-x86_64      90 k
 systemd-console        x86_64     249.20220113-1        @rock-x86_64      26 k
 systemd-cryptsetup     x86_64     249.20220113-1        @rock-x86_64     168 k
 systemd-hwdb           x86_64     249.20220113-1        @rock-x86_64      18 M
 systemd-locale         x86_64     249.20220113-1        @rock-x86_64     846 k
 systemd-polkit         x86_64     249.20220113-1        @rock-x86_64      44 k
 time                   x86_64     1.9-4                 @rock-x86_64      33 k

Transaction Summary
================================================================================
Remove  11 Packages

Freed space: 51 M
Is this ok [y/N]:  
Operation aborted.
```

**Comment by benbullard79** [comment]
Why? What do you gain by removing vim?

rpm command with appropriate options would remove that. 

_Standard disclaimer:_ However if do that any breakage is your problem.

**Comment by RDKRACZ** [comment]
Whan about making it vim **or** sth else like nano? That way if I have nano installed I can remove vim, but without nano I can't.

**Comment by tpgxyz** [comment]
@berolinux wdyt ?

**Comment by berolinux** [comment]
IMO requiring any console editor is sufficient, should be possible to pick whatever someone likes best. One potential issue is that some tools (visudo etc.) may have hardwired dependencies on a particular editor, but probably setting the right environment variables should work for most of those special cases.

**Comment by rugyada** [comment]
> IMO requiring any console editor is sufficient, should be possible to pick whatever someone likes best. 
,
>  but probably setting the right environment variables should work for most of those special cases.

@berolinux @tpgxyz
up

**Comment by rugyada** [comment]
Solved. Thank you.
