### ISSUE TITLE
Fix it list for rust packages that failed after the last 4.3 massbuild

### ISSUE THREAD

**Issue by itchka** [OpenMandrivaAssociation/distribution#2776]
https://abf.openmandriva.org/build_lists/115862;rust-actix-testing;x86_64;
https://abf.openmandriva.org/build_lists/115868;rust-atomicwrites;x86_64;
https://abf.openmandriva.org/build_lists/115871;rust-battery;x86_64;
https://abf.openmandriva.org/build_lists/115874;rust-bindgen;x86_64;
https://abf.openmandriva.org/build_lists/115877;rust-charset;x86_64;
https://abf.openmandriva.org/build_lists/115880;rust-cookie_store;x86_64;
https://abf.openmandriva.org/build_lists/115883;rust-coreos-installer;x86_64;
https://abf.openmandriva.org/build_lists/115886;rust-crates-io;x86_64;
https://abf.openmandriva.org/build_lists/115889;rust-criterion;x86_64;
https://abf.openmandriva.org/build_lists/115892;rust-crossbeam-epoch;x86_64;
https://abf.openmandriva.org/build_lists/115895;rust-crossterm;x86_64;
https://abf.openmandriva.org/build_lists/115901;rust-curl;x86_64;
https://abf.openmandriva.org/build_lists/115913;rust-ffsend;x86_64;
https://abf.openmandriva.org/build_lists/115916;rust-ffsend-api;x86_64;
https://abf.openmandriva.org/build_lists/115919;rust-filetime;x86_64;
https://abf.openmandriva.org/build_lists/115925;rust-gcsf;x86_64;34;Dependency Error
https://abf.openmandriva.org/build_lists/115928;rust-git2;x86_64;
https://abf.openmandriva.org/build_lists/115931;rust-git2-curl;x86_64;
https://abf.openmandriva.org/build_lists/115940;rust-gstreamer-base;x86_64;
https://abf.openmandriva.org/build_lists/115949;rust-http;x86_64;
https://abf.openmandriva.org/build_lists/115955;rust-hyper-tls;x86_64;
https://abf.openmandriva.org/build_lists/115961;rust-inotify-sys;x86_64;
https://abf.openmandriva.org/build_lists/115964;rust-iron;x86_64;
https://abf.openmandriva.org/build_lists/115970;rust-libflate;x86_64;34;Dependency Error
https://abf.openmandriva.org/build_lists/115979;rust-linked-hash-map;x86_64;
https://abf.openmandriva.org/build_lists/115985;rust-lru-cache;x86_64;
https://abf.openmandriva.org/build_lists/115991;rust-nickel;x86_64;
https://abf.openmandriva.org/build_lists/116015;rust-reqwest;x86_64;
https://abf.openmandriva.org/build_lists/116018;rust-restson;x86_64;
https://abf.openmandriva.org/build_lists/116021;rust-rgb;x86_64;
https://abf.openmandriva.org/build_lists/116024;rust-rustio;x86_64;34;Dependency Error
https://abf.openmandriva.org/build_lists/116027;rust-serde_yaml;x86_64;test src/error.rs - error::Error::location (line 85) .
https://abf.openmandriva.org/build_lists/116033;rust-silver;x86_64;
https://abf.openmandriva.org/build_lists/116036;rust-sysinfo;x86_64;
https://abf.openmandriva.org/build_lists/116039;rust-tokio-openssl;x86_64;
https://abf.openmandriva.org/build_lists/116045;rust-tokio-tls;x86_64;
https://abf.openmandriva.org/build_lists/116048;rust-trust-dns-native-tls;x86_64;
https://abf.openmandriva.org/build_lists/116051;rust-trust-dns-openssl;x86_64;
https://abf.openmandriva.org/build_lists/116054;rust-tungstenite;x86_64;
https://abf.openmandriva.org/build_lists/116057;rust-uom;x86_64;
https://abf.openmandriva.org/build_lists/116060;rust-urlshortener;x86_64;
https://abf.openmandriva.org/build_lists/116063;rust-uuid0.6;x86_64;
https://abf.openmandriva.org/build_lists/116066;rust-websocket;x86_64;
https://abf.openmandriva.org/build_lists/116069;rust-websocket-base;x86_64;
https://abf.openmandriva.org/build_lists/116072;rust-yaml-rust;x86_64;
https://abf.openmandriva.org/build_lists/116078;rust-zstd-sys;x86_64;

**Comment by benbullard79** [comment]
Is this still valid or can we close this one?
