### ISSUE TITLE
kcm_printer_manager error: "Could not activate remote peer."

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2778]
**OpenMandriva version**:
OM Lx 4.3
**Describe the bug**:
Users will see this error when using SystemSettings>Hardware>Printing>Add Printer
**Steps to reproduce**:
Open SystemSettings>Hardware>Printing>Add Printer
**Observed behavior**:
![Screenshot_20220224_200840](https://user-images.githubusercontent.com/5704386/155644319-fb64a207-a97b-47b9-9506-1fc27f0c0291.jpg)

**Expected behavior**:
That the utility opens without showing error.
**Additional comment**:
The utility works. I can set up a usb plugged printer or an unplugged printer wifi. Seems to function well to me.
**Logs and screenshots if relevant**

Konsole output:

`$ kcmshell5 kcm_printer_manager`

`kf.coreaddons: "Could not load plugin from : The shared library was not found."
QDBusError("org.freedesktop.DBus.Error.NameHasNoOwner", "Could not activate remote peer.") QDBusMessage(type=MethodCall, service="org.fedoraproject.Config.Printing", path="/org/fedoraproject/Config/Printing", interface="org.fedoraproject.Config.Printing", member="GroupPhysicalDevices", signature="", contents=([MapSMapSS]) )`

[omdv-bug-report-20220224.log](https://github.com/OpenMandrivaAssociation/distribution/files/8138100/omdv-bug-report-20220224.log)

**Comment by benbullard79** [comment]
This bug confirmed by person originally reporting in forum.

https://forum.openmandriva.org/t/unable-to-setup-brother-hl-l5100dn-printer/4406

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/unable-to-setup-brother-hl-l5100dn-printer/4406/7

**Comment by benbullard79** [comment]
This issue does not seemto exist in Cooker or Rolling before massbuild.

**Comment by benbullard79** [comment]
Mandian pointed to this in log output:

`Feb 24 14:39:53 scp-dbus-service[8765]: ModuleNotFoundError: No module named 'jobviewer'`

installing `system-config-printer-gui` causes the error to go away. `system-config-printer-gui` pulls dependencies `lib64gnome-keyring-gir1.0, lib64gnome-keyring0, lib64notify-gir0.7, and libgnome-keyring-i18n`. I suspect one of the lib packages has the missing module. I do not know why `kcm_printer_manager` needs this unless it is somehow related to viewing actual print jobs.
I'll see if can sort this  out with a test.

**Comment by benbullard79** [comment]
So without `system-config-printer-gui` and it's dependent packages the Print Queue in `kcm_printer_manager`seems to be able to track and manage print jobs just fine. So I *think* that module `jobviewer` is not needed.

**Comment by benbullard79** [comment]
Yes, in Lx 4.3 latest print-manager-21.12.2-2 adds the dependencies that fix this issue. Will move new print-manager to updates repos today.

**Comment by benbullard79** [comment]
This issue has appeared in Cooker. Or I just noticed it in cooker.

**Comment by benbullard79** [comment]
This is fixed. I should have closed some time ago.
