### ISSUE TITLE
qt-creator fails to install on rolling (fresh install)

### ISSUE THREAD

**Issue by niansa** [OpenMandrivaAssociation/distribution#2786]
[nils@lyllia ~]$ sudo dnf install qt-creator
    [sudo] password for nils: 
    Last metadata expiration check: 0:10:30 ago on Do 17 Mär 2022 22:17:50 CET.
    Error: 
     Problem: conflicting requests
      - nothing provides libclang.so.11.0()(64bit) needed by qt-creator-4.13.1-1.x86_64
      - nothing provides libclang.so.11.0(LLVM_11)(64bit) needed by qt-creator-4.13.1-1.x86_64
    (try to add '--skip-broken' to skip uninstallable packages)

**Comment by benbullard79** [comment]
AngryPenguinPL built this for Rolling and Lx 4.3, package currently in main/testing repo. To install in Rock x86_64:

sudo dnf --refresh in qt-creator --enablerepo rock-testing-x86_64

For other flavors edit the command to fit. Let us know if works for you.

![Screenshot_20220322_200848](https://user-images.githubusercontent.com/5704386/159602029-cc5c6163-1735-45a1-b68a-bae3e38a50d6.jpg)
