### ISSUE TITLE
Patched: Certificate generating errors during Postfix installation

### ISSUE THREAD

**Issue by bogdro** [OpenMandrivaAssociation/distribution#2790]
**OpenMandriva version**: 4.3

**Describe the bug**:
When installing Postfix (+the required minimum dependencies), the following messages show up in the console:
```
req: Unknown option or message digest: days 365
req: Use -help for summary.
chmod: cannot access '/etc/pki/tls/private/postfix.pem': No such file or directory
```
This is caused by a command syntax error in `/usr/share/rpm-helper/create-ssl-certificate` (https://github.com/OpenMandrivaSoftware/rpm-helper/blob/master/create-ssl-certificate).

**Steps to reproduce**:
Install Postfix (run `dnf install postfix`).

**Observed behavior**:
The above errors are shown in the terminal.

**Expected behavior**:
No errors are shown.

**Additional comment**:
The attached patch should fix the issue.
[create-ssl-certificate.patch.gz](https://github.com/OpenMandrivaAssociation/distribution/files/8324950/create-ssl-certificate.patch.gz)

**Logs and screenshots if relevant**

**Comment by berolinux** [comment]
Thanks, fixed in https://github.com/OpenMandrivaSoftware/rpm-helper/tree/0.24.19 https://github.com/OpenMandrivaAssociation/rpm-helper/commit/f435df740f0c589e4aae94f51e95bfe99b1eaeb9
