### ISSUE TITLE
merged-usr

### ISSUE THREAD

**Issue by bluca** [OpenMandrivaAssociation/distribution#2792]
Hello,

(apologies if this is not the appropriate location, please direct me to the right one)

systemd marked support for split-usr/unmerged-usr deprecated last year via a build-time warning: https://github.com/systemd/systemd/commit/9afd5e7b975e8051c011ff9c07c95e80bd954469
A runtime warning was also just added: https://github.com/systemd/systemd/commit/31cd2dd9060decfb5c1341e2b126d3dde643e02a

(reminder on what merged-usr means: https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/ )

We started a thread on the mailing list to try and get some data about which distributions have not yet switched to merged-usr: https://lists.freedesktop.org/archives/systemd-devel/2022-April/047673.html

and I was told OpenMandriva is one of them. With some googling I found mentions here https://forum.openmandriva.org/t/cooker-ideas-and-brainstorming-for-cooker/2890 but it was just a general discussion, not sure if it ever happened. It would be great to have some information about the status here, if there are any plans/ideas/discussions/etc. I am happy to relay back information to the thread if needed.

Thanks!

**Comment by tpgxyz** [comment]
Hello @bluca 
yes we are aware of that "split-usr". We plan to switch to "merge-usr" with OpenMandriva 5.0 which is going to be our next release. I'd say this is related to https://github.com/OpenMandrivaAssociation/distribution/issues/2720

**Comment by bluca** [comment]
Great news, thank you for the update!

**Comment by tpgxyz** [comment]
Some progress has been made. It is time to move glibc and gcc to /usr

**Comment by tpgxyz** [comment]
Looks like we managed to achieve merged-usr. On top of that merged-bin with a merged /usr/sbin->/usr/bin happened.
