### ISSUE TITLE
QMapShack doesn't install

### ISSUE THREAD

**Issue by Giorgio-IT** [OpenMandrivaAssociation/distribution#2793]
**OpenMandriva version**:Lx 4.3

**Describe the bug**: trying to install [QMapShack](https://github.com/Maproom/qmapshack) I get this error message
```
Problema: conflicting requests
  - nothing provides libproj.so.12()(64bit) needed by qmapshack-1.10.0-1.x86_64
  - nothing provides libroutino.so.0()(64bit) needed by qmapshack-1.10.0-1.x86_64
  - nothing provides routino needed by qmapshack-1.10.0-1.x86_64
```

**Additional comment**: I would suggest to update to [latest version](https://github.com/Maproom/qmapshack/releases) 

**Logs and screenshots if relevant**

**Comment by benbullard79** [comment]
Package builds are failing due to:
```
No matching package to install: 'routino'
No matching package to install: 'routino-devel'
Not all dependencies satisfied
Error: Some packages could not be found.
```
I do not see routino in ABF or GH. Someone else will have to take this one.

**Comment by mandian** [comment]
@Giorgio-IT Hi, qmapshack is now in testing repository. Please could you test it?

**Comment by Giorgio-IT** [comment]
Sorry for delay in answer but I don't get any notification in mail. 
Now I installed QMapShack but it doesn't open. Here's what I get in konsole:

`$ qmapshack
2022-05-05 11:00:40.859 [warning] "no file found for translations '/usr/share/qt5/translations/qt_C' (using default)."
2022-05-05 11:00:40.859 [warning] "no file found for translations '/usr/share/qmapshack/translations/qmapshack_C' (using default)."
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
2022-05-05 11:00:41.339 [warning] Failed to create projection: "EPSG:3857" -> "EPSG:4326"
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
2022-05-05 11:00:41.343 [warning] Failed to create projection: "EPSG:3857" -> "EPSG:4326"
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
2022-05-05 11:00:41.345 [warning] Failed to create projection: "EPSG:4326" -> "EPSG:4326"
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
2022-05-05 11:00:41.346 [warning] Failed to create projection: "EPSG:3857" -> "EPSG:4326"
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
2022-05-05 11:00:41.349 [warning] Failed to create projection: "EPSG:3857" -> "EPSG:4326"
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
2022-05-05 11:00:41.349 [warning] Failed to create projection: "EPSG:3857" -> "EPSG:4326"
2022-05-05 11:00:41.350 [warning] Empty filename passed to function
proj_create: Cannot find proj.db
proj_create: unrecognized format / unknown name
proj_create: Cannot find proj.db
proj_create: unrecognized format / unknown name
proj_create: Cannot find proj.db
proj_create: no database context specified
2022-05-05 11:00:41.352 [warning] Failed to create projection: " +type=crs" -> "EPSG:4326"
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: unrecognized format / unknown name
2022-05-05 11:00:43.225 [warning] Failed to create projection: "EPSG:4326" -> " +type=crs"
2022-05-05 11:00:43.876 [warning] Empty filename passed to function
2022-05-05 11:00:43.939 [warning] Empty filename passed to function
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
proj_create: Cannot find proj.db
proj_create: no database context specified
2022-05-05 11:00:44.001 [warning] Failed to create projection: "EPSG:4326" -> "EPSG:32661"
2022-05-05 11:00:44.090 [warning] Empty filename passed to function
Segmentation fault (core dumped)
`

**Comment by mandian** [comment]
Hi @Giorgio-IT,
try to remove the directory ~/.QMapShack/.

If this doesn't solve please check you are using lastt version of these packages:

```
$ sudo dnf install qmapshack
Dependencies resolved.
========================================================================================================================================================================
 Package                              Architecture                    Version                            Repository                                                Size
========================================================================================================================================================================
Installing:
 qmapshack                            x86_64                          1.16.1-4                           rock-updates-x86_64-unsupported                           41 M
Installing dependencies:
 lib64gdal30                          x86_64                          3.4.1-1                            rock-x86_64                                              6.0 M
 lib64proj22                          x86_64                          8.2.1-3                            rock-updates-x86_64                                      997 k
Installing weak dependencies:
 qmaptool                             x86_64                          1.16.1-4                           rock-updates-x86_64-unsupported                          5.1 M

Transaction Summary
```
If not, remove  lib64proj* then remove the directory ~/.QMapShack/ and reinstall _qmapshack_.
