### ISSUE TITLE
Xsne crashes with EPSON XP-2150 MULTIFUNCTION PRINTER

### ISSUE THREAD

**Issue by alangean** [OpenMandrivaAssociation/distribution#2796]
OM LX 4.3

I've changed my old multifunction printer with Epson XP-2150. 

I downloaded drivers for printer, both USB and Wi-Fi.
Subsequently, as Xsane (and skanlite) didn't recognize the device, I installed the driver Epson for Scan 2 (rpm package).
Then, the Epson 2 scan front-end (installed togheter with driver) works, as skanlite, but:

Xsane crashes when device Epson XP-2150 is selected.

When launching from console, the following diagnostics apply:

Segmentation error (core dump) created.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/problemi-con-lo-scanner/4453/6

**Comment by AngryPenguinPL** [comment]
Hi. We provide driver for Epson printers. Called `epson-inkjet-printer-escpr`
Can you try it instead your current driver?

Another thing... xsane is really old software. If you want GUI for scan device I recommend you try `simple-scan`

Btw. Do you any crash log? If yes can you post it here?

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/epson-xp-2150-xsane-scanning/4461/6

**Comment by alangean** [comment]
> > OM LX 4.3
> > I installed the driver Epson for Scan 2 (rpm package).
> 
> The driver .rpm comes from where? Sounds like something from Epson.
> 
> Do you have `task-printing-epson`, and `task-printing-scanning` installed? General instructions for setting up a printer are here:
> 
> https://wiki.openmandriva.org/en/distribution/guides/how-tos/printer
> 
> For my HP printer all I normally need to do is install `task-printing-hp` and set up printer using SystemSettings>Hardware>Printers. When I want to scan something I normally open Skanlite and my printer is automatically recognized and I scan away. I see this in the driver list for Epson:
> 
> ![Screenshot_20220425_145259](https://user-images.githubusercontent.com/5704386/165164423-b6379693-7a52-4f42-a1b2-84796f1ee369.jpg)
> 
> Which would lead one to believe the Epson XP-2150 is supported in `task-printing-epson`. You probably do need `task-printing-scanning` installed for scanner support.

Task-printing-epsno and task-printing-scanning are already installed.

**Comment by alangean** [comment]
> Hi. We provide driver for Epson printers. Called `epson-inkjet-printer-escpr` Can you try it instead your current driver?
> 
> Another thing... xsane is really old software. If you want GUI for scan device I recommend you try `simple-scan`
> Yes, the

**Comment by alangean** [comment]
> > > OM LX 4.3
> > > I installed the driver Epson for Scan 2 (rpm package).
> > 
> > 
> > The driver .rpm comes from where? Sounds like something from Epson.
> > Do you have `task-printing-epson`, and `task-printing-scanning` installed? General instructions for setting up a printer are here:
> > https://wiki.openmandriva.org/en/distribution/guides/how-tos/printer
> > For my HP printer all I normally need to do is install `task-printing-hp` and set up printer using SystemSettings>Hardware>Printers. When I want to scan something I normally open Skanlite and my printer is automatically recognized and I scan away. I see this in the driver list for Epson:
> > ![Screenshot_20220425_145259](https://user-images.githubusercontent.com/5704386/165164423-b6379693-7a52-4f42-a1b2-84796f1ee369.jpg)
> > Which would lead one to believe the Epson XP-2150 is supported in `task-printing-epson`. You probably do need `task-printing-scanning` installed for scanner support.
> 
> Task-printing-epsno and task-printing-scanning are already installed.



> 
Yes, the driver was epson-inkjet-printer-escpr. Again, the problem seems with Xsane. I'll use simple-scan. My only concern is by that no control on the quality trimming is possible. More than that, I see no way to to pack a multipage PDF file.

**Comment by benbullard79** [comment]
Tested in OMLx 4.3. Printer/Scanner device is HP Photosmart 6520

xsane-0.999-18
sane-backends-1.0.32-3

Xsane seems to work here. Certainly not crashing.

**Comment by benbullard79** [comment]
alangean: Posting: Segmentation error (core dump) created.

Does not provide any useful information. Usually it is the information before that line that would tell someone the cause. We ask users to provide all the Konsole output and/or logs so the person helping can decide what is or is not important. If the output is more than 20 lines please put that in a file and attach the file to your post here.

**Comment by alangean** [comment]
> OM LX 4.3
> 
> I've changed my old multifunction printer with Epson XP-2150.
> 
> I downloaded drivers for printer, both USB and Wi-Fi. Subsequently, as Xsane (and skanlite) didn't recognize the device, I installed the driver Epson for Scan 2 (rpm package). Then, the Epson 2 scan front-end (installed togheter with driver) works, as skanlite, but:
> 
> Xsane crashes when device Epson XP-2150 is selected.
> 
> When launching from console, the following diagnostics apply:
> 
> Segmentation error (core dump) created.

With Xsane package upgrading this issue was solved.
