### ISSUE TITLE
PHP's timezonedb module not updated when PHP is updated

### ISSUE THREAD

**Issue by bogdro** [OpenMandrivaAssociation/distribution#2797]
**OpenMandriva version**:
4.3

**Describe the bug**:
After updating PHP, it reports warnings about mismatched timezonedb versions between the module and the version PHP was compiled with:
```
Warning: PHP Startup: timezonedb: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0
```

**Steps to reproduce**:
Run `php < /dev/null` in the shell.

**Observed behavior**:
PHP CLI displays the above warning.

**Expected behavior**:
PHP CLI does not display any warnings.

**Additional comment**:
This usually works correctly on each new "full" release/ISO - PHP and timezonedb matches.
The problems (this is not the first time) appear later, when new PHP packages are made available to be installed, but without new versions of the timezonedb module. Last time I checked (a few days ago), the timezonedb module was still in the old version.
A PHP build should trigger a rebuild of the timezonedb module that matches the PHP build. I don't know what's the impact of this and what could potentially stop working.

**Logs and screenshots if relevant**

**Comment by mandian** [comment]
@bogdro I rebuilt php-timezonedb. Please could you test it? It is now in testing repository so you should enable it before.

**Comment by bogdro** [comment]
Hi.
Checked http://abf-downloads.openmandriva.org/rock/repository/x86_64/main/testing/ -> php-timezonedb-2020.4-2-omv4003.x86_64.rpm
Confirmed - fixed!
Thank you, keep up the good work and keep updating php-timezonedb along with PHP! :)
If proper build management has been or will be introduced, defect can be closed.

**Comment by mandian** [comment]
> If proper build management has been or will be introduced, defect can be closed.

Actually there is not any automatism about packages to rebuild after an update. All we hone in the future ...
