### ISSUE TITLE
Installation error > grub2-install: error: efibootmgr: not found. 

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2807]
**OpenMandriva version**: Cooker

**Describe the bug**: Can not install on system using EFI.

**Steps to reproduce**: In VirtualBox with EFI enabled or on hw using EFI install as normal.

**Observed behavior**: Installation fails at building bootloader step.

**Expected behavior**: Installation proceeds to conclusion. Then user does first boot to installed system.

**Additional comment**:

**Logs and screenshots if relevant**

![Screenshot_20220702_113620](https://user-images.githubusercontent.com/5704386/177057154-2a02cc99-9760-448b-8eef-ef3732f5003d.jpg)

[calamares-instalation.log.txt](https://github.com/OpenMandrivaAssociation/distribution/files/9035491/calamares-instalation.log.txt)

**Comment by tpgxyz** [comment]
It looks like efibootmgr sefgaults. have you tried with efibootmgr-0.17-6 ?

**Comment by benbullard79** [comment]
> It looks like efibootmgr sefgaults. have you tried with efibootmgr-0.17-6 ?

Yes, no change with that version.

**Comment by benbullard79** [comment]
On installed (VBox) Cooker system just dsynced:

```
# grub2-install /dev/sda
Installing for x86_64-efi platform.
grub2-install: error: efibootmgr: not found.
```

**Comment by berolinux** [comment]
The efivar fix does fix the issue, it just has to be installed in the chroot as well.
