### ISSUE TITLE
Upgrading to latest kernel

### ISSUE THREAD

**Issue by Yuensan** [OpenMandrivaAssociation/distribution#2808]
Hello, I'm using OpenMandriva Lx 4.2 in VMware, and I'm trying to upgrade kernel 5.10.14 to latest kernel 5.18.9 using source code from kernel.org. I tried using command 
$ sudo dnf in kernel-desktop --refresh --enablerepo cooker-x86_64 

but it seems like there is “No such file or directory” error. The package is installed but the kernel does not run.
![image](https://user-images.githubusercontent.com/102211084/177112981-80607e40-6f1e-4baa-ae65-f5474095019f.png)
![image](https://user-images.githubusercontent.com/102211084/177113648-59486294-9841-41f1-ad4f-07477e3e8feb.png)

Besides that, i tried using sudo yum -y update but insufficient disk space problem occurs.
![image](https://user-images.githubusercontent.com/102211084/177113846-5970fcc2-f549-484f-9e6f-89e86fdc6eea.png)

May I know is there any solution to these problems, or is there an alternative method to upgrade kernel of OpenMandriva Lx 4.2  in VMware? Thanks in advance.

**Comment by benbullard79** [comment]
This is kind of  an unusual report as Lx 4.2 is way past End Of Life or EOL. 

I am not recommending this to users. However In VirtualBox OMLx 4.3 x86_64 system I can install latest Cooker kernel 5.18.13 and it definitely boots and seems to work OK. I know Cooker kernels are built with Cooker tool-chain packages which right now are very different from Rock/4.3 tool-chain. So we have a situation where the _Cooker kernel package will not build for Rock/4.3_ but it will install and boot. Beyond that I do not know all the implications of doing this type of thing.

I think it may be appropriate to close this as Won't_fix.
