### ISSUE TITLE
fprint package error

### ISSUE THREAD

**Issue by jr551** [OpenMandrivaAssociation/distribution#2810]
Problem: conflicting requests
- nothing provides libfprint.so.0()(64bit) needed by fprintd-0.9.0-1.x86_64

**Comment by tpgxyz** [comment]
@jr551 Thanks for pointing this out. Will fix this soon

**Comment by tpgxyz** [comment]
fprintd is fixed for cooker environment.

**Comment by jr551** [comment]
Thanks for your time contributing to an amazing distro

**Comment by tpgxyz** [comment]
Thanks, closing then this issue.
