### ISSUE TITLE
LibreOffice doesn't opens link in Firefox [solved]

### ISSUE THREAD

**Issue by Giorgio-IT** [OpenMandrivaAssociation/distribution#2814]
**OpenMandriva version**: Lx 4.3

**Describe the bug**: link in LibreOffice Writer doesn't opens in Firefox

**Steps to reproduce**: left click on link in Writer

**Observed behavior**: error message

**Expected behavior**: link opened in Firefox

**Additional comment**: bug affect only "main" user (the user created during installation), after updating Firefox to version 100.0.
Link in Okular opens normally in Firefox.

**Logs and screenshots if relevant** here's the error message
![errore_LO_2](https://user-images.githubusercontent.com/747201/181378918-88305378-8f89-493c-966a-b07b00acfafc.png)

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/libreoffice-non-apre-i-collegamenti-in-firefox/4531/11

**Comment by benbullard79** [comment]
Thanks for reporting.

**Comment by Giorgio-IT** [comment]
I installed OpenOffice and I have the same error.

**Comment by AngryPenguinPL** [comment]
Unable to reproduce it on firefox in cooker.
Make sure that default webbrowser is seleted as firefox here in default applications:
![2022-08-12_17-08](https://user-images.githubusercontent.com/3121142/184384769-0407846d-839c-4c3e-b8b4-d8b271bd49b8.png)

Also please check of this issue is available in cooker. Maybe it is affecting only Lx 4.3/

**Comment by Giorgio-IT** [comment]
I think the problem is not in Firefox.
I checked already default software:
![errore_LO_3](https://user-images.githubusercontent.com/747201/186615229-5bbb077d-dffc-49d3-906d-60be7d180425.png)
Don't think the issue is present in cooker. Till few weeks ago my LO worked normally, the bug appeared suddenly probably after several updates. And it affect only the "main"user.

**Comment by Giorgio-IT** [comment]
Removing and reinstalling Firefox solved the problem.

**Comment by Giorgio-IT** [comment]
Removing and reinstalling Firefox solved the problem.
