### ISSUE TITLE
OpenMandriva specific configs disappeared from LXQt desktop

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2815]
**OpenMandriva version**: 

Current LXQt desktop

**Describe the bug**: 

OpenMandriva specific configs disappeared.

**Steps to reproduce**: 

Boot and Rolling or Cooker LXQt iso. The screenshots are from Cooker LXQt iso # 1280 build on 2022-07-24.

**Observed behavior**:

![Screenshot_20220727_202123](https://user-images.githubusercontent.com/5704386/181401014-2365e42b-7538-4f29-b74b-26412fe505d3.jpg)

**Expected behavior**:

![Screenshot_20220727_202527](https://user-images.githubusercontent.com/5704386/181401045-3dfd9593-1360-468a-a8ca-ef14bc4b3f68.jpg)

**Additional comment**: 

All of that is a matter of tweaking configs
1. Make Menu panel white background instead of black or make the stuff show up on the black panel. The black panel might be better if that is possible
2. Remove Home, Trash, Computer, and Network from desktop
3. Add OM .svg icon to application menu

**Logs and screenshots if relevant**

I don't know where or how to make the changes so they appear in our packages, on our isos and installed LXQt systems.

These issues have been reported by several users.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/lxqt-rolling/4484/18

**Comment by benbullard79** [comment]
I am unsure if this report is really complete so let me know if anything else is needed. Reported by user in OpenMandriva forum and confirmed by me.

https://forum.openmandriva.org/t/lxqt-rolling/4484/

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/lxqt-rolling/4484/20

**Comment by tpgxyz** [comment]
Guess needs to update config patch

**Comment by benbullard79** [comment]
This is fixed with these iso's:

ROME:   https://abf.openmandriva.org/platforms/rolling/products/41/product_build_lists/1634

Cooker:   https://abf.openmandriva.org/platforms/cooker/products/39/product_build_lists/1635
