### ISSUE TITLE
LXQt desktop task manager and desktop switcher invisible

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2816]
**OpenMandriva version**:

LXQt desktop Cooker or Rolling. Screenshots are from Cooker LXQt iso # 1280 built on 2022-07-24.

**Describe the bug**:

Both task manager and desktop switcher appear to be enabled but are invisible.

**Steps to reproduce**:

Boot any current Cooker or Rolling LXQt iso and open a few applications and look for the desktop switcher. Right click in middle of lxqt-panel and select to open "Manage Widgets" and check to see if "Task Manager" and "Desktop Switcher" are enabled. 

**Observed behavior**:

Both task manager and desktop switcher appear to be enabled but are invisible.

**Expected behavior**:

The open applications appear in task manager like the do on KDE Plasma desktop. That desktop switcher is visible and user can switch desktops.

**Additional comment**:

Reported by user in OpenMandriva forum and confirmed by me.

https://forum.openmandriva.org/t/lxqt-rolling/4484/

**Logs and screenshots if relevant**

Screenshot showing 3 applications open and nothing in task manager. This means apps that are minimized disappear, can not be brought back. Notice to left of screen in panel no desktop switcher is visible.

![Screenshot_20220727_210550](https://user-images.githubusercontent.com/5704386/181405794-b7e64035-c758-4d58-a988-e96dd736089f.jpg)

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/lxqt-rolling/4484/19

**Comment by benbullard79** [comment]
Looks like someone filed bug report upstream about this:

https://github.com/lxqt/lxqt/discussions/2288

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/lxqt-rolling/4484/20

**Comment by tpgxyz** [comment]
Hi,
we are carrying this config here
https://github.com/OpenMandrivaAssociation/lxqt-panel/blob/780d9159a45fd0e8a381c1c1e0522b3c40a8b3ec/lxqt-panel-0.8.0-omv-settings.patch#L52


This means it is global settings, not user ones.

**Comment by benbullard79** [comment]
Maybe it is this?      https://github.com/lxqt/lxqt-session/issues/427

**Comment by tpgxyz** [comment]
Please try lxqt-session-1.2.0-5 as it do have patch from upstream.

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/how-to-select-best-om-vesion-for-older-laptop/4843/4

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/how-to-select-best-om-vesion-for-older-laptop/4843/8

**Comment by benbullard79** [comment]
Tested this fix on ROME iso 1761 and in installed system from that iso. Fix for this looks like:

`$ sudo dnf in kwindowsystem-x11`

That pulls in 4 other packages. These 3 are not needed and can be removed:

```
x11-server
x11-server-xnest
x11-server-xvfb
```

`lib64xcb-res0` and `kwindowsystem-x11` are all that is needed to correct this.

bero is adding these to the package list for new isos.

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/fix-for-bugs-in-lxqt-desktop-2816/4845/1

**Comment by berolinux** [comment]
It's just a missing dependency. `dnf install kwindowsystem-x11` or update to the current cooker package.
