### ISSUE TITLE
Appmenu patch .desktop files

### ISSUE THREAD

**Issue by rugyada** [OpenMandrivaAssociation/distribution#2817]
**Kate:**
In default installation the Kate icon is the only one listed under Development category. This makes the application menu one line more high without any practical reason.

Request to patch
`/usr/share/applications/org.kde.kate.desktop`

from:
`Categories=Qt;KDE;Utility;TextEditor;Development;`
to:
`Categories=Qt;KDE;Utility;TextEditor;`
(same as Kwrite)

The change is mostly cosmetic for a more clean and tidy look, in the mean time easily doable.

**Emoji Selector:**
Not seeing any reason why it's there. If it cannot be removed from Plasma, at least let's hide it.

Request to patch
`/usr/share/applications/org.kde.plasma.emojier.desktop`

add:
`NoDisplay=true`

**Comment by AngryPenguinPL** [comment]
reopen as is only fixed in kate

**Comment by rugyada** [comment]
Thanks
