### ISSUE TITLE
No HP icon for HPLIP in Cooker

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2819]
**OpenMandriva version**: Cooker

**Describe the bug**: After HPLIP is installed, there is no HP icon for the menu entry.

**Steps to reproduce**: Open menu, migrate to System, look for HP Graphical Tools.

**Observed behavior**: No menu icon.

**Expected behavior**: Icon should have installed with the package.

**Additional information**: HPLIP version 3.22.6

![hplip](https://user-images.githubusercontent.com/73129450/183250750-390bbb79-41b2-45e6-8009-94703c974d2c.png)

**Comment by tpgxyz** [comment]
Hi @edwardp3 please try with hplip-3.22.6-3

**Comment by edwardp3** [comment]
Hi @tpgxyz  Confirming fixed, printer icon present. Thank you.
