### ISSUE TITLE
Require enchant as a dependency for claws-mail

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2826]
I have a few OpenMandriva VirtualBoxes installed, all running Cooker and I use Claws Mail. On one VBox, I was initially not able to get Claws Mail to recognize the spellchecker, the dictionary pull down list was empty. I then looked at all of the other OMA VBoxes and made sure the same dictionary packages were installed. Some of the builds install **enchant** by default and I didn't realize this until I did further checking. Once I installed enchant on this VBox, the Claws spellchecker kicked right in.

I would like to recommend that **enchant** be a dependency when installing claws-mail.

Thank you.

**Comment by tpgxyz** [comment]
@edwardp3 Hello, thanks for your input. Have you considered to prepare a Pull Request for https://github.com/OpenMandrivaAssociation/claws-mail with `Requires: enchant ` ?

**Comment by edwardp3** [comment]
Submitted. Thanks.

https://github.com/OpenMandrivaAssociation/claws-mail/pull/4

**Comment by AngryPenguinPL** [comment]
Should be fixed. 
Thanks.
