### ISSUE TITLE
om-control-center in Cooker not working - will launch but none of the selections work

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2829]
**OpenMandriva version**:

Cooker

**Describe the bug**:

Launched om-control-center from GUI, main screen loads, but selecting an entry does not do anything. Wanted to see Display setting.

**Observed behavior**:

No response when Display and Monitor was selected.

**Expected behavior**:

Some sort of screen with current settings should have displayed.

**Logs and screenshots if relevant**

When run from terminal window (GUI launches, no selections work):

```
~]$ om-control-center
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
[3560:7:0813/211147.664874:ERROR:command_buffer_proxy_impl.cc(141)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
/usr/share/om-control-center/apps/02-xfdrake.run: line 2: exec: kcmshell5: not found
```

When run from terminal as superuser (GUI does not launch):

```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[3604:3604:0813/211226.321877:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

```

Running xfdrake from terminal:
```

~]$ xfdrake
Traceback (most recent call last):
  File "/usr/bin/cnf", line 19, in <module>
    sys.argv = [x.decode(sys.stdout.encoding) for x in sys.argv]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/cnf", line 19, in <listcomp>
    sys.argv = [x.decode(sys.stdout.encoding) for x in sys.argv]
                ^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?

```

**Comment by benbullard79** [comment]
I must be missing something about this report. `xfdrake` should result in command not found. We got rid of drakx tools a few years ago. To start OM Control Center the command is `om-control-center`:

![Screenshot_20220813_210300](https://user-images.githubusercontent.com/5704386/184519486-e6637a27-dde7-4ad9-8350-1d56584a2e3c.jpg)

And it is working here.

**Comment by benbullard79** [comment]
I do see there are still some drak packages in repositories but those are not used and have not been for some time. This could be a housekeeping issue or maybe devs think they should not be removed yet for reasons I can not imagine.

`dnfdrake` is something new, not related to the old drakx tools except in name.

**Comment by rugyada** [comment]
om-control-center and om-welcome are tools made for KDE Plasma environment.

drakx-whatever filenames have been kept for convenience only. Script filenames don't matter at all and have nothing to do with the actual command they run, the scripts are shortcuts to KDE Plasma systemsettings modules. Open the files and just look at the content.

Alternative desktops must use their own native system settings tools.

**Comment by edwardp3** [comment]
My latest OpenMandriva VirtualBox, was created with Cooker Xfce build # 1308 from ABF and om-control-center is on the Settings menu. If om-c-c isn't designed for the alternative desktops, in attempting to remove it, dnf wants to remove additional packages. I left everything intact.

![om-control-center](https://user-images.githubusercontent.com/73129450/184538624-5608a906-f337-4110-bfe8-fc53c999a17e.png)

```
Removing:
 om-control-center          noarch  0.2.9-1               @cooker-x86_64  1.1 M
Removing unused dependencies:
 htmlscript                 x86_64  1.0.1-1               @cooker-x86_64   63 k
 kdialog                    x86_64  1:22.07.90-1          @cooker-x86_64  578 k
 lib64Qt5WebEngine5         x86_64  5.15.10-0.20220628.1  @cooker-x86_64  557 k
 lib64Qt5WebEngineCore5     x86_64  5.15.10-0.20220628.1  @cooker-x86_64  129 M
 lib64Qt5WebEngineWidgets5  x86_64  5.15.10-0.20220628.1  @cooker-x86_64  351 k
 lib64freebl3               x86_64  1:3.81-1              @cooker-x86_64  1.2 M
 lib64harfbuzz-subset       x86_64  5.1.0-1               @cooker-x86_64  1.1 M
 lib64minizip-ng3           x86_64  3.0.6-1               @cooker-x86_64  164 k
 lib64qt5positioning5       x86_64  5.15.5-1              @cooker-x86_64  357 k
 lib64qt5positioningquick5  x86_64  5.15.5-1              @cooker-x86_64  129 k
 lib64qt5webchannel5        x86_64  5.15.5-1              @cooker-x86_64  148 k
 lib64re2_9                 x86_64  2021.09.01-1          @cooker-x86_64  355 k
 lib64snappy1               x86_64  1.1.7-3               @cooker-x86_64   32 k
 lib64z-ng1                 x86_64  2.0.6-3               @cooker-x86_64  135 k
 nss-shlibsign              x86_64  1:3.81-1              @cooker-x86_64   25 k
 qt5-qtpositioning          x86_64  5.15.5-1              @cooker-x86_64  285 k
 qt5-qtwebengine            x86_64  5.15.10-0.20220628.1  @cooker-x86_64   25 M

Transaction Summary
================================================================================
Remove  18 Packages

Freed space: 160 M
Is this ok [y/N]: n
Operation aborted.

```

**Comment by rugyada** [comment]
> om-control-center is on the Settings menu.


@edwardp3 
Right, it's been an oversight.
Thanks for reporting. I will remove it from iso packages lists.

Meanwhile if you want to remove in your system:
`sudo rpm -e --nodeps om-control-center`

**Comment by benbullard79** [comment]
The remaining drak, drakx, ect. packages should be removed from repos now. 

`dnfdrake` remains as that is currently a valid package.

**Comment by edwardp3** [comment]
_I must recommend that om-control-center be available for all desktops._ 

I am trying to change the shell for my account in my Xfce VBox to see if ti fixes an issue with neofetch. 

The `chsh` command does not work and there is no man page for it.

```
epp@openmandriva ~]$ chsh --help
Traceback (most recent call last):
  File "/usr/bin/cnf", line 19, in <module>
    sys.argv = [x.decode(sys.stdout.encoding) for x in sys.argv]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/cnf", line 19, in <listcomp>
    sys.argv = [x.decode(sys.stdout.encoding) for x in sys.argv]
                ^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
[epp@openmandriva ~]$ man chsh
No manual entry for chsh
[epp@openmandriva ~]$ chsh tcsh
Traceback (most recent call last):
  File "/usr/bin/cnf", line 19, in <module>
    sys.argv = [x.decode(sys.stdout.encoding) for x in sys.argv]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/cnf", line 19, in <listcomp>
    sys.argv = [x.decode(sys.stdout.encoding) for x in sys.argv]
                ^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
[epp@openmandriva ~]$ chsh /usr/bin/tcsh
Traceback (most recent call last):
  File "/usr/bin/cnf", line 19, in <module>
    sys.argv = [x.decode(sys.stdout.encoding) for x in sys.argv]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/cnf", line 19, in <listcomp>
    sys.argv = [x.decode(sys.stdout.encoding) for x in sys.argv]
                ^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
```

On the Xfce menu, there is no option to add/remove/modify users. So the only other way to be able to do this, would be under the System menu in the OM Control Center (Add and Configure user and groups).

**Comment by rugyada** [comment]
Not sure if kuser works in xfce. You may try.
`$ sudo kuser`

**Comment by edwardp3** [comment]
OM Control Center isn't working with Plasma/Cooker either. Attempted to change the shell in the Plasma VBox and upon entering the root password to modify the user, it said it could not launch `kuser`. Screenshot taken fron host OS.

`sudo kuser: command not found`

`
![omcontrolcenter](https://user-images.githubusercontent.com/73129450/185815038-9f4140a1-b07d-417b-9c66-98d27b78d0c4.png)

**Comment by rugyada** [comment]
Is kuser installed?
```
$ rpm -q kuser
kuser-16.08.3-7.x86_64
```

**Comment by edwardp3** [comment]
It wasn't. I just installed it, changed it to bin/sh, but it did not affect the neofetch display, so it's not the shell. Updating that bug report now.

**Comment by rugyada** [comment]
> Thanks for reporting. I will remove it from iso packages lists.

Done.
