### ISSUE TITLE
screengrab - does not launch after installation

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2831]
**OpenMandriva version**:

Cooker (installed in VirtualBox)

**Describe the bug**:

Attempted to take screengrab of black Chromium browser window, but Screengrab would not launch from the Plasma/X11 menu after installation via dnf.

**Steps to reproduce**:

Select Screengrab from Plasma menu, does not launch, does not display its bouncing icon.

**Observed behavior**:

None

**Expected behavior**:

Screengrab should have launched.

**Logs and screenshots if relevant**

Screenshot taken from host OS, terminal displays error when screengrab was launched from a terminal window.

![screengrab-openmandriva](https://user-images.githubusercontent.com/73129450/185438537-ab378d5b-74f0-4418-8012-a4a9b0c30606.png)

**Comment by tpgxyz** [comment]
Gonna fix this soon

**Comment by tpgxyz** [comment]
ok screengrab-2.4.0-2 and lib64qt5xdg3-3.9.1-2 fxes the issue.
