### ISSUE TITLE
Qt Creator does not open

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2832]
**OpenMandriva version**:

Cooker znver1 fully dsynced.

**Describe the bug**:

Qt Creator does not open

**Steps to reproduce**:

Install Qt Creator from OM-Welcome and try to open

**Observed behavior**:

Does not open

**Expected behavior**:

That the application opens normally and works OK

**Additional comment**:

Konsole output:

`qtcreator`
`qtcreator: error while loading shared libraries: libExtensionSystem.so.8: cannot open shared object file: No such file or directory`

That .so .8 file is in /usr/lib64/qtcreator

**Logs and screenshots if relevant**

`rpm -qa | grep qt-creator`
`qt-creator-common-8.0.0-2.noarch`
`qt-creator-8.0.0-2.znver1`

[omdv-bug-report-20220821072411.log](https://github.com/OpenMandrivaAssociation/distribution/files/9389086/omdv-bug-report-20220821072411.log)

_Workaround to open Qt Creator:_ Open terminal and run:

`LD_LIBRARY_PATH=/usr/lib64/qtcreator qtcreator`

![Screenshot_20220821_072602](https://user-images.githubusercontent.com/5704386/185791545-c29f7020-f345-45d2-b93d-960e8d5b1213.png)

![Screenshot_20220821_072629](https://user-images.githubusercontent.com/5704386/185791550-b9f412de-0f0e-4e9b-aae9-5c30f59917a7.png)

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/qt-creator-wont-open/4592/7
