### ISSUE TITLE
lib64qt5svg5 - mirror error - dnf reported interrupted by header callback - report issue to maintainer

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2833]
**OpenMandriva version**:

Cooker

**Describe the bug**:

Updated VBox install via `sudo dnf clean all ; sudo dnf dsync` and dnf reported a mirror error relating to `lib64qt5svg5`:

`[MIRROR] lib64qt5svg5-5.15.5-2-omv4090.x86_64.rpm: Interrupted by header callback: Inconsistent server data, reported file Content-Length: 135672, repository metadata states file length: 135652 (please report to repository maintainer)
`

**Steps to reproduce**:

As above.

**Observed behavior**:

dnf proceeded to update other packages, then displayed the above error.

**Expected behavior**:

Server data should have matched.

**Logs and screenshots if relevant**

dnf otherwise appeared to install the package without further issue (21/22):

```
(18/22): lib64Qt5QuickTemplates2_5-5.15.5-2-omv 1.5 MB/s | 415 kB     00:00    
(19/22): lib64wpe1-1.12.3-1-omv4090.x86_64.rpm  161 kB/s |  24 kB     00:00    
(20/22): libksane-22.08.0-1-omv4090.x86_64.rpm  474 kB/s |  84 kB     00:00    
(21/22): lib64qt5svg5-5.15.5-2-omv4090.x86_64.r 208 kB/s | 132 kB     00:00    
(22/22): qt5-qtimageformats-5.15.5-2-omv4090.x8 132 kB/s |  63 kB     00:00   
```

` Upgrading        : lib64qt5svg5-5.15.5-2.x86_64                         18/42 `

` Cleanup          : lib64qt5svg5-5.15.5-1.x86_64                         23/42 `

```
  Verifying        : lib64qt5svg5-5.15.5-2.x86_64                         35/42 
  Verifying        : lib64qt5svg5-5.15.5-1.x86_64                         36/42 
```

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/lib64qt5svg5-mirror-error-report-issue-to-maintainer/4600/1

**Comment by benbullard79** [comment]
If you see something like this you probably caught the system while some publishing was in progress. Wait a bit and try again. This is common in Cooker where there are many days where hundreds of packages are published.

I updated an x86_64 Cooker VM about 2 hours ago with no errors. So I believe that makes this "fixed"?

That package was included in the upgrade:

`2022-08-24T13:24:32-0500 DEBUG Upgraded: lib64qt5svg5-5.15.5-2.x86_64`

**Comment by edwardp3** [comment]
Thank you.

The package was reinstalled using dnf.
