### ISSUE TITLE
mate-themes - some themes are missing graphics above the Firefox Menu bar

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2837]
**OpenMandriva version**: Cooker (installed in a VirtualBox)

**Describe the bug**: Went through some of the MATE themes and noticed graphics are missing with the TraditionalGreen, TraditionakOk, YaruGreen and YaruOk themes, above the Menu bar in Firefox.

**Steps to reproduce**: Login to MATE desktop and launch Firefox, Go to System/Preferences/Look and Feel/Appearance and select any of the above four themes. Does not occur with the other installed MATE themes.

**Observed behavior**: Gaps in graphics with those particular themes.

**Expected behavior**: No gaps in graphics.

**Additional comment**: Used the same themes with Claws Mail, themes appeared as expected, no gaps in graphics. The mate-themes package version in Cooker-Unsupported, is referencing omv4050 `mate-themes-3.22.23-1-omv4050.noarch.rpm`

**Logs and screenshots if relevant**

TraditionalGreen
![TraditionalGreen](https://user-images.githubusercontent.com/73129450/187705233-84945803-f9e1-4dfa-8813-92276317ccd1.png) 

TraditionalOk
![TraditionalOk](https://user-images.githubusercontent.com/73129450/187705236-53beecc6-92c8-471b-8438-504df845070e.png) 

YaruGreen
![YaruGreen](https://user-images.githubusercontent.com/73129450/187705237-bf52cd1a-ea21-449a-b538-26139c254ca7.png)

YaruOk
![YaruOK](https://user-images.githubusercontent.com/73129450/187705810-aaec98a2-b79d-480a-a048-b02dbae7be83.png)

Claws Mail YaruOK
![ClawsMailYaruOk](https://user-images.githubusercontent.com/73129450/187707782-20df5d79-32ba-468a-bf23-5facc904fc00.png)

**Comment by benbullard79** [comment]
Not sure what to say other than the OP told us he would not use OMLx anymore.
