### ISSUE TITLE
Firefox 104.0.1 update reset profiles

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2838]
**OpenMandriva version**: Cooker (installed in VirtualBox)

**Describe the bug**: Firefox updated from 103.0 to 104.0.1 and found the previously used profile was now "empty", the saved Bookmarks and Add-Ons were gone. Firefox launched using a new, clean profile.

**Steps to reproduce**: Update Firefox.

**Observed behavior**: Upon first launch, it began with a brand new profile. Found a new, third profile in ~/.mozilla/firefox ending with `.default-release-1` and when I tried the other two profiles via about:profiles, all of them launched Firefox with a new, empty profile (no saved bookmarks or Add-Ons).

**Expected behavior**: Firefox should have launched with the previously-saved profile.

**Additional information**: I still have Firefox 103.0 in one of the other VirtualBoxes and it launched with the previously-saved profile, with saved Bookmarks and Add-Ons.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/firefox-update-in-cooker-reset-profile-bookmarks-add-ons-gone/4624/3

**Comment by benbullard79** [comment]
I can confirm that whenever FF is upgraded it does create a new profile here, but my old profile is intact and I am able to use that.

_Workaround:_ Whenever FF is upgraded I try to be sure to open the new version from terminal with `firefox -p` and in that case it usually opens to the old profile and no new profile is created.

**Comment by benbullard79** [comment]
No FF 104 anymore so invalid.
