### ISSUE TITLE
xfce4-pulseaudio-plugin not launching PulseAudio (pavucontrol) when Audio Mixer is selected

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2840]
**OpenMandriva version**: Rolling, Cooker

**Describe the bug**: Clicking the Xfce PulseAudio plugin, displays minimal volume control settings for the active audio devices (headphones/microphone). Clicking "Audio Mixer..." displays an error "Failed to execute command "pavucontrol".

PulseAudio is installed, it's displayed on the Xfce Multimedia menu.

**Steps to reproduce**: Click Xfce PulseAudio plugin, select "Audio mixer..."

**Observed behavior**: Error appears as described, screenshot below.

**Expected behavior**: Should have launched the PulseAudio Volume Control UI (pavucontrol).

**Additional comment**:

**Logs and screenshots if relevant**

![xfce4-pulseaudio-plugin](https://user-images.githubusercontent.com/73129450/189248801-fd13b51e-93eb-4844-8245-a6871bda4090.png)

**Comment by tpgxyz** [comment]
Does this occur with xfce4-pulseaudio-plugin-0.4.4 ?

**Comment by edwardp3** [comment]
Yes. 0.4.4 is the currently-installed version.

**Comment by AngryPenguinPL** [comment]
As simple workaround please install pavucontrol-qt

**Comment by edwardp3** [comment]
In Cooker, there was an update today of `xfce4-pulseaudio-plugin` and `pavucontrol-qt `was listed as a new dependency that also installed. I clicked the plugin and the PulseAudio controls opened right up.

**Comment by AngryPenguinPL** [comment]
Hi.
Package 0.4.5-1 should fix this issue for good. After installing it pavucontrol-qt is no longer needed. This plugin should open directly pavucontrol (not a QT one).

Fixed by
https://github.com/OpenMandrivaAssociation/pulseaudio/commit/6b9037e334ed01a500d6ade859826767411dce44
https://github.com/OpenMandrivaAssociation/xfce4-pulseaudio-plugin/commit/e5647bbf02646eb13af6b530f2d12ed380d331a4

**Comment by edwardp3** [comment]
> Hi. Package 0.4.5-1 should fix this issue for good. After installing it pavucontrol-qt is no longer needed. This plugin should open directly pavucontrol (not a QT one).
> 
> Fixed by [OpenMandrivaAssociation/pulseaudio@6b9037e](https://github.com/OpenMandrivaAssociation/pulseaudio/commit/6b9037e334ed01a500d6ade859826767411dce44) [OpenMandrivaAssociation/xfce4-pulseaudio-plugin@e5647bb](https://github.com/OpenMandrivaAssociation/xfce4-pulseaudio-plugin/commit/e5647bbf02646eb13af6b530f2d12ed380d331a4)


Confirmed fixed in Cooker, upon removal of pavucontrol-qt.

Thank you.
