### ISSUE TITLE
Firefox 104.0.1 tab crashes on Jitsi when in a meeting room

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2842]
**OpenMandriva version**: Rolling (untested with Cooker)

**Describe the bug**: After logging into Jitsi, went into a meeting room with a dozen other participants. The Jitsi on-screen interface was non-responsive and the browser tab eventually crashed. 

**Steps to reproduce**: As above.

**Observed behavior**: As above.

**Expected behavior**: The Firefox tab should not have crashed and the Jitsi on-screen interface should have been responsive.

**Additional comment**: Restoring the crashed tab, reproduced the issue. Later on in the day, went into the same Jitsi room, as the only participant. The Jitsi interface was responsive and the tab did not crash. 

**Logs and screenshots if relevant**

![firefox-jitsi](https://user-images.githubusercontent.com/73129450/189484711-90fafe13-75e9-4bd1-9e8f-cd3055b38860.jpg)

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/issues-with-installed-rolling-firefox-audio-usb-bluetooth/4645/7

**Comment by benbullard79** [comment]
We are past FF 104 so this is invalid.
