### ISSUE TITLE
Application Menu - Add/Remove Favorites not responsive

### ISSUE THREAD

**Issue by rugyada** [OpenMandrivaAssociation/distribution#2844]
**OpenMandriva version**:
Cooker and ROME. I don't remember if 4.3 was affected too.

**Describe the bug**:
Add and/or remove favorites is not immediately responsive

**Steps to reproduce**:
Add and/or remove favorites in Application menu

**Observed behavior**:
Apparently do nothing

**Expected behavior**:
Favorites added or removed in real time

**Additional comment**:
The changes apply by switching to alternative widget in current session, or until session logout/login.

**Logs and screenshots if relevant**

This works:
![ss_20220912_141317](https://user-images.githubusercontent.com/46781309/189657683-614d4a13-a93f-4545-b96b-eab3726abf8c.jpg)

These not working.
Also workaround to make favorites changes applyed. Just for report purpose, that's far from being acceptable.

![ss_20220912_141407](https://user-images.githubusercontent.com/46781309/189658776-b29bb27c-b755-43f2-9ab4-b5ca2ef4a92e.jpg)

![ss_20220912_141611](https://user-images.githubusercontent.com/46781309/189658846-dc074682-8299-4b26-b130-578272a8e9b7.jpg)

![ss_20220912_141703](https://user-images.githubusercontent.com/46781309/189658892-b3d7efae-24f8-49b9-85fa-ad29415b3c4e.jpg)

![ss_20220912_141746](https://user-images.githubusercontent.com/46781309/189658931-1cacf6e2-05ed-4e74-8eb3-ceb37b860824.jpg)

![ss_20220912_141902](https://user-images.githubusercontent.com/46781309/189658963-8cb57c71-3ed6-4bcb-a33d-9874be918744.jpg)

![ss_20220912_142002](https://user-images.githubusercontent.com/46781309/189659003-3a1bd80f-f5e2-4f3a-99bf-444011b08787.jpg)

![ss_20220912_142238](https://user-images.githubusercontent.com/46781309/189659034-b91114f5-862c-4010-b2e5-791e5f6b1768.jpg)

![ss_20220912_142341](https://user-images.githubusercontent.com/46781309/189659053-7f0ac3b3-7bf0-4bfe-907b-806c00468237.jpg)

**Comment by rugyada** [comment]
All of the most recent KDE stuff upgrades did not fix the issue.

**Comment by rugyada** [comment]
> All of the most recent KDE stuff upgrades did not fix the issue.

Idem on 23 Oct. 2022

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/having-problems-with-launcher-favourites/4693/2

**Comment by rugyada** [comment]
The issue should get fixed with upcoming Plasma6.
