### ISSUE TITLE
Xfce x86_64  build ID 1308 simple-scan, xsane and skanlite all will not launch - lib64sane1 package was missing, should be a depencency

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2846]
**OpenMandriva version**: Rolling (possibly Cooker as well)

**Describe the bug**: Installed scanner applications would not launch, until `lib64sane1` was installed.

**Steps to reproduce**: Installed simple-scan, xsane and skanlite. Launch any of them, none will launch.

**Observed behavior**: None of the three scanner applications would launch.

**Expected behavior**: They should have launched.

**Additional comment**: The package `lib64sane1` should have been included as a dependency. Once installed, they all launched. Tried to submit this as a Pull Request, but the icon was grayed out.

**Logs and screenshots if relevant**

**Comment by AngryPenguinPL** [comment]
Hi.
From what ISO system was installed?

**Comment by edwardp3** [comment]
I used the Cooker Xfce x86_64 build # 1308 ISO from ABF to install, then converted to Rolling.

**Comment by AngryPenguinPL** [comment]
Ok, thanks for info. I try add it on ISO and also I will try to add it as a dependency for these individual packages to make sure it it pulled everytime.

In progress

**Comment by AngryPenguinPL** [comment]
Fixed in Cooker.
