### ISSUE TITLE
Thunderbird not displaying new email notifications unless lower right section of screen is moused-over

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2847]
**OpenMandriva version**: Cooker and Rolling

**Describe the bug**: Thuinderbird (current version 102.2.0) is not displaying new email notifications unless the lower right section of the window is moused-over. This also occurred with at least the previous version.

**Steps to reproduce**: Launch Thunderbird, wait for a new email to come in, notification not displaying unless lower right section of screen is moused-over. The default sound on a new mail, is playing, however.

**Observed behavior**: Notifications not displayed unless lower right section of screen is moused-over.

**Expected behavior**: Notifications should automatically appear without user intervention.

**Additional comment**: Installed in a VirtualBox, via Cooker Xfce ABF Build # 1308. Not known if packaging, upstream, or VirtualBox issue.

**Logs and screenshots if relevant**

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/thunderbird-not-displaying-new-mail-notifications-unless-lower-right-of-screen-is-moused-over/4657/1

**Comment by benbullard79** [comment]
Not sure what to say other than the OP told us he would not use OMLx anymore.
