### ISSUE TITLE
Localization issue in Live mode

### ISSUE THREAD

**Issue by rugyada** [OpenMandrivaAssociation/distribution#2848]
**OpenMandriva version**:
Cooker, and ROME Gold candidate

**Describe the bug**:
Localization not working for some languages

**Steps to reproduce**:
More in detail in the topic at forum
https://forum.openmandriva.org/t/4655

**Expected behavior**:
System properly localized

**Additional comment**:
Testing in live mode.
Maybe related, but the user reported only installed system affected:
https://forum.openmandriva.org/t/4663/10

**Logs and screenshots if relevant**

French language selected at ISO boot menu

![ss_20221004_134401](https://user-images.githubusercontent.com/46781309/193821996-e24fe910-3546-4c37-a20d-784e70ea0aff.jpg)

![ss_20221004_134646](https://user-images.githubusercontent.com/46781309/193822334-ae574c2f-9aa7-437c-acad-0549f6dba1e0.jpg)

![ss_20221004_134723](https://user-images.githubusercontent.com/46781309/193822457-5a0dfd66-c78c-4aea-ae2a-f5c522ccb0df.jpg)

![ss_20221004_134830](https://user-images.githubusercontent.com/46781309/193822533-878b1d8a-8664-4d40-aa70-b1878fff3d7f.jpg)

After language change in systemsettings, the desktop language is **partly** fixed but console cries:

![ss_20221004_135455](https://user-images.githubusercontent.com/46781309/193823724-b8b82c25-eba3-4989-8385-e3d9974048be.jpg)

![ss_20221004_140937](https://user-images.githubusercontent.com/46781309/193824219-3f806bc3-bfb0-428b-b63e-1aa2c97569bd.jpg)

![ss_20221004_150329](https://user-images.githubusercontent.com/46781309/193826422-526cec32-c45f-407c-a800-899a24a12f48.jpg)

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/cooker-and-rome-iso-localization-live-mode/4655/7

**Comment by rugyada** [comment]
In installed system localization seems working as expected
https://forum.openmandriva.org/t/cooker-and-rome-iso-localization-live-mode/4655/8

Changed the title to reflect what the problem is actually about.

**Comment by tpgxyz** [comment]
What does says `sudo localectl` when you boot with french language ?

**Comment by rugyada** [comment]
@tpgxyz 

![ss_20221006_104746](https://user-images.githubusercontent.com/46781309/194267791-51dcf42a-96c0-493e-8e82-b3d4aa6944bb.jpg)

```
[live@omv-1403 ~]$ sudo localectl
Warning: Settings on kernel command line override system locale settings in /etc/locale.conf.
    Command Line: LANG=fr_FR.utf8
   System Locale: LANG=en_US.utf8
       VC Keymap: us
      X11 Layout: n/a
```

**Comment by rugyada** [comment]
ROME installed system, if of any help:

```
[ruru@1403-rome-FR ~]$ sudo localectl
[sudo] Mot de passe de ruru : 
   System Locale: LANG=fr_FR.UTF-8
       VC Keymap: it
      X11 Layout: it
```

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/om-rome-gold-konsole/4669/3

**Comment by tpgxyz** [comment]
> Command Line: LANG=fr_FR.utf8
>    System Locale: LANG=en_US.utf8

This explains a lot. Somehow language selected from grub2 menu is not set as a system language.

**Comment by rugyada** [comment]
Issue fixed. Thanks to @berolinux 

![ss_20221022_175911](https://user-images.githubusercontent.com/46781309/197350282-15f5bdc3-d96f-4642-b29f-598463f16fd9.jpg)

![ss_20221022_180126](https://user-images.githubusercontent.com/46781309/197350291-29f4c640-d32e-4250-b14f-3ca8627f827d.jpg)

**Comment by aario** [comment]
> Issue fixed. Thanks to [@berolinux](https://github.com/berolinux)

Would be awesome if you had shared the solution with us 🙂

**Comment by rugyada** [comment]
It was at system/updates level, not a trick or a workaround.
I can't remember right now the specific commit, sorry.
