### ISSUE TITLE
 Firefox on wayland by default 

### ISSUE THREAD

**Issue by yusssufff** [OpenMandrivaAssociation/distribution#2849]
It would be very nice to flag Firefox so it could run default on wayland instead of xwayland on a wayland session.
That is how it is on OpenSuSE, Fedora, Gentoo, ALTLinux, Rosa Linux…

**Comment by AngryPenguinPL** [comment]
Package with Wayland enabled by default compiling right now in Cooker.
It brings also vaapi enabled.

**Comment by AngryPenguinPL** [comment]
Done. Fixed and update to 106.0.1 package in Cooker.
https://github.com/OpenMandrivaAssociation/firefox/commit/b44f9111fb636750d414889f3d994f6d03f8dcae
