### ISSUE TITLE
kernel-desktop-gcc 6.0.0 preventing Plymouth bootsplash (at least in Rolling) from appearing with AMD/Radeon graphics installed

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2851]
Please see OMA Forum thread for details. 

https://forum.openmandriva.org/t/lost-plymouth-bootsplash-on-rolling-after-installing-gcc-kernel-6-0-0-upon-reboots-after-the-initial-boot/4670

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/lost-plymouth-bootsplash-on-rolling-after-installing-gcc-kernel-6-0-0-upon-reboots-after-the-initial-boot/4670/11

**Comment by tpgxyz** [comment]
@edwardp3 issue is related to broken gawk-5.2.x that was released by mistake. Make sure your are running only gawk-5.1.x then rebuild your initrd with ‘dracut -f’

**Comment by benbullard79** [comment]
Not sure what to say other than the OP told us he would not use OMLx anymore.
