### ISSUE TITLE
Firefox from ABF Xfce Builds displays the window frame then crashes

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2853]
**OpenMandriva version**: Cooker

**Describe the bug**: Installed ABF Xfce Cooker builds 1356, 1418 and 1419 in VirtualBoxes. Firefox included with all of these, will display only a window frame when launched, then eventually crashes.

Ran `ldd` on the Firefox directory for libxul.so and it reported the following libraries were missing:

libmozsandbox.so
liblgpllibs.so
libmozsqlite3.so
libmozgtk.so
libmoxwayland.so

**Steps to reproduce**: Installed one of the above builds, launched Firefox on the first login after reboot, Firefox launches displaying a window frame then eventually crashes.

**Observed behavior**: As above.

**Expected behavior**: Firefox should have launched normally without crashing.

**Additional comment**: Reported at https://forum.openmandriva.org/t/abf-cooker-xfce-image-build-1356/4615

Downloaded and installed latest Firefox version from Mozilla, that launched and worked perfectly.

**Please be advised that due to issues with the host Linux OS repeatedly freezing while I am using a VirtualBox, the host OS will be removed, removing the VirtualBoxes in the process and replacing this with another host OS, in which I plan on not using VirtualBox further. I am willing to keep the system as is, pending resolution of this bug report.** 

Text from terminal when running Firefox included with the builds:
```
~]$ firefox
console.error: Region.jsm: "Error fetching region" (new TypeError("NetworkError when attempting to fetch resource.", ""))
console.error: Region.jsm: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.jsm", 421))
Exiting due to channel error.
Exiting due to channel error.
Segmentation fault (core dumped)
```

**Logs and screenshots if relevant**

![image](https://user-images.githubusercontent.com/73129450/194954737-69db5968-e5a3-42aa-a619-066dc185b36a.png)

[coredumpctl-debug-1467.txt](https://github.com/OpenMandrivaAssociation/distribution/files/9749365/coredumpctl-debug-1467.txt)
[coredumpctl-debug-1516.txt](https://github.com/OpenMandrivaAssociation/distribution/files/9749366/coredumpctl-debug-1516.txt)

**Comment by edwardp3** [comment]
With ABF Build 1419, Firefox launches and runs correctly, but only when run in the Live environment. Once the build was installed to a VirtualBox, the original error as reported, occurs.

Live environment: 
![live1419fx-tb](https://user-images.githubusercontent.com/73129450/196241497-cd662e53-a71e-421b-876c-596aec256cb7.png)

As installed in a VirtualBox: 
![omv1419fx-tb-installed](https://user-images.githubusercontent.com/73129450/196241748-02bb8b1d-974d-4f11-b42d-5e62dcdb4117.png)

**Comment by benbullard79** [comment]
Not sure what to say other than the OP told us he would not use OMLx anymore.
