### ISSUE TITLE
Thunderbird from ABF Xfce builds launches, but is unable to display Thunderbird Privacy Policy, tab instead displays Personal Security Manager is not installed

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2854]
**OpenMandriva version**: Cooker

**Describe the bug**: Installed Thunderbird from Cooker repository for ABF Xfce Cooker Builds 1356, 1418 and 1419 (all installed in VirtualBoxes), it launches, but the tab that should display the Thunderbird Privacy Policy, instead displays that the Personal Security Manager is not installed.

**Steps to reproduce**: As above.

**Observed behavior**: As above (see screenshot).

**Expected behavior**: Should have launched without any issues. 

**Additional comment**: Reported at: https://forum.openmandriva.org/t/abf-cooker-xfce-image-build-1356/4615

Installed latest Thunderbird binary from Mozilla, it launched and successfully displayed the tab showing the Thunderbird Privacy Policy.

**Please be advised that due to issues with the host Linux OS repeatedly freezing while I am using a VirtualBox, the host OS will be removed, removing the VirtualBoxes in the process and replacing this with another host OS, in which I plan on not using VirtualBox further. I am willing to keep the system as is, pending resolution of this bug report.** 

**Logs and screenshots if relevant**

![image](https://user-images.githubusercontent.com/73129450/194955823-f54c19b8-4078-496d-a351-044a94866e70.png)

[thunderbird-cooker-from-terminal.log](https://github.com/OpenMandrivaAssociation/distribution/files/9749431/thunderbird-cooker-from-terminal.log)
[thunderbird-install.log](https://github.com/OpenMandrivaAssociation/distribution/files/9749432/thunderbird-install.log)

**Comment by edwardp3** [comment]
DIscovered when in the Thunderbird settings, selecting Privacy & Security, does not display those settings. General, Composition and Chat correctly display. Screenshot attached.

![thunderbird-p-s](https://user-images.githubusercontent.com/73129450/194972351-5a4474b2-abf0-4b70-8dca-aa7b5e027309.png)

**Comment by edwardp3** [comment]
With ABF Build 1419, Thunderbird launches and runs correctly, but only when installed and run in the Live environment. Once the build was installed to a VirtualBox, the original error as reported, occurs.

Live environment: 
![live1419fx-tb](https://user-images.githubusercontent.com/73129450/196241497-cd662e53-a71e-421b-876c-596aec256cb7.png)

As installed in a VirtualBox: 
![omv1419fx-tb-installed](https://user-images.githubusercontent.com/73129450/196241748-02bb8b1d-974d-4f11-b42d-5e62dcdb4117.png)

**Comment by benbullard79** [comment]
Not sure what to say other than the OP told us he would not use OMLx anymore.
