### ISSUE TITLE
Plasma desktop icons in rolling-testing do not retain their positions on the desktop between and during sessions

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2855]
**OpenMandriva version**: Rolling-Testing

**Describe the bug**: Plasma desktop icons do not retain their positions on the desktop between and during sessions.

**Steps to reproduce**: Install Plasma and add `rolling-testing` repositories (this is installed in a VirtualBox).

**Observed behavior**: Icons were moved to the left side of the screen during a previous session. Sometime during that session, one icon stayed on the left side while the others moved to the right side and displayed diagonally (first screenshot). Other times, the icons will appear along the top row of the window (second screenshot).

**Expected behavior**: Once icons are moved to the left side of the window, or wherever the user prefers, the icons should remain where they were saved, between Plasma sessions.

**Additional comment**: This has so far not occurred with `cooker` or (ROME) `rolling` in VirtualBoxes, or `rolling` separately installed to hardware. Regular `rolling` installs were from ABF Build # 1286 (slim). Used ABF Build # 1403 (full iso) to install `roling-testing`.

**Logs and screenshots if relevant**
![rolling-testing-desktop-icons](https://user-images.githubusercontent.com/73129450/195698384-94fa1fc2-b313-4cee-af31-41e830e38b86.png)

![rolling-testing-desktop](https://user-images.githubusercontent.com/73129450/195698436-4feae543-cd82-41db-84d5-2ad4eb5cf10a.png)

**Comment by benbullard79** [comment]
Not sure what to say other than the OP told us he would not use OMLx anymore.
