### ISSUE TITLE
Plasma Cooker display resolution setting not persistent between sessions

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2856]
**OpenMandriva version**: Cooker

**Describe the bug**: Monitor display resolution on Plasma Cooker is not persistent between sessions.

**Steps to reproduce**: Plasma Cooker is installed in a VirtualBox using VBoxSVGA for graphics, `x11-driver-video-vboxvideo` is also installed. Display resolution after login comes up as 1440x900, which is slightly smaller than the window. Must be expanded to 1600x900 in order to get as close to a full-screen resolution as possible. The host OS display resolution is 1680x1050 on a 22" Samsung monitor.

**Observed behavior**: Display resolution does not come up as it was saved during previous sessions.

**Expected behavior**: Display resolution, once saved, should come up in the same resolution at each sessiom.

**Additional comment**: Installed ABF Build # 1286 (Plasma Slim ISO). The first screenshot below shows 1440x900.

**Logs and screenshots if relevant**
![plasmacooker1440x900](https://user-images.githubusercontent.com/73129450/196039061-5c640f05-f238-490c-a31f-3c4c789ea813.png)

![plasmacooker1600x900](https://user-images.githubusercontent.com/73129450/196039080-8ef3854d-159a-44a3-898c-2b56d04928ca.png)

**Comment by rugyada** [comment]
![ss_20221016_191148](https://user-images.githubusercontent.com/46781309/196049055-693568a2-b8f6-444e-81ab-fce365ed17cc.jpg)

Done this?

**Comment by edwardp3** [comment]
Host is (currently) Mageia 8. Most of the time, that menu does not work, it's either grayed out, or if accessible, selecting any of the listed resolutions does nothing.

**Comment by rugyada** [comment]
PS>
Other than that, for the record I can't confirm your bug report. Neither in this ROME host nor in Cooker host.

```
$ cat /etc/lsb-release 
LSB_VERSION=
DISTRIB_ID="OpenMandriva Lx"
DISTRIB_RELEASE=4.50
DISTRIB_CODENAME=ROME
DISTRIB_DESCRIPTION="OpenMandriva Lx 4.50"
```

```
$ rpm -q virtualbox
virtualbox-6.1.38-1.x86_64
```

**Comment by edwardp3** [comment]
> > Host is (currently) [...]
> 
> So we can't know what to blame.
> 
> Please install OM virtualbox to ROME or Cooker, and report back.

Can't, without removing the host OS. The other desktop with OM installed on-hardware, only has 4 GB RAM (maxed out), would not be able to use VirtualBox on it.

**Comment by benbullard79** [comment]
Not sure what to say other than the OP told us he would not use OMLx anymore.
