### ISSUE TITLE
LibreOffice draw cannot open PDF documents

### ISSUE THREAD

**Issue by dreamstorpi** [OpenMandrivaAssociation/distribution#2859]
**OpenMandriva version**: Cooker

**Describe the bug**: LO Draw fails to open PDF documents as it used to. 

**Steps to reproduce**: Try to open a PDF doc in LO Draw

**Observed behavior**: LO crashes with this error message,

_"Component cannot be loaded, possibly broken or incomplete installation.
Full error message:

 loading component library <file:///usr/lib64/libreoffice/program/../program/libsdlo.so> failed at /builddir/build/BUILD/libreoffice-7.4.2.3/cppuhelper/source/shlib.cxx:312."_

libsdlo.so exists here, /usr/lib64/libreoffice/program/libsdlo.so
I can find no other versions on the system, I'm slightly confused about the path shown in the error message.

**Expected behavior**: PDF Document opens in LO

**Additional comment**: 1) this may also apply to other files. 2) I have searched this on the web and it seems it is a general problem. See here, https://forums.freebsd.org/threads/libreoffice-7-4-1-2.86545/ There they suggest a forced upgrade. In Cooker I have tried reinstalling Libreoffice, removing and installing in dnfdrake. No luck, I get the same issue.

**Logs and screenshots if relevant**

**Comment by berolinux** [comment]
I can reproduce this, but I don't see anything wrong with the file path (libsdlo.so exists in the requested location) and the file shows no obvious errors (doesn't link to any libraries that don't exist etc.)
Probably something wrong with the component loader in LO...

**Comment by berolinux** [comment]
Should be fixed in today's build (7.4.2.3-2)

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/problemi-con-libreoffice-draw/4690/2

**Comment by dreamstorpi** [comment]
I confirm the bug is fixed after DNF upgrade today. Thank you.
