### ISSUE TITLE
kbreakout crashes on start-up

### ISSUE THREAD

**Issue by christann404** [OpenMandrivaAssociation/distribution#2860]
The game kbreakout crashes on start-up:
kbreakout
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
file:///usr/share/kbreakout/qml/main.qml:8:1: module "org.kde.games.core" is not installed 
     import org.kde.games.core 0.1 as KgCore 
     ^
QObject::connect: Cannot connect (nullptr)::levelComplete() to CanvasWidget::levelComplete()
QObject::connect: Cannot connect (nullptr)::gameEnded(int,int,int) to CanvasWidget::gameEnded(int,int,int)
QObject::connect: Cannot connect (nullptr)::mousePressed() to CanvasWidget::mousePressed()
QObject::connect: Cannot connect (nullptr)::ballMovingChanged() to CanvasWidget::updateCursor()
23 -- exe=/usr/bin/kbreakout
13 -- platform=xcb
11 -- display=:0
18 -- appname=kbreakout
17 -- apppath=/usr/bin
10 -- signal=11
10 -- pid=24026
19 -- appversion=22.08.3
22 -- programname=KBreakOut
31 -- bugaddress=submit@bugs.kde.org
12 -- startupid=0
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = kbreakout path = /usr/bin pid = 24026
KCrash: Arguments: /usr/bin/kbreakout 
KCrash: Attempting to start /usr/lib64/libexec/drkonqi
org.kde.drkonqi: Unable to find an internal debugger that can work with the crash backend

I reported this upstream and they said: 
--- Comment #3 from Albert Astals Cid [<aacid@kde.org>](mailto:aacid@kde.org) ---
Seeing

file:///usr/share/kbreakout/qml/main.qml:8:1: module "org.kde.games.core" is
not installed 

means you have to complain to your distribution, their package dependencies are
broken.

I am running an up-to-date cooker system.

**Comment by AngryPenguinPL** [comment]
Thanks for bug report.

Package fixed. Update you system. 
Fix is applied to kbreakout-22.08.3-2

**Comment by christann404** [comment]
Thanks for the fix. It works now.
Chris
