### ISSUE TITLE
openmandriva installation fails in (a bit slow) VM

### ISSUE THREAD

**Issue by usama-makhzoum** [OpenMandrivaAssociation/distribution#2861]
**OpenMandriva version**:
4.3 x86_64 , BUILD ID : 598 (I think it's ROCK but not sure)

**Describe the bug**:
setup failed at running scripts stage (/usr/bin/calmares-post-script specifically). installation waits for it 100 seconds only, this can be too short for VMs

**Steps to reproduce**:
run openmandriva installation in a weak or mid specs virtual machine (VBox for instance)

**Observed behavior**:
installation failed. no more scripts are executed and installation is broken.

**Expected behavior**:
installation should wait for it , a little more.

**Additional comment**:
I am running `/usr/bin/calmares-post-script ` inside another chroot as a trick in order to make installation complete, just before `calmares` executes the script itself.

having 3 GB as VM ram, 10 GB for harddisk space, Oracle Virtualbox in debian linux.

**Comment by tpgxyz** [comment]
Hi @usama-makhzoum thanks for the report. You can incerase timeout by yourself by editing `/etc/calamares/modules/shellprocess.conf`

Nevertheless i'll increase the timeout.

https://github.com/OpenMandrivaSoftware/distro-release/blob/6049f87ac41865e288eda37767aea5527c46214a/installer/shellprocess.conf#L34

**Comment by usama-makhzoum** [comment]
nice, I've edited conf inside harddisk just after calamares copied image files.

 worked as charm
