### ISSUE TITLE
with automatic disk partitioning, make it possible in which file system to do the markup.

### ISSUE THREAD

**Issue by saber716rus** [OpenMandrivaAssociation/distribution#2864]
I raised the issue in the upstream, they said that everything is in the config.

https://github.com/calamares/calamares/issues/2080

**Comment by tpgxyz** [comment]
With new distro-release-23.90 and fixed grub2 it is now available to choose filesystems on install.

**Comment by saber716rus** [comment]
and in the rock version, when will this feature be presented?

**Comment by benbullard79** [comment]
I don't know any reason why we would not do this.

**Comment by benbullard79** [comment]
Reopened just to pass this info along to user.

> and in the rock version, when will this feature be presented?

Not until there is new Rock version. Currently this is in Cooker (development branch). and should get to other branches in near future.

This is Cooker iso #1621. Cooker isos should have this feature again for any iso =>1621. 

![Screenshot_20230112_170533](https://user-images.githubusercontent.com/5704386/212200549-fef1f196-2699-42c3-99c1-6f7ef208deb1.jpg)

Should be in ROME soon and Rock with 5.0 release.
