### ISSUE TITLE
Flathub support

### ISSUE THREAD

**Issue by rugyada** [OpenMandrivaAssociation/distribution#2868]
We should probably have a package that includes the flatearth repo.

**Comment by rugyada** [comment]
> huh ? are you sure about flatearth ?

Flathub :)

**Comment by AngryPenguinPL** [comment]
Thanks @tpgxyz 
Now question is: do we want put flatpak package on Plasma ISO?
I would vote yes. Anyway, gnome iso has included a flatpak package for some time now.

**Comment by rugyada** [comment]
> hehe it should be there with new flatpak-1.15.1-2

@tpgxyz thank you

**Comment by tpgxyz** [comment]
@AngryPenguinPL feel free to add flatpack support on iso. I guess we are not loosing anything if it will be in our default installation.
