### ISSUE TITLE
Rootactions in OpenMandriva Rome changes permissions in other installed OS's

### ISSUE THREAD

**Issue by Locutus64** [OpenMandrivaAssociation/distribution#2872]
**openmandriva.rome-23.01-plasma.znver1**:

I used Dnfdragora to install Rootactions for Dolphin. Before creating folders in /mnt/ for my secondary partitions and drives I rightclicked in /mnt/ and used Rootactions to give ownership to the active user. I then proceeded to create my folders for mounting my secondary partitions and partitions to. I then proceeded to mount the various partitions and drives to their corresponding folders in /mnt/. I tested by copying files to the desktop from my Docs partition to make sure I had proper permissions. There was no issue copying to the desktop. Shortly thereafter I rebooted and went into Arch. I had new files that I needed to file away and was promptly told I didn't have permission, so I rightclicked in /mnt/ in Arch and create was greyed out. I took ownership again in Arch using Rootactions and all was good. After moving the files I needed to I rebooted and booted into Garuda when I ran into the same issue. I fixed the issue and rebooted into OM Rome and sure enough I no long had my permissions under /mnt/. I fixed it, booted back into Garuda and as I suspected I had to fix the permissions again. 

I know the issue is something with OM Rome cause with just Garuda, Arch, Manjaro this never happens. My permissions set using Rootactions stay as I have them. Garuda had this particular a good while back and has since corrected it.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/rootactions-in-openmandriva-rome-changes-permissions-in-other-installed-oss/4775/1

**Comment by Locutus64** [comment]
https://forum.openmandriva.org/t/rootactions-in-openmandriva-rome-changes-permissions-in-other-installed-oss/4775

**Comment by Locutus64** [comment]
There are relevant details there.

**Comment by Locutus64** [comment]
I found the below til your fix is pushed in a new ISO cause the current ISO will still install with 1001. Please let me know if this will for me without issue. Thanks

https://www.cyberciti.biz/faq/linux-change-user-group-uid-gid-for-all-owned-files/

**Comment by benbullard79** [comment]
I don't know of any fix submitted. I passed along your comments to developers at [OpenMandriva Cooker matrix channel](https://wiki.openmandriva.org/en/team/chat). Developers would decide on a fix. Of course developers should see this bug report also, sometimes they respond right away and sometimes it takes a bit of time.

**Comment by rugyada** [comment]
Nothing to do with the rootactions servicemenu.
