### ISSUE TITLE
Page Not Found | OpenMandriva wiki

### ISSUE THREAD

**Issue by Neustradamus** [OpenMandrivaAssociation/distribution#2873]
Dear @OpenMandrivaAssociation team,

In first, I wish you a Happy New Year!

On https://www.openmandriva.org/en/news/article/openmandriva-rome-the-rolling-release, there is a dead link:
- https://wiki.openmandriva.org/en/doc/release-plan-and-repositories

**Comment by rugyada** [comment]
> In first, I wish you a Happy New Year!

Happy New Year @Neustradamus 

Thank you very much for reporting.
Fixed.

**Comment by Neustradamus** [comment]
@rugyada: Thanks!

Attention: It is in another articles too...

**Comment by rugyada** [comment]
Hope I fixed all the dead links now :) 
Thanks.
