### ISSUE TITLE
Falkon > Unfortunately, your browser is unsupported.

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2877]
**OpenMandriva version**:
Cooker and ROME

**Describe the bug**:
Falkon >>> Unfortunately, [your browser is unsupported](https://www.discourse.org/faq/#browser).
This is for OpenMandriva Forum.

**Steps to reproduce**:
Install Cooker or ROME, open Falkon and navigate to OpenMandriva Forum.

**Observed behavior**:
![Screenshot_20230129_181910](https://user-images.githubusercontent.com/5704386/215364633-13de430c-e288-44b1-9f85-8522f39f23bf.jpg)

**Expected behavior**:
That OpenMandriva Forum is supported in our default browser.

**Additional comment**:
The assignees are my best guess at who might be interested in fixing this.
Other people have noticed this so marking as "bug" ie. confirmed.
_Edit:_ Please note there is no way to login and use OpenMandriva Forum in Falkon presently.
_Edit_: Changed to add ROME to this report.
**Logs and screenshots if relevant**

**Comment by benbullard79** [comment]
This page shows what Discourse seems to believe are supported browsers. 

![Screenshot_20230129_181910](https://user-images.githubusercontent.com/5704386/215364959-e4b88244-4b32-4532-a853-6cd3f08ae253.jpg)

**Comment by berolinux** [comment]
Yes, upstream bug -- not much we can do about it in the distro, but we can patch the offending check out of Discourse at least on our installation...

**Comment by benbullard79** [comment]
> Yes, upstream bug -- not much we can do about it in the distro, but we can patch the offending check out of Discourse at least on our installation...

If we can we probably should do that.

**Comment by benbullard79** [comment]
This is fixed, has been for a while. Apologies for not closing sooner.

![Screenshot_20240426_205826](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/2b3a1e00-fb27-423f-9de6-92b3b75ab136)

**Comment by ashledombos** [comment]
As well as for Angelfish browser
