### ISSUE TITLE
Xsane no preview nor scan

### ISSUE THREAD

**Issue by Giorgio-IT** [OpenMandrivaAssociation/distribution#2878]
**OpenMandriva version**: 4.3

**Describe the bug**: Xsane start but preview and scan give same error message

**Steps to reproduce**: install Xsane, start it, start preview or scan

**Observed behavior**: press "Acquire preview" button -> scanner lamp is on and move -> when preview scan is complete Xsane give error message: `Failed to start scanner: Invalid argument`

**Expected behavior**: show preview

**Additional comment**: starting Xsane from console give several warning and one error:
```
$ xsane

(xsane:5917): Gtk-WARNING **: 08:31:08.192: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.192: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.192: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.192: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.192: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.193: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.193: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.193: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.193: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.193: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.193: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.193: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.193: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.193: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.193: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.194: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.194: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.194: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.194: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.194: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.194: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.194: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.194: Unable to locate theme engine in module_path: "pixmap",

(xsane:5917): Gtk-WARNING **: 08:31:08.194: Unable to locate theme engine in module_path: "adwaita",

my note: next row is added after choosing scanner

[xsane] ERROR: xsane-startimage not found. Looks like xsane is not installed correct.
```

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/om-rolling-problema-xsane/4812/9

**Comment by tpgxyz** [comment]
Will fix this soon

**Comment by Giorgio-IT** [comment]
Just updated Xsane to version 0.999-20. 
No change, still impossible preview and scan.

**Comment by Giorgio-IT** [comment]
And same error messages and warning opening Xsane in console.

**Comment by benbullard79** [comment]
In [this forum thread](https://forum.openmandriva.org/t/om-rolling-problema-xsane/4812) all the devices that do not scan are Epson. I wonder if the [Epson Scan 2](http://support.epson.net/linux/en/epsonscan2.php) software is missing from OMLx scanning software or something?

**Comment by benbullard79** [comment]
"Failed to start scanner: Invalid argument" I get this error if I use a non-working connection. I will guess that Giorgio has already tried all connection possibilities but if you haven't that is something to try.

**Comment by Giorgio-IT** [comment]
> In [this forum thread](https://forum.openmandriva.org/t/om-rolling-problema-xsane/4812) all the devices that do not scan are Epson.

I just used Xsane with Canon Pixma TR4550 multifunctional printer connected using usb cable. I can get preview and scanning without any problem. 
Then probably problem arise when Xsane have to interact with Epson printer.

**Comment by benbullard79** [comment]
> > In [this forum thread](https://forum.openmandriva.org/t/om-rolling-problema-xsane/4812) all the devices that do not scan are Epson.
> 
> I just used Xsane with Canon Pixma TR4550 multifunctional printer connected using usb cable. I can get preview and scanning without any problem. Then probably problem arise when Xsane have to interact with Epson printer.

I have similar problem with my HP Photosmart 6520 device connected via USB. What worked for me was to remove 2 packages `ipp-usb` and `usbmuxd`. `usbmuxd` is in the system only in order for system to connect to Apple devices so I do not need that. I *think* `ipp-usb` is for the ipp protocols for driverless printing and scanning. I am not sure about that though. Anyway removing those had no negative affect for me.

There are posts on the forum about printing and scanning driverless. This would likely require the user to experiment a bit and figure out what works with their hardware. The scanning should work if your device is supported driverless. There are links in the forum articles to [OpenPrinting](https://openprinting.github.io/) with more info about driverless.
