### ISSUE TITLE
LibreCAD 2.2.0

### ISSUE THREAD

**Issue by Giorgio-IT** [OpenMandrivaAssociation/distribution#2879]
Please update to new stable 2.2.0 version of LibreCAD.
Current version 2.2.0 alpha is incomplete and hang.

**Comment by benbullard79** [comment]
So far LibreCAD-2.2.0 builds in cooker have failed. We are working on it. Then build for rolling repos (ROME). And then try to build for 4.3.

Normal workflow is cooker>rolling>release (currently release is 4.3).

**Comment by benbullard79** [comment]
`librecad-2.2.0-1` built for cooker. Packages also built for rolling and 4.3. For rolling and 4.3 they are currently in unsupported/testing repo.
