### ISSUE TITLE
ebook-viewer crashes on startup

### ISSUE THREAD

**Issue by christann404** [OpenMandrivaAssociation/distribution#2880]
I am running cooker. ebook-viewer crashes on startup. 

[Ebook-Viewer-problem.txt](https://github.com/OpenMandrivaAssociation/distribution/files/10788225/Ebook-Viewer-problem.txt)
[omdv-bug-report-20230220175057.log](https://github.com/OpenMandrivaAssociation/distribution/files/10788226/omdv-bug-report-20230220175057.log)

**Comment by benbullard79** [comment]
What package provides ebook-viewer? I don't see it in repos or ABF.

**Comment by AngryPenguinPL** [comment]
> What package provides ebook-viewer? I don't see it in repos or ABF.

Calibre.

Anyway I can confirm this issue.

But worth to add. App open just fine but spamming error about  missing file **/usr/share/calibre/user-agent-data.json** - so just like ih @christann404 report.
This prevent from searching books or display.

Can you look at it @mandian ?

**Comment by christann404** [comment]
Problem appears to be fixed with Calibre vs. 6.13.0-2. Thanks a lot.
