### ISSUE TITLE
Firefox version 110 not working

### ISSUE THREAD

**Issue by mtomatis** [OpenMandrivaAssociation/distribution#2881]
**OpenMandriva version**: Rome 23.01

**Describe the bug**: After a regular update from shell, Firefox version 110 won't connect and work properly. I had to uninstall it and revert to the version 108.

**Steps to reproduce**:

**Observed behavior**: Firefox version 110 behaves like it was offline. It won't respond to any URL.

**Expected behavior**:

**Additional comment**:

**Logs and screenshots if relevant**

**Comment by tpgxyz** [comment]
@mtomatis what happens if you run Firefox in konsole? Please share the output.

**Comment by mtomatis** [comment]
Here are the errors from running Firefox 110 in konsole:

> Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection. (t=0.202839) [GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection.
> ATTENTION: default value of option mesa_glthread overridden by environment.
> ATTENTION: default value of option mesa_glthread overridden by environment.
> ATTENTION: default value of option mesa_glthread overridden by environment.
> console.error: ({})
> console.warn: TopSitesFeed: Failed to fetch data from Contile server: NetworkError when attempting to fetch resource.
> console.error: Region.sys.mjs: "Error fetching region" (new TypeError("NetworkError when attempting to fetch resource.", ""))
> console.error: Region.sys.mjs: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.sys.mjs", 416))
> console.error: (new TypeError("NetworkError: Network request failed", "resource://services-settings/Utils.jsm", 237))
> [2023-02-25T23:39:09Z ERROR glean_core::metrics::ping] Invalid reason code startup for ping newtab
> console.error: (new TypeError("NetworkError: Network request failed", "resource://services-settings/Utils.jsm", 237))
> console.error: (new TypeError("NetworkError: Network request failed", "resource://services-settings/Utils.jsm", 237))
> console.error: (new TypeError("NetworkError: Network request failed", "resource://services-settings/Utils.jsm", 237))
> console.error: (new TypeError("NetworkError: Network request failed", "resource://services-settings/Utils.jsm", 237))
> console.error: (new TypeError("NetworkError: Network request failed", "resource://services-settings/Utils.jsm", 237))
> JavaScript error: resource://gre/modules/XULStore.jsm, line 58: Error: Can't find profile directory.
> 

After stopping Firefox with ctrl-c:

> Exiting due to channel error.
> Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=85.53) Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=85.5446) Exiting due to channel error.
> Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=85.5388) Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=86.2988) Exiting due to channel error.
> Exiting due to channel error.
> Exiting due to channel error.

**Comment by benbullard79** [comment]
Most of you have noticed that when you upgrade Firefox you may also see upgrades for `nss` and `nss-shlibsign`. For FF 110 you need:

```
lib64nss3-3.88.1-1
nss-shlibsign-3.88.1-1
nss-3.88.1-1
```
It looks like there was some glitch in publishing for these. They are shown as published in ABF but I do not seem them in rolling/main/release repo. So I am republishing these.

In the main time try:

For x86_64:

`$ sudo dnf --refresh firefox nss --enablerepo rolling-testing-x86_64`

znver1:

`$ sudo dnf --refresh firefox nss --enablerepo rolling-testing-znver1`

I do not know if absolutely every FF upgrade comes with also nss upgrade but it sure seems like it to me.

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/aggiornamento-firefox-difettoso/4830/8

**Comment by mtomatis** [comment]
I confirm the issue was due to nss.
Doing what Ben suggested (sudo dnf up --refresh firefox nss nss-shlibsign) could fix the Firefox 110 issue.
