### ISSUE TITLE
GtkHash

### ISSUE THREAD

**Issue by Giorgio-IT** [OpenMandrivaAssociation/distribution#2882]
Official package name: GtkHash
 
License (must be an OSI approved Open Source license): 

Download URL of latest release: https://gtkhash.org/ or https://github.com/tristanheaven/gtkhash

Latest release date (must be recent):

Description: check and compare easily checksums, very useful

**Comment by AngryPenguinPL** [comment]
Package updated to ver. 1.5. It is available in Cooker/unsupported repo with main package and with optional plugins packages for nemo, caja, thunar.

**Comment by benbullard79** [comment]
Building for rolling repos (ROME). And then try to build for 4.3. If this does not build for 4.3 then users will need to upgrade to ROME or wait for 5.0. We hope to release 5.0 soon. Soon as in a few weeks to 2 months. (Approximately)
