### ISSUE TITLE
Package request: NetworkManager-l2tp

### ISSUE THREAD

**Issue by lwanros** [OpenMandrivaAssociation/distribution#2885]
Official package name: networkmanager-l2tp

License (must be an OSI approved Open Source license): GPL-2.0 license

Download URL of latest release: https://github.com/nm-l2tp/NetworkManager-l2tp

Latest release date (must be recent): 1.20.8-2

Description: NetworkManager-l2tp is a VPN plugin for NetworkManager 1.20 and later which provides support for L2TP and L2TP/IPsec (i.e. L2TP over IPsec) connections.

**Comment by mandian** [comment]
Hi @lwanros
networkmanager-l2tp 1.20.8 is in queue for build on ABF (which is actually a bit busy) so you will receive it i a few time in unsupported repository.

**Comment by lwanros** [comment]
Thank you. Now, I can run my l2tp VPN on openmandriva rome.
