### ISSUE TITLE
Bleachbit fails to install on ROME (X86_64)

### ISSUE THREAD

**Issue by hakerdefo** [OpenMandrivaAssociation/distribution#2886]
Installation of Bleachbit (4.4.2-1) fails with the following error in ROME (X86_64),

`
Error: Transaction test error:
file /usr/sbin/bleachbit-root conflicts between attempted installs of bleachbit-4.4.2-1.noarch and bleachbit-4.4.2-1.noarch
`

**Comment by hakerdefo** [comment]
Running `rpm -qlp bleachbit-4.4.2-1-omv4050.noarch.rpm` shows these two separate entries,

`
/usr/bin/bleachbit-root
`
` 
/usr/sbin/bleachbit-root
`

Now, the `/usr/sbin` is just a symlink to `/usr/bin`. This means that they are the same location, and an RPM cannot install two different files to the same location. So, removing either one of them from the rpm will (hopefully) fix this issue.

**Comment by benbullard79** [comment]
Confirmed bug in Cooker and Rome. `bleachbit` has not been touched in GH for a year and half so it at least will need rebuild for catching up to latest dependency versions, may need more help. We shall see.

**Comment by benbullard79** [comment]
OK, I did have to get bero (OM project leader) to fix some things. Mostly removing code from .spec file regarding no longer used usermode. This, %{_bindir} and %{_sbindir} (which are the same nowadays).

So I can verify that package built for Cooker and ROME and that it installs. As to how well it works that is up to you and other users.

![Screenshot_20230402_201141](https://user-images.githubusercontent.com/5704386/229390861-eec4638f-bc6f-4662-aa5e-f5cd55e89322.jpg)

![Screenshot_20230402_201223](https://user-images.githubusercontent.com/5704386/229390872-7fd373ff-1c14-4b85-b991-917436432723.jpg)

**Comment by hakerdefo** [comment]
Ben the man :+1:
