### ISSUE TITLE
VirtualBox on Kernel 6.2.8> hangs

### ISSUE THREAD

**Issue by christann404** [OpenMandrivaAssociation/distribution#2889]
I am running an up-to-date cooker and Kernel 6.2.8.  When I run Virtual Box and then try to start up a system under vbox, it just hangs. The system slows down a lot with tons of messages in the system log (journalctl -xe)

[omdv-bug-report-20230403105648.log](https://github.com/OpenMandrivaAssociation/distribution/files/11139662/omdv-bug-report-20230403105648.log)
[aa.txt](https://github.com/OpenMandrivaAssociation/distribution/files/11139667/aa.txt)

**Comment by rugyada** [comment]
And with kernel 6.3.x so far affected as well.

**Comment by benbullard79** [comment]
Added ROME now that ROME has kernel 6.3.5.

**Comment by rugyada** [comment]
This is fixed now.
