### ISSUE TITLE
 Unison file synchronizer 

### ISSUE THREAD

**Issue by hakerdefo** [OpenMandrivaAssociation/distribution#2891]
Official package name: unison

License : GNU General Public License v3.0

Download URL of latest release: https://github.com/bcpierce00/unison/releases/download/v2.53.2/unison-v2.53.2+ocaml-4.08.1+x86_64.linux.tar.gz

Latest release date: Mar 20, 2023

Description: Unison is a file-synchronization tool for POSIX-compliant systems (e.g. *BSD and GNU/Linux), macOS and Windows, with the caveat that the platform must be supported by OCaml. It allows two replicas of a collection of files and directories to be stored on different hosts (or different disks on the same host), modified separately, and then brought up to date by propagating the changes in each replica to the other.
Unison has been in use for over 20 years and many people use it to synchronize data they care about.

**Comment by mandian** [comment]
unison 2.53.3 is in repo now.
