### ISSUE TITLE
cannot run emacs-nox on terminal

### ISSUE THREAD

**Issue by SACViper** [OpenMandrivaAssociation/distribution#2899]
**OpenMandriva ROME**:

**when running emacs from terminal get an error :
desired fingerprint: 33bef65f4e420d6e9691edb40f20e94cf686103c9a48a7be0920087b0cbc59b4
found fingerprint: 7e0c4671b9effa86f75ea935e139ade4ab4719d7a2ae64a47a57cc3c3743ff23
emacs: could not load dump file "/usr/libexec/emacs/27.1/x86_64-openmandriva-linux-gnu/emacs.pdmp": not built for this Emacs executable**:

**installed emacs and tried to run emacs from terminal**:

**Observed behavior**:

**Expected behavior**:

**Additional comment**:

**Logs and screenshots if relevant**

**Comment by benbullard79** [comment]
I have no clue about this one.  I notice that most recent build in ABF 2023-04-02 failed. I started x86_64 builds for cooker and rolling to see what happens. We will go from there. Please feel free to talk to OM devs at [OpenMandriva Chat](https://wiki.openmandriva.org/en/team/chat).

**Comment by benbullard79** [comment]
Looks fixed:

![Screenshot_20230926_175225](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/8df3f9db-3a67-47ba-b0cc-e10ff3f8d55e)

Thanks to whoever fixed this.
