### ISSUE TITLE
Installed LXQt Cooker Build 1899 to an external SSD - would not boot after installation when using ext4

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2903]
**OpenMandriva version**:
Cooker, Build # 1899, LXQt

**Describe the bug**:
Installed .ISO (from a USB flash drive) to an external SSD, the installation did not indicate any errors, however, on the first boot, it displayed a grub rescue prompt with an indication that a file normal.mod could not be found (photo of display is attached). The SSD is a Samsung T7, 500GB.

**Steps to reproduce**:
As above.

**Observed behavior**:
As above.

**Expected behavior**:
OpenMandriva should have successfully booted to the login manager.

**Additional comment**:
The image on the USB flash drive successfully boots to a live desktop. Reported on OM Forum at https://forum.openmandriva.org/t/build-1899-not-booting-after-installation-to-external-ssd-grub-rescue-prompt/4907

I subsequently tried installing a different Linux distribution to the SSD, with success, that boots up perfectly.

**Logs and screenshots if relevant**
![openmandrivabooterror](https://user-images.githubusercontent.com/73129450/235257353-dbbca73f-2372-4327-83e0-eeaaf2b84af8.jpeg)

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/build-1899-not-booting-after-installation-to-external-ssd-grub-rescue-prompt/4907/2

**Comment by benbullard79** [comment]
I better label this reply as opinion. I don't believe anyone involved with OM knows specifically how to do this. 

For Problem Solving this: If someone or some other distro does know how to do this we need for you to find that out and tells us how they do it. Also try googling something like: "How to get a Linux operating system to boot from external ssd?" The results I get suggest this is not a problem at all unique to OpenMandriva.

I would like to see this issue resolved.

**Comment by edwardp3** [comment]
It looks like the LXQt panel not appearing, or appearing for a fractional second, then disappearing, may be related to the `lxqt-powermanagement` package. That displayed a notification that it couldn't find a battery (as this is not a laptop) and as soon as that notification appeared, that's when the panel disappeared. I removed only that package using `rpm -e --nodeps lxqt-powermanagement` (otherwise it wanted to remove all of LXQt) and rebooted. So far, the panel has successfully appeared at each login and reboot. I will continue to test.

**Comment by edwardp3** [comment]
When I reinstalled it using the btrfs file system, it installed perfectly to the external SSD. When installing with ext4, is when it has a problem finding grub.

**Comment by benbullard79** [comment]
I think we can close this as I believe user left OM in not happy state. If I am wrong please reopen this bug report.
