### ISSUE TITLE
Can't login from sddm with new user passwd (Installed system)

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2904]
**OpenMandriva version**:
Cooker
**Describe the bug**:
Change existing user passwd. Logout to sddm login. Login from sddm login. Can not login.
**Steps to reproduce**:
For some user account with existing passwd you know is working. Change that user passwd. Logout. Try to login from sddm login.
**Observed behavior**:
Login from sddm login. Can not login.
**Expected behavior**:
User should be able to change passed and login from sddm login.
I consider this as about as high a priority as can be but am not selecting one for this report yet.

**Additional comment**:
sudo works, can login from VT. The password works and has been in use for days.
**Logs and screenshots if relevant**
On the way.

**Comment by benbullard79** [comment]
I have reproduced this problem on 2 computers. Root journal log from the notebook I will have on my trip attached.

[journal-sddm-nologin.txt](https://github.com/OpenMandrivaAssociation/distribution/files/11358238/journal-sddm-nologin.txt)

I don't have much time to study that log, have to get ready to leave. To me it does not look like it even tries to boot user 1000. That is the user that won't login from sddm on this box.

[omdv-bug-report-20230428222018.log](https://github.com/OpenMandrivaAssociation/distribution/files/11358244/omdv-bug-report-20230428222018.log)

**Comment by benbullard79** [comment]
In fully updated Cooker znver1 on my desktop this issue persists. I do not have this issue on older ASUS notebooks that are x86_64. One might conclude this issue is either hardware or znver1 related. It is none the less disturbing. I can not do autologin unless I am physically present and testing whatever.

**Comment by benbullard79** [comment]
I was able to reproduce this issue with a fresh install of cooker, in another partition on the same machine.  I**t would be helpful if someone else using znver1 would test this.** The system was updated with `dnf dsync --exclude=*5.240.0*` before changing passwd. Yes I run `dnf clean all` before `dsync`.

**Comment by benbullard79** [comment]
On the desktop where I have this problem I did a fresh install of cooker x86_64 and znver1 and both have this issue. I suppose this now points to somehow being hardware related. I do not understand how this could be hardware related. But proper investigative procedure says "Follow the evidence".

**Comment by benbullard79** [comment]
Another consequence of this bug is that in those fresh installs if I add a new user, set passwd for that user then sddm login screen will not accept that passwd. _Disturbing_.

**Comment by benbullard79** [comment]
Found workaround for this issue:

`$ sudo dnf rm kwallet-pam`

The removed package is `kwallet-pam-5.27.5-1`. I do not know if this might have other consequences.

**Comment by benbullard79** [comment]
This README from [here](https://github.com/KDE/kwallet-pam) _might_ point to what may be going wrong. 

[kwallet-pam_README.txt](https://github.com/OpenMandrivaAssociation/distribution/files/11594149/kwallet-pam_README.txt)

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/possible-problems-with-rome-upgrade-2023-06-04/4943/1

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/possible-problem-upgrading-rome-2023-07-05/4950/1

**Comment by benbullard79** [comment]
Just discovered in Cooker system. User accounts created from SystemSettings or KUser login OK. Only user I create in terminal has this issue. I had been wondering why we have not heard form users on this. I  have been creating users like this since forever:

# useradd -c "Some User" -u 100x someu

No idea what is wrong with that now.

**Comment by benbullard79** [comment]
Maybe there has been some change in the commands for doing this from terminal or I have doing something wrong since Mandriva days.
