### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Reini4711** [OpenMandrivaAssociation/distribution#2905]
Es ist ein Paket-Konflikt aufgetreten:

Multiple matches of lib64vulkan1;1.3.243-1;x86_64;rolling-x86_64

**Comment by tpgxyz** [comment]
Hi @Reini4711 can you please provide output fron the dnf ? Like what is the real error.

**Comment by rugyada** [comment]
_Please note:_
For non-English computers to make output easier to read for folks trying to help use this `LC_ALL=C`

Example: `sudo LC_ALL=C journalctl` 

Using a translator on terminal output or code is not very workable.

**Comment by Reini4711** [comment]
<html>Es ist ein Paket-Konflikt aufgetreten:<br/><br/>Multiple matches of lib64vulkan1;1.3.243-1;x86_64;rolling-x86_64</html>
after I wrote dnf --auto-orphans i cannot even update packages manually or find packages in dnfdragora
