### ISSUE TITLE
Addition of 81-blueman-rules file to /etc/polkit-1/rules.d for users in the wheel group

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2911]
In Rolling, I installed Blueman. Subsequent to this, after logging in with LXQt, I was prompted for my password again, with a dialog box containing the Bluetooth logo and _Setting Rfkill State requires privileges_.

As my account is already in the wheel group, it sounds like such a prompt shouldn't be seen.

This required the placement of a file named `81-blueman-rules` in `/etc/polkit-1/rules.d` containing the following:

```
polkit.addRule(function(action, subject) {
  if (action.id == "org.blueman.rfkill.setstate" && subject.local && subject.active && subject.isInGroup("wheel")) {
      return polkit.Result.YES;
  }
  if (action.id == "org.blueman.network.setup" && subject.local && subject.active && subject.isInGroup("wheel")) {
      return polkit.Result.YES;
  }
});
```

Once this file was placed in this directory, after the next and subsequent LXQt logins, this prompt is no longer displayed. This apparently only affects LXQt logins. The prompt did not appear after Plasma and Xfce logins.

Info taken from: https://www.linuxquestions.org/questions/fedora-35/blueman-requires-authentication-twice-when-logging-into-account-4175626708/

**Comment by tpgxyz** [comment]
Will workaround it.
https://github.com/blueman-project/blueman/issues/2073

**Comment by tpgxyz** [comment]
please try with blueman-2.3.5-2

**Comment by edwardp3** [comment]
I've given up on using the smaller desktops, due to numerous issues with them. Presently unable to try with new blueman on LXQt. Using Plasma currently.
