### ISSUE TITLE
Software Repository Selector: add the ability to connect the yandex browser repository.

### ISSUE THREAD

**Issue by saber716rus** [OpenMandrivaAssociation/distribution#2917]
there is an idea to add the ability to connect the yandex browser repository.
[Yandex browser stable](https://repo.yandex.ru/yandex-browser/rpm/stable/x86_64/) 

[Yandex browser beta](https://repo.yandex.ru/yandex-browser/rpm/beta/x86_64/)

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/wouldnt-it-be-easyer-and-also-make-sense-general-suggestion/4651/9

**Comment by peter-power-594** [comment]
+1 Using the stable version here

**Comment by AngryPenguinPL** [comment]
I guess I can try to do something about it, but so far no promises yet.

**Comment by rugyada** [comment]
Work in progress

**Comment by benbullard79** [comment]
![Screenshot_20230926_174104](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/020965c1-c5ad-4045-926d-85557ca0fa5c)
