### ISSUE TITLE
Japanese input not working anymore after upgrading from 4.3x to ROME

### ISSUE THREAD

**Issue by peter-power-594** [OpenMandrivaAssociation/distribution#2918]
OpenMandriva Lx release 23.03 (ROME) Rolling for x86_64 with KDE X11 - I believe !

OpenMandriva Stars,

I've upgraded yesterday from 4.3x to 5. For now on congratulations, everything is smoothy :-D Open Mandriva 4ever !
Except the japanese input. _Fcitx_ is still working but the fcitx-anthy does not work anymore.
Couldn't get log, on terminal something I got Anthy: iconv can't convert from ECJ to internal something like that.
I can type in English or French, as soon as I switch the Japanese input, it kind of switching to the next input method.

If anyone can confirm or tell me if it's my desktop please

**Comment by rugyada** [comment]
@peter-power-594 I edit the title as OMLx 5.0 is not officially released yet so it may be misleading.

**Comment by AngryPenguinPL** [comment]
@peter-power-594 can you try install:
`locales-extra-charsets`
and check again

**Comment by peter-power-594** [comment]
@AngryPenguinPL @rugyada 

どうもありがとうございますぅぅぅぅぅ 😎

It's working mates ! ! ! YOU ARE AWESOME 🤗

**Comment by berolinux** [comment]
Added a hard dependency on locales-extra-charsets to fcitx-anthy so installing the package is sufficient now

**Comment by peter-power-594** [comment]
@rugyada @AngryPenguinPL @berolinux 

After multiple testing today, you need the _anthy binaries_ as well (Agent / dict Tool). Don't know exactly how the stuff works but if you don't install it, you won't go far... When starting from an non-asian environment, this _anthy_ package is not installed by default and japanese input does not work. Testing on ROME with 2 different machines. When you installed a full system in Japanese - I didn't do it - I **guess** _anthy_ is installed because of another package dependency like _kasumi_ and _locales-extra-charsets_ installed by _locales-ja_ or something similar. I didn't find the info with Fedora but the package in Debian flags anthy as a dependency as a reference.

**Comment by peter-power-594** [comment]
And with my "_rolling_ only" machine (fresh install and Unsupported, Restricted, Non-Free repo are disabled), I don't know if this is related but fcitx-gtk2 won't install as well (not a major issue for me right now just reporting) :

![Screenshot_20230611_210235](https://github.com/OpenMandrivaAssociation/distribution/assets/70574048/8c47f01e-5165-4a58-9af5-3136217eb701)

![Screenshot_20230611_210401](https://github.com/OpenMandrivaAssociation/distribution/assets/70574048/f86706ff-14a3-4a74-870c-469d73da7efc)

**Comment by rugyada** [comment]
Use the command line with option to exclude `*5.240*`

**Comment by peter-power-594** [comment]
@rugyada don't exactly how to do that, or if someone already updated between my try, 
this morning (24h earlier) running the following command works for me :

```
sudo dnf --setop=install_weak_deps=false install fcitx-gtk2
```
