### ISSUE TITLE
Nginx: Won't start with default config

### ISSUE THREAD

**Issue by peter-power-594** [OpenMandrivaAssociation/distribution#2923]
**OpenMandriva version**:  
OpenMandriva Lx 23.06 6.3.5-desktop-3omv2390

**Describe the bug**: 
the default nginx's server.conf will try to enable the SSL version as well which is not available by default (The include module file "ssl.conf" does not exit)

**Steps to reproduce**: 
```
sudo dnf install nginx
sudo systemctl start nginx
```

**Observed behavior**: 
Nginx won't start

**Expected behavior**:
Nginx to start

**Additional comment**:
Minor issue for me, just removing or commenting the SSL section in the /etc/nginx/sites-enabled/default.conf is enough.

Cheers

**Comment by davidebeatrici** [comment]
@berolinux https://github.com/OpenMandrivaAssociation/nginx-quic/commit/ca6899b086e8acae2091e2a6d13555d071322a70 should be moved into `nginx`.

**Comment by tpgxyz** [comment]
@peter-power-594 please provide the logs from nginx when you are starting the service

**Comment by peter-power-594** [comment]
@tpgxyz :1234:  Here it is :

```
juin 17 16:38:40 concorde nginx[8967]: nginx: [emerg] open() "/etc/nginx/ssl.conf" failed (2: No such file or directory) in /etc/nginx/sites-enabled/default.conf:20
juin 17 16:38:40 concorde nginx[8967]: nginx: configuration file /etc/nginx/nginx.conf test failed
juin 17 16:38:40 concorde systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
```

**Comment by davidebeatrici** [comment]
I confirm https://github.com/OpenMandrivaAssociation/nginx-quic/commit/ca6899b086e8acae2091e2a6d13555d071322a70 fixes that.

**Comment by peter-power-594** [comment]
@tpgxyz To follow on @davidebeatrici here is my current laptop screenshot'slogs : 

![Screenshot_20230617_231016](https://github.com/OpenMandrivaAssociation/distribution/assets/70574048/d399018d-bae7-4b63-9623-06e5a78f33da)

![Screenshot_20230617_231340](https://github.com/OpenMandrivaAssociation/distribution/assets/70574048/43a73bb3-c4b1-4a74-b5cf-51c020ebd0be)

**Comment by benbullard79** [comment]
This seems to be fixed here.

![Screenshot_20230926_084814](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/b3f13ca6-5a7c-4c37-8854-1dd83230f8c2)
