### ISSUE TITLE
Include KDE Discover by default on Rome Slim

### ISSUE THREAD

**Issue by joewood9364** [OpenMandrivaAssociation/distribution#2924]
Discover would be useful to have installed by default for users to help with finding apps and keeping the system updated.

**Comment by rugyada** [comment]
> keeping the system updated.

Discover (and dragora) is not suitable to update ROME or cooker systems.

Read documentation
https://wiki.openmandriva.org/en/distribution/guides/how-tos/howto-update-system
https://wiki.openmandriva.org/

**Comment by joewood9364** [comment]
I see thanks. Would it not still be useful just for installing apps like flatpaks easily?
Also regarding those recommended update commands does the GUI update configuration app implement them in the background? For example if I choose auto install updates in the app will it regularly perform the CLI commands mentioned?

**Comment by rugyada** [comment]
> Would it not still be useful just for installing apps like flatpaks easily?

If you wish, do
`sudo dnf --refresh install discover`

and/or any other package you need:
`sudo dnf --refresh install package_name`

**Comment by benbullard79** [comment]
If this is wontfix we should be able to close this right?
