### ISSUE TITLE
Integrate OM Update Configuration by default in Rome Slim

### ISSUE THREAD

**Issue by joewood9364** [OpenMandrivaAssociation/distribution#2925]
Currently there is an extra step within the welcome app to enable the update configuration app. This should simply be pre-installed.
The option could also be provided thought KDE settings as in fedora where there is an "updates" section at the bottom of KDE settings.

**Comment by rugyada** [comment]
> This should simply be pre-installed.

Not in  ’Slim’ ISO images.
The Plasma ’Slim’ ISO images offer a minimal Plasma5 environment and leave the users free to install what they really need.

**Comment by joewood9364** [comment]
That's what I like about the slim iso as well since most KDE distros are very bloated. I would say the configuration app is very small and an important one as it simplifies the update process for new users like myself, adding minimal footprint but key functionality?
There are also other apps less important like Gwenview and Kate that are installed. (I was going to open another issue for these to be removed from the slim iso?😄)

**Comment by rugyada** [comment]
> There are also other apps less important like Gwenview and Kate that are installed.

Less or more important is personal opinion.
In minimal system Gwenview or other similar image viewer app is sort of must-have.
Even more is a text editor.
Gwenview and Kate/Kwrite are among KDE Plasma most popular basic applications.
