### ISSUE TITLE
[Bug] Gzdoom cannot be installed through dnf in ROME

### ISSUE THREAD

**Issue by fleurc** [OpenMandrivaAssociation/distribution#2926]
**OpenMandriva version**:  ROME (updated as of 5th of July 2023)

**Describe the bug**: Gzdoom doesn't see the libomp dependency, cannot install.

**Steps to reproduce**:
1. Open Terminal or dnfdrake
2. sudo dnf install gzdoom
3. Warning is given: Nothing provides libomp.so.1(VERSION)(64bit) needed by gzdoom-4.10.0-1.x86_64 from rolling-x86_64-unsupported
4. sudo dnf install libomp libomp-devel
5. ldconfig -p | grep libomp.so.1
6. sudo dnf install gzdoom
7. Warning is given again.

**Observed behavior**:
Package cannot be installed because of the warning, seems like version or description of dependency on package install is badly
written or broken. Unless there is a difference between lib64 and lib (there shouldn't be in this case as the libomp and libomp-devel install to lib64 folder).

The paths shown by ldconfig -p | grep libomp.so.1 is as follows:
libomp.so.1 (libc6,x86-64) => /lib64/libomp.so.1
libomp.so.1 (libc6) => /usr/lib/libomp.so.1

**Expected behavior**:
gzdoom finds libomp and libomp-devel packages and installs correctly.

**Additional comment**:
I've read that unsupported is a barely maintained repo, i understand that perfectly so i have no expectations that the fix for this will come anytime soon, but making the issue is still important as it can help with this package and similar errors in the future.

If there is any observation or help without having to immediately repackage the thing i'll accept it.

Also i agree that i checked and this is not a duplicate.

**Logs and screenshots if relevant**
[Log of Terminal](https://privatebin.io/?6162fbfc924be2fd#FGyG1EM2Z4Ejf7Gd1eQd4CGN4MECozzmkXTddfwvXgtD)

**Comment by benbullard79** [comment]
Should be fixed now with `gzdoom-4.10.0-2`. Fixed by bero, all I did was push buttons.

![Screenshot_20230705_173002](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/334d540c-a626-47e7-b349-0ef451a6983f)

Result:

![Screenshot_20230705_173247](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/914f8617-8b88-4b2b-a0c6-e214fcb80009)
