### ISSUE TITLE
[Package Request] Imv: An image viewer for Wayland

### ISSUE THREAD

**Issue by fleurc** [OpenMandrivaAssociation/distribution#2927]
Official package name: imv

License (must be an OSI approved Open Source license): MIT

Download URL of latest release: [4.4.0](https://git.sr.ht/~exec64/imv/tree/v4.4.0)

Latest release date (must be recent): 5 months ago, February 2023

Description:
imv is a command line image viewer intended for use with tiling window managers.

[Project home](https://sr.ht/~exec64/imv/)

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/imv-an-image-viewer-for-wayland/4948/4

**Comment by AngryPenguinPL** [comment]
Sorry for the delay, the application is ready and is now being published in"
cooker - main repo
rome(rolling) - main/testing repo
