### ISSUE TITLE
Codecs canNot be Installed.

### ISSUE THREAD

**Issue by fleurc** [OpenMandrivaAssociation/distribution#2928]
**OpenMandriva version**: ROME

**Describe the bug**: Cannot install Codecs thanks to nothing providing necessary libraries.

**Steps to reproduce**:
1. Install OpenMandriva ROME;
2. Open OM-Welcome;
3. Go to Multimedia
4. Click on Codecs;
5. Install fails;
6. Open Dnfdrake;
7. Try to manually install codecs;
8. Error.

**Observed behavior**:
When trying to install through OM-Welcome all it says is Codecs Not Installed;
When trying to install through Dnfdrake, the following errors appears:

Error: 
 Problem: conflicting requests
  - nothing provides libavutil.so.57()(64bit) needed by x264-0.164-0.20220601.2.x86_64 from rolling-x86_64-restricted
  - nothing provides libavutil.so.57(LIBAVUTIL_57)(64bit) needed by x264-0.164-0.20220601.2.x86_64 from rolling-x86_64-restricted
  - nothing provides libavcodec.so.59()(64bit) needed by x264-0.164-0.20220601.2.x86_64 from rolling-x86_64-restricted
  - nothing provides libavcodec.so.59(LIBAVCODEC_59)(64bit) needed by x264-0.164-0.20220601.2.x86_64 from rolling-x86_64-restricted
  - nothing provides libavformat.so.59()(64bit) needed by x264-0.164-0.20220601.2.x86_64 from rolling-x86_64-restricted
  - nothing provides libavformat.so.59(LIBAVFORMAT_59)(64bit) needed by x264-0.164-0.20220601.2.x86_64 from rolling-x86_64-restricted
  - nothing provides libswscale.so.6()(64bit) needed by x264-0.164-0.20220601.2.x86_64 from rolling-x86_64-restricted
  - nothing provides libswscale.so.6(LIBSWSCALE_6)(64bit) needed by x264-0.164-0.20220601.2.x86_64 from rolling-x86_64-restricted
(try to add '--skip-broken' to skip uninstallable packages)

**Expected behavior**:
OM-Welcome: Codecs Installed.
Dnfdrake: Packages installed successfully.

**Additional comment**:
I hope this issue doesn't affect users of OpenMandriva Lx 4.3 as it affects ROME.

**Logs and screenshots if relevant**
N/A.

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/codecs-cannot-be-installed/4957/1

**Comment by fleurc** [comment]
The above worked, thank you.

Though idk if i should close the issue thanks to the x264 package needing to be installed outside the Rolling repos.

**Comment by benbullard79** [comment]
This issue is fixed.
