### ISSUE TITLE
kuser does not run from GUI

### ISSUE THREAD

**Issue by itchka** [OpenMandrivaAssociation/distribution#2930]
**OpenMandriva version**: 23.08 (ROME) Rolling for znver1

**Describe the bug**: Launching kuser from the gui asks for password (via kdesu) password is entered correctly but kuser does not start.

**Steps to reproduce**: Start kuser from the launcher.

**Observed behavior App does not appear

**Expected behavior**: App window should appear to allow editing

**Additional comment**:  It is possible to start kuser from the command line and it does work but the gui looks a bit odd (see screenshot. Also relevant terminal output attached.
![image](https://github.com/OpenMandrivaAssociation/distribution/assets/7284530/d52b142b-543a-45e7-bb38-f2b07c048279)

**Logs and screenshots if relevant**
kuser: /lib64/libldap-2.4.so.2: no version information available (required by /lib64/libKPim5Ldap.so.5)
kuser: /lib64/liblber-2.4.so.2: no version information available (required by /lib64/libKPim5Ldap.so.5)
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "KUser" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "KUser" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "KDE User Editor" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "(c) 1997-2000, Denis Perchine\n(c) 2004, Szombathelyi Gy\xC3\xB6rgy" msgid_plural: "" msgctxt: ""
Your code needs to be ported in KF5.  See the Ki18n programmers guide.
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Your names" msgid_plural: "" msgctxt: "NAME OF TRANSLATORS"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Your emails" msgid_plural: "" msgctxt: "EMAIL OF TRANSLATORS"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Users" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Groups" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&Add..." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&Edit..." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&Delete..." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&Set Password..." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&Add..." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&Edit..." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&Delete..." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&Reload..." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&Select Connection..." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Show System Users/Groups" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Reading configuration" msgid_plural: "" msgctxt: ""
kf.xmlgui: KXMLGUI file found at deprecated location ("/usr/share/kuser/kuserui.rc") -- please use ${KDE_INSTALL_KXMLGUI5DIR} to install this file instead.
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Ready" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "KDE User Manager" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "UID" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "User Login" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Full Name" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Home Directory" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Login Shell" msgid_plural: "" msgctxt: ""

**Comment by benbullard79** [comment]
To make the gui a little better right click on toolbar, unselect 'Lock Toolbar Position' then under 'Toolbar Settings>Text Position' select either 'Text Alongside Icons`  or 'Text Under Icons'. IMO this is a flaw or bug in a lot of KDE applications including Kate and Kwrite. Perhaps the 'Lock Toolbar Position' should not be default setting? Perhaps this should have a separate bug report?

**Comment by AngryPenguinPL** [comment]
Can't confirm. Works when running from a shortcut in the menu

https://github.com/OpenMandrivaAssociation/distribution/assets/3121142/3d07cabc-4331-450c-b662-687cc8f48d07

**Comment by benbullard79** [comment]
It is because of this:

![Screenshot_20230829_075702](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/3a049b75-02bd-48be-8fd0-e0ceb06efb26)

That should be:

Command Line Argument: `%i kuser`

**Comment by benbullard79** [comment]
Ah, I may have missed something more obvious. Under 'Program' we have listed 'kdesu'. Perhaps that should be 'kuser' and the 'Command Line Argument' should be blank. This seems betterer to me.

![Screenshot_20230829_081117](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/098cfc1d-1995-4937-b3eb-946018cfc2cc)

Works here.

**Comment by berolinux** [comment]
Fixed in 16.08.3-10
