### ISSUE TITLE
OM-Control Center Print setup nonfunctional

### ISSUE THREAD

**Issue by mkropf777** [OpenMandrivaAssociation/distribution#2931]
**OpenMandriva version**:

**Describe the bug**:

**Steps to reproduce**:

**Observed behavior**:

**Expected behavior**:

**Additional comment**:

**Logs and screenshots if relevant**

**Comment by mkropf777** [comment]
OM v. 23.08 Using OM Control Center the printer setup sits there with no ability to open up for use.    Used DnfDrake to reinstall to see if it would resolve, but no different after reinstall.   It is there and all the other areas under Hardware work besides this one.     Cannot use for printing setup and no clear alternative is present.    I tried CUPS to set up with no response with ipp and after reload of ipp from its removal.   The printer being USB, I have also changed out lusb interface and the same problem.
Should not OM Control Center /Hardware/ Printer setup function?

**Comment by benbullard79** [comment]
Not sure what does not work?

![Screenshot_20230830_201344](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/cd7f67b2-90cf-486c-bf3e-080142911ab9)

![Screenshot_20230830_201412](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/5229ea4a-6fac-408a-8d88-e30c57dea8ca)

![Screenshot_20230830_201504](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/6b3f249b-4516-4719-988d-48f937696f83)

![Screenshot_20230830_201551](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/e8e9811a-353c-49fa-a2c1-6d5868738d55)

![Screenshot_20230830_201619](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/e6b8b8bf-19a7-4dd5-957d-6a4a37bc42c8)
 
Test page prints. Works here. Can not reproduce the issue.

**Comment by mkropf777** [comment]
Unfortunately, for whatever the reason, the icon on the top screen with the printer, has no working response at all. Your use of it may work. Maybe something did not load correctly in my installation. I simply do not know. I can get any other Hardware or other setting to respond, but not this one. I wish I could exple it! I cannot. I am sure that it works for some. Reinstall the whole system? I don't know.
In every other respect, the platform works well, or at least to the extent that I have had the opportunity to use it.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mkropf777** [comment]
If I did not make the business clear, exactly where the red arrow is on the top screen has nothing of any useful action in the GUI. Perhaps there is some Terminal based inquiry which might detect whether this icon has an action faultily set, not at all set or not performing as it is intended to fo. I again do not know. At least using terminal there is some feedback that shows that the action cannot be done. Here I get no feedback from the GUI and have no idea as to what is 'failing to happen under the hood'.
I was trying to see if there was a work around.
The computer used for this is a Celeron N4120 Intel based unit with a decent amount of RAM at 8 GB and with a fairly decent prior function under Q4OS, thought I was having a bit of difficulty doing some things under Debian as the Headers got corrupted after a few months and that is a real bitch to deal with as it creates an inability to manage updates on the system when that happens.
I was trying OpenMandriva after having considered Mageia, mostly as there are too many new changes with the latter. I had used Mandrake a long time ago, but never had any issues with that.

------- Original Message -------

**Comment by benbullard79** [comment]
From what you have told us all we know is that for you the application does not start. Firtst step try starting it from terminal and seeing if there is any output. If there is post all of the output here as code (<> icon). 

To start the printer configuration application from terminal:

`$ kcmshell5 kcm_printer_manager`

Next in that OM Control Center under System click on:

![Screenshot_20230830_233652](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/5133fac8-237f-48f0-8c82-dfde255f4ed3)

enter root password when prompted and the 'omv-bug-report.log' will be created in you home directory. Attach that here in next post. You might want to take a look and see what information is in there. Nothing private I can assure you. Just system info.

**Comment by mkropf777** [comment]
I will respond with the request, but first: From Konsole
***@***.*** ~]$ kcmshell5 kcm_printer_manager
Could not find module 'kcm_printer_manager'. See kcmshell5 --list for the full list of modules.
***@***.*** ~]$

------- Original Message -------

**Comment by mkropf777** [comment]
Your request for the bug support, though I believe we can both see part of the problem from my last note; See attached

------- Original Message -------

**Comment by mkropf777** [comment]
Apparently the problem has not been foreign to some reports:
https://www.reddit.com/r/kde/comments/ydur33/missing_printer_setup_module_in_system_settings/?rdt=36236
https://ubuntuforums.org/showthread.php?t=2269586

https://bbs.archlinux32.org/viewtopic.php?id=2782

------- Original Message -------

**Comment by benbullard79** [comment]
If you are using OMLx Plasma desktop version you should see this:

```
$ rpm -qa print-manager
print-manager-23.04.3-1.x86_64
```

If you don't have that package you will need to install it. _That package is installed by default in OMLx Plasma desktop versions._ I am not sure but I do not believe is would be installed in OMLx Plasma slim desktop versions.

**Comment by mkropf777** [comment]
Thank you very much for your posts. I did put in the smaller Plasma, or as you call it Plasma slim, but did not realize that it was so pared down as to limit the printer setup which I would have thought might be even in the most bare bones configuration. I haave used Puppy Linux and Damned Small Linux and both of them had printing cpacities set into the setup even in their super compacted state. Hopefully once I can add that component I cn get the system up in its full functioning.
This is a bit strange in my history with various Distros as I have not had it in OpenSUSE, Fedora or in PCOS Linux trials nor even with brief an unsatisfactory trials of a few other distros, a few of which are now defunct.

------- Original Message -------

**Comment by benbullard79** [comment]
If you have trouble adding that component do let us know. To install it is simple. Open Konsole (terminal) and run:

`$ sudo dnf --refresh in print-manager`

I would guess there will be other packages pulled as dependencies.

**Comment by mkropf777** [comment]
As noted a problem with kwin-x11 etc.

------- Original Message -------

**Comment by mkropf777** [comment]
All the different means to do the business give a consistent endpoint with the same error as would be expected. At least the interfaces agree. I still cannot get the business to work properly. I would note that I have used rpm on PCOS Linux with apt and obviously in a different manner as well as in OpenSUSE and in Fedora. I will remember this modified usage to clean the distro, whatever the rationale might be for the correction, but why is this rpm requiring the extra notations in the use of Terminal. Perhaps I am lazy, but I have used dnf for ages, maybe for 8 years or more and never saw this as a syntax in Terminal. Yes, the GUI shortcut may be easier to use, but it is still a bit baffling.
You obviously have better things to do than explain the unique runnings of OM to me.. I don't mean to waste your time, but it is certainly quite different!

------- Original Message -------

**Comment by rugyada** [comment]
"_The Plasma ’Slim’ ISO images offer a minimal Plasma5 environment and leave the users free to install what they really need._"
It's assumed that one knows in advance what to install and how.

Otherwise, 2 options:

\- 1.
make the helping people aware that you installed the Slim ISO,
kindly ask them what you would need to get your wish accomplished

\- 2.
install the full featured ISO

In your particular case you may want to install:

task-printing
task-printing-scanning
system-config-printer-gui

And read documentation
https://wiki.openmandriva.org/en/distribution/guides/how-tos/printer

On a side note, fill the informative fields in bug report submission instead of leave it uselessly full empty.
They are there for reasons.

This bug report has been closed because of

> [mkropf777](https://github.com/mkropf777)
> Success! Thanks
