### ISSUE TITLE
Upgrade issue with problem appartently related to difficulty with kf6-kconfig

### ISSUE THREAD

**Issue by mkropf777** [OpenMandrivaAssociation/distribution#2932]
**OpenMandriva version**:

**Describe the bug**:

**Steps to reproduce**:

**Observed behavior**:

**Expected behavior**:

**Additional comment**:

**Logs and screenshots if relevant**

**Comment by mkropf777** [comment]
Unable to upgrade via sudo dnf upgrade with error.   Have only used the system for 2-3 weeks at most and now apparently difficulty with kf6-kconfig upgrade.   Nothing further reported from Konsole.
Used Discover to try and got a very long error message:
I can snd that as a follow up as I cannot tell how long to make this message
Using Openmandriva 23.08 ROME Rolling x86 64 plasma with lean form with few additions, but would hope for basic upgrade not to be problematic with this limited form.   I have used truncated release forms before in other distros without a problem.

**Comment by mkropf777** [comment]
To make the report easier to read I have pasted it into LibreOffice as a file:
[kf6-kconfig reedback.odt](https://github.com/OpenMandrivaAssociation/distribution/files/12551610/kf6-kconfig.reedback.odt)

**Comment by mkropf777** [comment]
Hit button by accident to close.

**Comment by rugyada** [comment]
> Unable to upgrade via sudo dnf upgrade with error.

https://wiki.openmandriva.org/en/distribution/guides/how-tos/howto-update-system


> To make the report easier to read I have pasted it into LibreOffice as a file

Better a plain .txt file instead, and copy/paste the full console output including the command/s.

**Comment by mkropf777** [comment]
For whatever reason, I could not get the business to work through the System Update. Even after using the steps for ROME, I am left with an error:
"Error: Error downloading packages:
kwin-x11-5.27.7-3.x86_64: Cannot download, allmirrors were already tried without success"
I fail to understand how the file is there for use as a call, but not as a reached retrieval value.
Is the file now defuncrt? Is it incorrectly labelled?

------- Original Message -------

**Comment by benbullard79** [comment]
There was a bug causing this. It is fixed now. Upgrade ROME using the instructions for ROME in the wiki. Or open Konsole and:

`sudo dnf clean all ; sudo dnf --allowerasing dsync`

**Comment by mkropf777** [comment]
I fixed it already. I am clearly a novice to Openmandriva, but I have some skills and I have figured things out which I was not ideally confident enough to address by myself as a newbie on this system. I doubt that I will need further assistance as I have fully managed to work out the business, even the ddync command.
Thanks for your assistance.
It is hard doing support, though I do not do this for software, I yet understand the demanding nature of the business in a different manner.

------- Original Message -------

**Comment by benbullard79** [comment]
If you do have problems in the future do not hesitate to ask for help. Bugs here other stuff in the [OpenMandriva Forum](https://forum.openmandriva.org/) or on [OpenMancriva Chat](https://wiki.openmandriva.org/en/team/chat).

Closing this one.
