### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by jpietarinen** [OpenMandrivaAssociation/distribution#2933]
**OpenMandriva version**: 23.08 ROME

**Describe the bug**: /usr/bin/mariadb-config --libs : typo in path

**Comment by benbullard79** [comment]
```
$ /usr/bin/mariadb_config --libs
-L/usr//usr/lib64/ -lmariadb
```
You could create a symbolic link if you need `/usr/bin/mariadb-config` instead of `/usr/bin/mariadb_config`.

We need a developer to weigh in on whether this is or is  not a but. I do not know.

**Comment by benbullard79** [comment]
I asked this of OM devs and got:

> Yes, just not a very important one. Note the -L/usr//usr/lib64/ in the output. That's clearly wrong (but not very relevant because stuff in /usr/lib64 is found anyway, even without any -L)

Confirming as bug.

**Comment by tpgxyz** [comment]
This is fixed
`[tpg@omv-rockpro64 mariadb]$ file mariadb-common-11.2.1-1-omv2390.aarch64.rpm 
mariadb-common-11.2.1-1-omv2390.aarch64.rpm: RPM v3.0 bin mariadb-common-11.2.1-1
[tpg@omv-rockpro64 mariadb]$ ./mysql_config --libs
-L/usr/lib64  -lmariadb -lz -ldl -lm -lssl -lcrypto`
