### ISSUE TITLE
f3d - Fast and minimalist 3D viewer

### ISSUE THREAD

**Issue by RDKRACZ** [OpenMandrivaAssociation/distribution#2934]
**Official package name:** f3d

**License (must be an OSI approved Open Source license):**  BSD-3-Clause

**Download URL of latest release:** https://github.com/f3d-app/f3d/releases/tag/v2.1.0

**Latest release date (must be recent):** 02/07/2023

**Description:** F3D (pronounced `/fɛd/`) is a fast and minimalist 3D viewer. It supports many file formats, from digital content to scientific datasets (including glTF, STL, STEP, PLY, OBJ, FBX, Alembic), can show animations and support thumbnails and many rendering and texturing options including real time physically based rendering and raytracing.
It is fully controllable from the command line and support configuration files. It can provide thumbnails, support interactive hotkeys, drag&drop and integration into file managers.
F3D also contains the libf3d, a simple library to render meshes, with C++ and Python Bindings, as well as experimental Java and Javascript bindings.

**Comment by RDKRACZ** [comment]
It's already available in Arch (Extra); Debian 12 (Main); Mageia 9 (core); Ubuntu 23.04 (Universe); FreeBSD 13

**Comment by mandian** [comment]
Hi @RDKRACZ 
f3d v2.2.1 is now in cooker repo and will be soon (when the next UM will be run) in rolling and 5.0.
