### ISSUE TITLE
fstl - A fast STL file viewer

### ISSUE THREAD

**Issue by RDKRACZ** [OpenMandrivaAssociation/distribution#2935]
**Official package name:** fstl

**License (must be an OSI approved Open Source license):** https://github.com/fstl-app/fstl?tab=readme-ov-file#license

**Download URL of latest release:** https://github.com/fstl-app/fstl/releases/tag/v0.10.0

**Latest release date (must be recent):** Jun 28, 2022

**Description:** It is designed to quickly load and render very high-polygon models; showing 2 million triangles at 60+ FPS on a mid-range laptop.

**Comment by RDKRACZ** [comment]
It's already available for Debian 10, 11, 12; Ubuntu 20.04 - 23.04; OpenSUSE Leap 15.5 and Tumbleweed; Void Linux; NetBSD 9.3

**Comment by mandian** [comment]
Hi @RDKRACZ 
fstl v.0.10.0 is now in cooker repo and will be soon (when the next UM will be run) in rolling and 5.0.
