### ISSUE TITLE
Upgrade 4.3 to 5.0 fails

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2943]
**OpenMandriva version**:
Rock 4.3
**Describe the bug**:
Attermpt to upgrade system with `dsync --allowerasing` fails.
**Steps to reproduce**:
Install Rock/4.3, upgrade system, switch repos to 5.0 and run `dnf clean all ; dnf dsync --allowerasing`.
**Observed behavior**:
System/Distro upgrade fails.
```
Error: Transaction test error:
  file /usr/lib64/libkfontinst.so.5 from install of lib64plasma-workspace-5.27.8-1.x86_64 conflicts with file from package lib64kfontinst5-5.23.5-2.x86_64
  file /usr/lib64/libplasma-geolocation-interface.so.5 from install of lib64plasma-workspace-5.27.8-1.x86_64 conflicts with file from package lib64plasma-geolocation-interface5-5.23.5-2.x86_64
  file /usr/lib64/libkworkspace5.so.5 from install of lib64plasma-workspace-5.27.8-1.x86_64 conflicts with file from package lib64kworkspace5_5-5.23.5-2.x86_64
  file /usr/lib64/libkfontinstui.so.5 from install of lib64plasma-workspace-5.27.8-1.x86_64 conflicts with file from package lib64kfontinstui5-5.23.5-2.x86_64
  file /usr/lib64/libtaskmanager.so.6 from install of lib64plasma-workspace-5.27.8-1.x86_64 conflicts with file from package lib64taskmanager6-5.23.5-2.x86_64
  file /usr/lib64/libcolorcorrect.so.5 from install of lib64plasma-workspace-5.27.8-1.x86_64 conflicts with file from package lib64colorcorrect5-5.23.5-2.x86_64
  file /usr/lib64/libweather_ion.so.7.0.0 from install of lib64plasma-workspace-5.27.8-1.x86_64 conflicts with file from package lib64weather_ion7-5.23.5-2.x86_64
```
**Expected behavior**:
System/Distro upgrade should succeed.
**Additional comment**:

**Logs and screenshots if relevant**
[openmandriva-rock-x86_64.repo.txt](https://github.com/OpenMandrivaAssociation/distribution/files/13168345/openmandriva-rock-x86_64.repo.txt)

Commands used `dnf clean all` then `dnf dsync --allowerasing`. Log of transaction:

[43to50.log.txt](https://github.com/OpenMandrivaAssociation/distribution/files/13169157/43to50.log.txt)

**Comment by berolinux** [comment]
43to50log.txt looks to me like it succeeded (but is missing the new kernel).
The error from libkfontinst and friends should be fixed in the current plasma-workspace 5.27.9 packages.

**Comment by benbullard79** [comment]
I tried a Rock/4.3 to Cooker to simulate what would happen with 4.3 to 5.0. It looked like it would work in Konsole but there was some problem solving and multiple steps. One was new version of `dnf` was installed but old `dnf` was not removed. Another is that kernel still has to be updated manually in a separate step. Then since this was tested in VBox the system would not reboot. Had to hard shut down system using the VBox power off. Then system will not boot.

![Screenshot_20231025_175732](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/71ec23f5-d195-4092-b9b6-be757f27086e)

This is the log, it is a bit long and involved...

[43toCooker.txt](https://github.com/OpenMandrivaAssociation/distribution/files/13171369/43toCooker.txt)

Hope this info is useful for when these packages go to 5.0.

**Comment by benbullard79** [comment]
This is fixed given one is upgrading a default system without a lot of customization, expecially changes to configuration or system packages.. If user makes changes to configuration or system they need to know what they have done and be able to report that in issue report here or in forum. Or else! Or else it will be difficult for anyone to help because we won't know what changes user made. This is a constant problem with these system/distro upgrades.

https://forum.openmandriva.org/t/upgrading-rock-4-3-to-rock-5-0/5071
