### ISSUE TITLE
UnixTree 3.0.4-1 for amd64 (Xtree clone for Linux/Unix)

### ISSUE THREAD

**Issue by deltakprime** [OpenMandrivaAssociation/distribution#2946]
Official package name: UnixTree-3.0.4-1_amd64.rpm

License (must be an OSI approved Open Source license): GNU General Public License Version 3

Download URL of latest release: https://dokakod.github.io/unixtree/packages/UnixTree-3.0.4-1_amd64.rpm

Latest release date (must be recent): 24 Apr 2022

Description: Xtree file manager clone for Linux/Unix

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/error-message-installing-unixtree-package-from-rpm-file/5075/7

**Comment by berolinux** [comment]
Package added to cooker.

**Comment by deltakprime** [comment]
Thank you, Bernhard.

I really appreciate your help.

Michael Orlando
