### ISSUE TITLE
New package request:  dolphin-quick-view

### ISSUE THREAD

**Issue by rugyada** [OpenMandrivaAssociation/distribution#2949]
Official package name:
dolphin-quick-view

License (must be an OSI approved Open Source license):
GPL-3.0 license 

Download URL of latest release:
https://github.com/Nyre221/dolphin-quick-view
https://store.kde.org/p/2083711/

Latest release date (must be recent):
https://github.com/Nyre221/dolphin-quick-view/releases

Description:
Simple program to have a quick preview of the files in a folder (similar to Apple's Quick Look)

**Comment by AngryPenguinPL** [comment]
Project is no longer maintained but was restarted in C++ and now is on under kde care https://invent.kde.org/danagost/Kiview
Still interested in adding it?

**Comment by rugyada** [comment]
> Still interested in adding it?

Yes I'd like ;)

**Comment by rugyada** [comment]
Thank you 

![ss_20240731_215925](https://github.com/user-attachments/assets/002d69b0-6710-42d7-8c23-5e1e0238dd58)
