### ISSUE TITLE
Omni Issue Tracker for OMLx Rock/5.0 LXQt desktop

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2952]
**OpenMandriva version**:
All with LXQt desktop

**Describe the bug**:
Omni Tracker bug report to track issues and enhancements for OMLx LXQt desktop.

**Steps to reproduce**:
Install your preferred version of LXQt ISO and test. Report and help resolve issues. Suggest enhancements.

**Observed behavior**:
Write your observed behavior about any issue or enhancement in a post and include OMLx version, ISO build ID number, and any relevant logs.

**Expected behavior**:
A well working but minimal desktop.

**Additional comment**:
Reports should include:

1. What you are testing on: **What version of OMLx, please include the Build ID number of the iso you used. Is this the iso 'Live' or an installed system, is this on hardware or in VirtualBox or other VM?** 

2. **Detailed description.** This does not have to be long but there needs to be enough for someone to work with. This is a work project.

3. Any and all **relevant logs** and **screen-shots**. It would be wise to include the entire journal log with any report or post.

4. If you do not know how to do any of this please ask here and we will walk you through this.

5. Any terminal output longer than about 20-30 lines can be put in a .txt file and attached to your report.

Developers can not fix "it's broke" they need a cause or otherwise something to work on. That is what the **screen-shot**s and **especially the logs** are for.

**Logs and screenshots if relevant**
Please do include logs and screenshots as much as possible.

**Comment by benbullard79** [comment]
This was a test on Vivobook ASUSLaptop M1605YA installed from Rock/5.0 znver1 LXQt iso.

1. `notepadqq` crashes 
```
$ notepadqq
Segmentation fault (core dumped)
[live@omv-2840 ~]$ journalctl | grep notepadqq
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal', 'wheel' can see all messages.
      Pass -q to turn off this notice.
Jan 11 01:47:31 omv-2840 systemd-coredump[1920]: Process 1774 (notepadqq-bin) of user 1000 dumped core.
                                                 #1  0x0000563f4c7670d1 _ZNK15EditorTabWidget7tabTextEi (notepadqq-bin + 0x15a0d1)
                                                 #2  0x0000563f4c7cd298 _ZN8Sessions11saveSessionEP9DocEngineP18TopEditorContainer7QStringS4_ (notepadqq-bin + 0x1c0298)
                                                 #3  0x0000563f4c7dee76 _ZN13BackupService11writeBackupEP10MainWindow (notepadqq-bin + 0x1d1e76)
                                                 #4  0x0000563f4c7dd729 _ZN13BackupService13executeBackupEv (notepadqq-bin + 0x1d0729)
                                                 #19 0x0000563f4c714b47 main (notepadqq-bin + 0x107b47)
                                                 #22 0x0000563f4c7100f1 _start (notepadqq-bin + 0x1030f1)
Jan 11 01:48:50 omv-2840 systemd-coredump[3939]: Process 1958 (notepadqq-bin) of user 1000 dumped core.
                                                 #1  0x000055c827f320d1 _ZNK15EditorTabWidget7tabTextEi (notepadqq-bin + 0x15a0d1)
                                                 #2  0x000055c827f98298 _ZN8Sessions11saveSessionEP9DocEngineP18TopEditorContainer7QStringS4_ (notepadqq-bin + 0x1c0298)
                                                 #3  0x000055c827fa9e76 _ZN13BackupService11writeBackupEP10MainWindow (notepadqq-bin + 0x1d1e76)
                                                 #4  0x000055c827fa8729 _ZN13BackupService13executeBackupEv (notepadqq-bin + 0x1d0729)
                                                 #19 0x000055c827edfb47 main (notepadqq-bin + 0x107b47)
                                                 #22 0x000055c827edb0f1 _start (notepadqq-bin + 0x1030f1)

```
2. `rosa-imagewriter` does not start
```
$ rosa-imagewriter
lxqt-sudo: Stripping child environment except for: DISPLAY,LANG,LANGUAGE,LC_ADDRESS,LC_ALL,LC_COLLATE,LC_CTYPE,LC_IDENTIFICATION,LC_MEASUREMENT,LC_MESSAGES,LC_MONETARY,LC_NAME,LC_NUMERIC,LC_PAPER,LC_TELEPHONE,LC_TIME,PATH,QT_PLATFORM_PLUGIN,QT_QPA_PLATFORMTHEME,TERM,WAYLAND_DISPLAY,XAUTHLOCALHOSTNAME,XAUTHORITY
bash: line 1: /home/live/'/usr/lib64/rosa-imagewriter/rosa-imagewriter': No such file or directory
```

3.  `om-repo-picker` aka: Software Repository Selector does not ask for password or change the repos.

4,  Update Configuration utility does not ask for password or change the configuration.

This is the entire journal log:

[journal.txt](https://github.com/OpenMandrivaAssociation/distribution/files/13920484/journal.txt)

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/omni-tracker-for-issues-with-omlx-lxqt-desktop/5169/1

**Comment by benbullard79** [comment]
Closing, lack of interest.
