### ISSUE TITLE
Package request: zzz

### ISSUE THREAD

**Issue by K0-RR** [OpenMandrivaAssociation/distribution#2953]
Official package name: zzz

License (must be an OSI approved Open Source license): MIT

Source repository: https://github.com/jirutka/zzz

Download URL of latest release: https://github.com/jirutka/zzz/releases/

Latest release date (must be recent): Jul 10, 2022 - It's feature complete so no more new releases unless bug fixes.

Description: A simple program to suspend or hibernate your computer. It supports hooks before and after suspending.

`Currently available at Arch AUR and Alpine Linux repository`

**Comment by mandian** [comment]
version 0.1.1 is now in cooker and rolling. If you are using  rolling maybe you have to enable testing repo first.

**Comment by AngryPenguinPL** [comment]
Closing as solved.
