### ISSUE TITLE
Dooble browser crashed

### ISSUE THREAD

**Issue by peter-power-594** [OpenMandrivaAssociation/distribution#2954]
**OpenMandriva version**: OM Lx 5 Rock

**Describe the bug**: 
The page crashed (browser still running but the page turned blank) when trying to login with SNS to websites.

**Steps to reproduce**: 
Try to login to the OpenMandriva forum or Github

**Observed behavior**: 
The content of the page disappears

**Expected behavior**:
Should allow me to input me email / password

**Additional comment**:
Is working when disabling the sandbox as described here :
https://forums.gentoo.org/viewtopic-t-1123597-start-0.html
QTWEBENGINE_DISABLE_SANDBOX=1 /usr/bin/dooble

Would be nice if you push @AngryPenguinPL 2023.12.25 version to Rock please
(current one is from August 2023.08 in Rock)

**Logs and screenshots if relevant**
[pierre@concorde ~]dooble
qt.core.qobject.connect: QObject::connect(QObject, Unknown): invalid nullptr parameter
The following paths were searched for Qt WebEngine locales:
  /usr/lib64/qt6/translations/qtwebengine_locales
  /home/pierre/.Dooble
but could not find the translation file for the current locale: en-US.pak
You may override the default search paths by using QTWEBENGINE_LOCALES_PATH environment variable.
Translations WILL NOT be correct.
[0115/143221.841118:WARNING:resource_bundle_qt.cpp(83)] locale_file_path.empty() for locale
The following paths were searched for Qt WebEngine locales:
  /usr/lib64/qt6/translations/qtwebengine_locales
  /home/pierre/.QtWebEngineProcess
but could not find the translation file for the current locale: en-US.pak
You may override the default search paths by using QTWEBENGINE_LOCALES_PATH environment variable.
Translations WILL NOT be correct.
[0115/143221.878240:WARNING:resource_bundle_qt.cpp(83)] locale_file_path.empty() for locale
The following paths were searched for Qt WebEngine locales:
  /usr/lib64/qt6/translations/qtwebengine_locales
  /home/pierre/.QtWebEngineProcess
but could not find the translation file for the current locale: en-US.pak
You may override the default search paths by using QTWEBENGINE_LOCALES_PATH environment variable.
Translations WILL NOT be correct.
[0115/143221.880099:WARNING:resource_bundle_qt.cpp(83)] locale_file_path.empty() for locale
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
js: Refused to execute script from 'https://forum.openmandriva.org/ynh_portal.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
js: Refused to apply style from 'https://forum.openmandriva.org/ynh_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
js: Refused to execute script from 'https://forum.openmandriva.org/ynhtheme/custom_portal.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
js: Refused to apply style from 'https://forum.openmandriva.org/ynhtheme/custom_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
js: Refused to apply style from 'https://forum.openmandriva.org/ynhtheme/custom_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
../../../../../src/3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:prctl() failure

**Comment by AngryPenguinPL** [comment]
New Doobie in testing repo. You try it after enabling it

**Comment by peter-power-594** [comment]
Thank you @AngryPenguinPL, that's awesome ! ! !
It worked first try without the "no sandbox" quick fix :100: 

One feedback: thank you for adding the dictionnaries for the spellcheck, could you include the [_Translation_ directory](https://github.com/textbrowser/dooble/blob/master/Translations/README) as well :
![image](https://github.com/OpenMandrivaAssociation/distribution/assets/70574048/1ed5b364-54f4-46f8-a940-268cd1a62585)

For example if I launch the app like that :
```
DOOBLE_TRANSLATIONS_PATH=/home/pierre/Documents/dooble-2023.12.25/Translations/ dooble
```
Then I can select "SYSTEM" in the pulldown, restart the browser and get the user interfance in French language :)
The directory is not compiled, you just need the raw files as provided somewhere to be readable by the app.

**Comment by peter-power-594** [comment]
hmmm could connect to the OpenMandriva forum with 2023.12.25 but still needed to disable the sandbox to access the matrix chat on element. So I modified the /usr/bin/dooble like this :

```
#!/bin/sh
export QT_PLUGIN_PATH=/usr/lib64/qt6/plugins
export QTWEBENGINE_DISABLE_SANDBOX=1
exec /usr/bin/Dooble ""
```

Not sure if it's safe to do it be default

**Comment by rugyada** [comment]
Issue reported "_Dooble browser crashed_" looks fixed.
