### ISSUE TITLE
Telegram is falling

### ISSUE THREAD

**Issue by saber716rus** [OpenMandrivaAssociation/distribution#2955]
**OpenMandriva version**:
OpenMandriva Lx 24.01 (ROME) Rolling
**Describe the bug**:
telegram-desktop-4.12.2-1.znver1
In my opinion, the telegram version in the cooker is more stable than in rolling
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
libx265.so.199: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
libx265.so.199 is missing, x265 support will be disabled
[libvpx-vp9 @ 0x7fa75abae040] v1.13.1
[libvpx-vp9 @ 0x7fa75abad040] v1.13.1
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment

(telegram-desktop:2584): GLib-CRITICAL **: 21:21:01.076: g_variant_type_new_array: assertion 'g_variant_type_check (element)' failed

(telegram-desktop:2584): GLib-CRITICAL **: 21:21:01.076: g_variant_builder_init: assertion 'type != NULL' failed

(telegram-desktop:2584): GLib-CRITICAL **: 21:21:01.076: g_variant_builder_add_value: assertion 'valid_builder' failed

(telegram-desktop:2584): GLib-CRITICAL **: 21:21:01.076: g_variant_builder_add_value: assertion 'valid_builder' failed

(telegram-desktop:2584): GLib-CRITICAL **: 21:21:01.076: g_variant_builder_add_value: assertion 'valid_builder' failed

(telegram-desktop:2584): GLib-CRITICAL **: 21:21:01.076: '(null)' is not a valid GVariant format string

(telegram-desktop:2584): GLib-CRITICAL **: 21:21:01.076: g_variant_new: assertion 'valid_format_string (format_string, TRUE, NULL) && format_string[0] != '?' && format_string[0] != '@' && format_string[0] != '*' && format_string[0] != 'r'' failed

(telegram-desktop:2584): GLib-CRITICAL **: 21:21:01.076: g_variant_builder_clear: assertion 'valid_builder' failed

(telegram-desktop:2584): GLib-CRITICAL **: 21:21:01.076: g_variant_ref_sink: assertion 'value != NULL' failed
Segmentation fault (memory image has been flushed to disk)

**Comment by benbullard79** [comment]
`telegram-desktop-4.14.4 is in ROME/rolling and 5.0 repositories now.

**Comment by saber716rus** [comment]
> `telegram-desktop-4.14.4 is in ROME/rolling and 5.0 repositories now.

I was doing pr. can I close it then?

**Comment by saber716rus** [comment]
the problem has been fixed in the commit https://github.com/OpenMandrivaAssociation/telegram-desktop/commit/cd7862ac112c61c99eeaeda895cdddaf3013a138

**Comment by saber716rus** [comment]
telegram was updated, but it started to fall again, it seems that it's not about the telegram itself.

**Comment by benbullard79** [comment]
I verified on Cooker hw system that this is failing.

[omdv-bug-report-20240128100340.log](https://github.com/OpenMandrivaAssociation/distribution/files/14076483/omdv-bug-report-20240128100340.log)

[journal-telegram.txt](https://github.com/OpenMandrivaAssociation/distribution/files/14076493/journal-telegram.txt)

**Comment by saber716rus** [comment]
> I verified on Cooker hw system that this is failing.
> 
> [omdv-bug-report-20240128100340.log](https://github.com/OpenMandrivaAssociation/distribution/files/14076483/omdv-bug-report-20240128100340.log)
> 
> [journal-telegram.txt](https://github.com/OpenMandrivaAssociation/distribution/files/14076493/journal-telegram.txt)

I also checked in the cooker and there was no fall.

**Comment by saber716rus** [comment]
telegram is also crashing in version 5.0
[omdv-bug-report-20240128195822.log](https://github.com/OpenMandrivaAssociation/distribution/files/14076889/omdv-bug-report-20240128195822.log)
[telegam.log](https://github.com/OpenMandrivaAssociation/distribution/files/14076890/telegam.log)

**Comment by rugyada** [comment]
Telegram is working fine in cooker, and so it is in ROME 24.07.
