### ISSUE TITLE
[FR] om-repo-picker: when installing third-party repositories, then install the package immediately.

### ISSUE THREAD

**Issue by saber716rus** [OpenMandrivaAssociation/distribution#2956]
when installing third-party repositories, then immediately install the package. I.e., for example: if I install the Yandex repository, then install the package from this repository.

**Comment by benbullard79** [comment]
Can not reproduce.

I just added Yandex repo with OpenMandriva Repository Selector (aka: om-repo-picker). 

![Screenshot_20240123_105707](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/c01e5e13-5eff-4589-a28d-c2d1ead6c835)

I do not have` yandex-browser` installed.

![Screenshot_20240123_105616](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/c808abd8-6425-4bc2-bcc8-fb0586df7815)

**Comment by rugyada** [comment]
om-repo-picker is designed to add repositories, not to install sofware. User must do it.
