### ISSUE TITLE
Nvidia driver issue

### ISSUE THREAD

**Issue by pozitigor1** [OpenMandrivaAssociation/distribution#2957]
**OpenMandriva version**: 
OpenMandriva Lx 5.0 (Iodine) Rock with kernel 6.6.2 desktop

**Describe the bug**: 
Nvidia drvier not working as it should be

**Steps to reproduce**:
Install nvidia driver using dnf or hardware menu in OMCC

**Observed behavior**:
1.Broken GRUB2 loading, no nvidia-drm.modeset=1 in kernel parameters
2.Plasma X11 session runs without desktop effects. SDDM and Plasma wayland session lagging
3.Blender rendering with optix parameter is unavailable
4.Nvidia-settings not showing me settings that should be there like X11 options

**Expected behavior**:
1.Plasma runs smooth with desktop effects on X11/Wayland session, SDDM not lagging
2.Blender able to use my GPU with OptiX
3.No tearing

**Additional comment**:
It seems like nvidia driver not containing nvidia-xconfig in it
My GPU is nvidia GTX 1060

**Logs and screenshots if relevant**
![image](https://github.com/OpenMandrivaAssociation/distribution/assets/61246816/29d77e60-8d5b-419a-8faa-53a3804c4b01)
No X11 options or informations, Powermizer option does not exist
![image](https://github.com/OpenMandrivaAssociation/distribution/assets/61246816/edac3f3b-734f-41e6-9f1f-34d4ac9d7ed6)
KDE settings recognizes my GPU as llvmpipe

**Comment by pozitigor1** [comment]
if i start nvidia-settings from terminal, the output will be:
ERROR: NVIDIA driver is not loaded


(nvidia-settings:3416): GLib-GObject-CRITICAL **: 18:15:49.085: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

** (nvidia-settings:3416): CRITICAL **: 18:15:49.086: ctk_powermode_new: assertion '(ctrl_target != NULL) && (ctrl_target->h != NULL)' failed

ERROR: nvidia-settings could not find the registry key file or the X server is not accessible. This file
       should have been installed along with this driver at
       /usr/share/nvidia/nvidia-application-profiles-key-documentation. The application profiles will
       continue to work, but values cannot be prepopulated or validated, and will not be listed in the help
       text. Please see the README for possible values and descriptions.

**Comment by pozitigor1** [comment]
on further attempt to start nvidia-settings the output is:

(nvidia-settings:8151): GLib-GObject-CRITICAL **: 20:47:31.574: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(nvidia-settings:8151): Gtk-CRITICAL **: 20:47:31.586: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(nvidia-settings:8151): GLib-GObject-CRITICAL **: 20:47:31.587: invalid (NULL) pointer instance

(nvidia-settings:8151): GLib-GObject-CRITICAL **: 20:47:31.587: g_signal_handlers_block_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(nvidia-settings:8151): Gtk-CRITICAL **: 20:47:31.587: gtk_toggle_button_get_active: assertion 'GTK_IS_TOGGLE_BUTTON (toggle_button)' failed

(nvidia-settings:8151): GLib-GObject-CRITICAL **: 20:47:31.587: invalid (NULL) pointer instance

(nvidia-settings:8151): GLib-GObject-CRITICAL **: 20:47:31.587: g_signal_handlers_unblock_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(nvidia-settings:8151): Gtk-CRITICAL **: 20:47:31.587: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(nvidia-settings:8151): GLib-GObject-CRITICAL **: 20:47:31.587: invalid (NULL) pointer instance

(nvidia-settings:8151): GLib-GObject-CRITICAL **: 20:47:31.587: g_signal_handlers_block_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(nvidia-settings:8151): Gtk-CRITICAL **: 20:47:31.587: gtk_toggle_button_get_active: assertion 'GTK_IS_TOGGLE_BUTTON (toggle_button)' failed

(nvidia-settings:8151): GLib-GObject-CRITICAL **: 20:47:31.587: invalid (NULL) pointer instance

(nvidia-settings:8151): GLib-GObject-CRITICAL **: 20:47:31.587: g_signal_handlers_unblock_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(nvidia-settings:8151): Gtk-CRITICAL **: 20:47:31.587: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by benbullard79** [comment]
> ERROR: NVIDIA driver is not loaded

The `dmesg` and `journalctl -b` logs should show something about the kernel module not loading. If you could post those so we can get to a why the kernel module is not loading. Please put the logs in a .txt file and post those files here.

**Comment by benbullard79** [comment]
pozitigor1 maybe it would be easier for you to open OM-Welcome and click on the "Bug report tool" and post the file that creates here.

![Screenshot_20240122_105926](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/ab262856-7463-4739-b4e1-8af12e42ab5d)

That should include all or most of the logs needed to get to a cause for this issue.

**Comment by pozitigor1** [comment]
sure, here it is!
https://disk.yandex.ru/d/K5Lh-CQRxBZhHA

**Comment by pozitigor1** [comment]
my mail showed me that here was a message to show my dmesg and journalctl output:
https://disk.yandex.ru/d/2QpcJYV0lTFH3A

**Comment by pozitigor1** [comment]
I've tried to install other desktop environments(GNOME and maui) and to my surprise after i log into them the effects are enabled, no tearing and nvidia-settings have all of the options that it should have.
But when I reboot the system, all its smoothness and settings in nvidia go away, I can't even log into the Gnome session.

**Comment by pozitigor1** [comment]
Good afternoon! Did the files I sent yesterday help you to identify the cause of this problem? If you need any additional files, then tell me, I will certainly share them.

**Comment by benbullard79** [comment]
I am not a developer, not an expert on nvidia hardware or software. I mainly wanted to get the logs here for our developers. They are aware of this report. You can talk directly to OM devs at [OpenMandriva Chat](https://wiki.openmandriva.org/en/team/chat) if you wish. I would encourage you to do so.

**Comment by AngryPenguinPL** [comment]
Package in ROME 555.58.02-3 should be fixed now. Please re-open or create new bug topic if problem appear again.
