### ISSUE TITLE
Plasma 6 not detecting USB thumb drives when plugged in

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2965]
**OpenMandriva version**:

Cooker, with Plasma 6.0.1 X11

**Describe the bug**:

When a USB thumb drive is plugged into a USB port, Plasma 6 does not see the thumb drive. `lsblk` will see it, but on attempting to mount the thumb drive, it reports it's not in `/etc/fstab`. Plasma 6 will detect an Android phone connected via USB though.

**Steps to reproduce**:

* Boot OpenMandriva Cooker with Plasma 6.
* After logging in, insert a formatted USB thumb drive.
* Disks & Devices does not automatically open up to allow for mounting of the thumb drive, nor is it listed when D&D is manually opened.

**Observed behavior**:

Disks & Devices did not automatically open up to allow for mounting of the thumb drive, nor is it listed when D&D is manually opened.

**Expected behavior**:

Disks & Devices should have detected the thumb drive and opened to allow for mounting of it.

**Additional comment**:

**Logs and screenshots if relevant**

**Comment by benbullard79** [comment]
Maybe I spoke to soon in encouraging you to write a bug report on this. I just updated my Cooker (iso 2881) hw system. I do not see flash drive recognized in systemtray or Dolphin. But Dolphin also does not show all unmounted partitions like it did in P5 so this may be related to that. However flash drives are recognized by KDE Partitionmanager and `fdisk -l`. Not sure if this is/is not a bug.

**Comment by edwardp3** [comment]
My intent was to import a bookmark file into a web browser, where the file was on the thumb drive.

I was able to workaround this by copying the file from the thumb drive to my Android phone, then from the phone to ~/Documents, then import into the browser from there.

**Comment by benbullard79** [comment]
Confirmed with berolinux that this is a bug. Issue will be looked in to shortly.
