### ISSUE TITLE
foomatic-filters: error in POSTIN scriptlet - exit status 1

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2966]
**OpenMandriva version**:

Cooker

**Describe the bug**:

Error in POSTIN scriptlet in rpm package foomatic-filters

**Steps to reproduce**:

Installed cups and hplip separately, to add a printer. Cups install went fine. hplip included foomatic-filters, in which dnf displayed the following error as it was installing it:
```

 Installing       : foomatic-filters-4.0.17-21.noarch                                                  13/22 
  Running scriptlet: foomatic-filters-4.0.17-21.noarch                                                  13/22 
/var/tmp/rpm-tmp.SMQZua: line 4: fg: no job control
warning: %post(foomatic-filters-4.0.17-21.noarch) scriptlet failed, exit status 1

Error in POSTIN scriptlet in rpm package foomatic-filters
```

**Observed behavior**:

Error in foomatic-filters

**Expected behavior**:

Package install without error.

**Additional comment**:

Am able to successfully send test pages to the printer only from the CUPS and HPLIP interfaces. Printing from LibreOffice also works. 

From the web browsers (Chromium, Vivaldi), printing does not work. nothing is sent to the printer and CUPS does not show any print jobs. Does not matter whether CUPS or HPLIP is used to add the printer. If printing using the system dialog, no printers are listed. Printer is an HP OfficeJet Pro 8210. Will open separate bug for printing issue.

**Logs and screenshots if relevant**

**Comment by AngryPenguinPL** [comment]
That should be fixed in cooker with commit https://github.com/OpenMandrivaAssociation/foomatic-filters/commit/cd3a8efe26a5f86f2cfaaa0eef40a232ba326dce by @berolinux 

Please retest.
