### ISSUE TITLE
Save as PDF from Chromium does not save a PDF file

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2969]
**OpenMandriva version**:

Cooker

**Describe the bug**:

Due to inability to print web pages from Chromium-based browsers (see https://github.com/OpenMandrivaAssociation/distribution/issues/2967), the Save to PDF option also does not work. An attempt was made to save a web page as a PDF in this manner, however, no PDF file exists anywhere in the /home directory, not even the specified default of ~/Downloads.

**Steps to reproduce**:

* Launch Chromium
* Go to web page
* Select _Print_
* Select _Save as PDF_

**Observed behavior**:

PDF wasn't saved anywhere.

**Expected behavior**:

PDF should have saved to default directory, or prompted to save it, neither occurred.

**Additional comment**:

**Logs and screenshots if relevant**

**Comment by rugyada** [comment]
> Issue has cleared up on its own

Not exactly: @berolinux fixed it..
