### ISSUE TITLE
Wireshark failing to start

### ISSUE THREAD

**Issue by aunoor** [OpenMandrivaAssociation/distribution#2971]
**OpenMandriva version**: ROME 23.04

Wireshark installed from packet `wireshark-4.2.2-1.x86_64` is failed to start with next error:
`wireshark: symbol lookup error: wireshark: undefined symbol: _ZN10QAudioSink12stateChangedEN6QAudio5StateE, version Qt_6`

Wireshark is depended from lib64Qt6Multimedia.so.6, which is installed from `lib64Qt6Multimedia-6.7.0-0.rc.1.x86_64`

Looks like version of Qt6 is raised, but packets depended from Qt6 is not was rebuilded.

**Comment by benbullard79** [comment]
`wireshark-4.2.2-2` is publishing for x86_64 rolling/main/testing repo. When that is finished publishing to install:

`sudo dnf up wireshark --enablerepo rolling-testing-x86_64`

For a x86_64 system. Package is building for znver1 and aarch64 also. Hopefully that will work. I do not use wireshark and have not tested.

**Comment by aunoor** [comment]
It's work now. Thanks!
