### ISSUE TITLE
avogadro2 cannot be started (core dumped)

### ISSUE THREAD

**Issue by nicolastaulier** [OpenMandrivaAssociation/distribution#2973]
**OpenMandriva version**:
Rolling version (recently updated)

**Describe the bug**:
when starting avogadro2, I have the following message "Erreur de segmentation (core dumped)"

**Steps to reproduce**:
launch the command 
>avogadro2

**Observed behavior**:
return : 
>Erreur de segmentation (core dumped)

**Comment by AngryPenguinPL** [comment]
Fixed by crisb. Package works now.
