### ISSUE TITLE
New mirror: mirror.accum.se

### ISSUE THREAD

**Issue by ZNikke** [OpenMandrivaAssociation/distribution#2975]
Hi!

I hope this is the correct way to request adding a new mirror to OpenMandriva.

We've been running a mirror for quite some time, but have failed to get in contact with you to get it properly registered. In fact, the current mirroring-howto page https://wiki.openmandriva.org/en/team/infra/mirroring still doesn't contain any information on HOW to get a new mirror registered.

Hosting site: [Academic Computer Club in Umeå, Sweden](https://www.accum.se/)

Contact email: ftp-adm@accum.se

Available bandwidth: 200 Gbps (yes, Gbps). Excellent worldwide network presence peering via [NORDUnet](http://stats.nordu.net/stat-q/load-map/ndn-map,,traffic,peak)

Access URLs:

http://mirror.accum.se/mirror/openmandriva.org/
https://mirror.accum.se/mirror/openmandriva.org/
rsync rsync://mirror.accum.se/mirror/openmandriva.org/

Mirror status URL: https://mirror.accum.se/mirror/

**Comment by benbullard79** [comment]
Thanks for this bug report. This mirror has been added.

![Screenshot_20240530_133556](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/3464fbf1-69af-4282-93c3-ca3bf68887bf)

![Screenshot_20240530_133621](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/99437690-3c23-4b25-a790-c9b8ed48be1e)
