### ISSUE TITLE
DnfDrake loading list packages fail

### ISSUE THREAD

**Issue by seb62** [OpenMandrivaAssociation/distribution#2976]
**OpenMandriva version**:
Roma 

**Describe the bug**:
At start, DnfDrake try to load list packages, which failwith the message "The connection is unavailable, please check it!".

**Steps to reproduce**:
Just launch DnfDrake.

**Observed behavior**:

**Expected behavior**:

**Additional comment**:
I'm in Virtuabox under Windows.

**Logs and screenshots if relevant**
![Screenshot_20240605_133916](https://github.com/OpenMandrivaAssociation/distribution/assets/22667397/04869def-fa12-41c1-9039-c1748b70c1ba)

**Comment by benbullard79** [comment]
Works here on OMLx ROME host system. But I know I am connected to the internet.

![Screenshot_20240605_142307](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/fa665d35-c239-48aa-9a36-b714f23c6250)

Is you VBox client connected to the internet?

Try running `dnfdrake` from Konsole (terminal) and post the entire output here.

**Comment by seb62** [comment]
Yes, I'm connected, and for example the Distro Sync works perfectly well, I've just updated DnfDragora this way.
Here's the output of dnfdrake.gambas launched from the terminal:

![image](https://github.com/OpenMandrivaAssociation/distribution/assets/22667397/22a44a07-2742-40f2-bf8b-6f889f6f8ef9)

**Comment by rugyada** [comment]
> Here's the output of dnfdrake.gambas launched from the terminal

This is common, I'd say fake, _error_ from console. Unfortunately it does not say anything useful.

**Comment by seb62** [comment]
For information : doesn't have the probleme with OMLx 5.0 on the same PC and environment (windows & virtualbox).

**Comment by rugyada** [comment]
I cannot reproduce this bug

![ss_20240610_175906](https://github.com/OpenMandrivaAssociation/distribution/assets/46781309/5718b972-d114-4ee8-bf79-77351ead6526)

![ss_20240610_180049](https://github.com/OpenMandrivaAssociation/distribution/assets/46781309/9dd37c22-a48f-4690-8f31-1614e453a38c)

**Comment by seb62** [comment]
I can observe the same problem under OMLx ROME plasma 6 up to date installed on a PC, in dual-boot with other linux (Slackware 15.0).
Is there something I should set up in dnfdrake under ROME, which is not needed in Rock ?

**Comment by rugyada** [comment]
> Is there something I should set up in dnfdrake under ROME, which is not needed in Rock ?

Nothing in ROME Plasma5, dnfdrake in Plasma6 not fully tested yet.

**Comment by berolinux** [comment]
Maybe configured to use a broken mirror?

**Comment by seb62** [comment]
I just tried to change the baseurl (from mirror.openmandriva.com to abf-downloads.openmandriva.org) in /etc/yum.repos.d/openmandriva-rolling-x86_64-source.repo, without effect. But anyway if it was a mirror problem, I wouldn't be abble to use the "Distro Sync" button in DnfDrake, although it works and allowed me to update again this morning.
