### ISSUE TITLE
Bug report tool button in OM Control Center doesn't work

### ISSUE THREAD

**Issue by seb62** [OpenMandrivaAssociation/distribution#2977]
**OpenMandriva version**:
OMLx ROME up to date

**Describe the bug**:
Using the bug report tool button in the OM Control Center doesn't work, even if a message appears telling that the log file has been created.
Using the omdv-bug-report in the terminal works.

**Steps to reproduce**:
Just clicking the bug report tool ("Outil de rapport de bogues" in french) in the OM Control Center

**Observed behavior**:
No log file generated

**Expected behavior**:
Log file generated

**Additional comment**:
I'm under VirtualBox under Windows.

**Logs and screenshots if relevant**

**Comment by benbullard79** [comment]
I can confirm this report (ROME Plasma6 hardware system). Also occurs with OM-Welcome.

**Comment by rugyada** [comment]
Fixed in cooker, will be soon also in ROME and 5.0
