### ISSUE TITLE
DnfDrake - "unexpected error" while searching a package

### ISSUE THREAD

**Issue by seb62** [OpenMandrivaAssociation/distribution#2978]
**OpenMandriva version**:
OMLx ROME up to date

**Describe the bug**:
Searching for an application fails with an "unexpected error" message

**Steps to reproduce**:
 - enter an application in the search field,
 - press enter

**Observed behavior**:
error message appears "This application has raised an unexpected error and must abort."

**Expected behavior**:

**Additional comment**:
Under virtualbox under windows.

**Logs and screenshots if relevant**

![image](https://github.com/OpenMandrivaAssociation/distribution/assets/22667397/bf3ee22c-4f56-4e67-8a6a-9a582058652c)

![image](https://github.com/OpenMandrivaAssociation/distribution/assets/22667397/c0ba2a78-c977-4c25-a3b3-65f2f4ae88c2)

**Comment by rugyada** [comment]
Would it help to delete or rename
`~/.config/dnfdrake/`
?

**Comment by seb62** [comment]
No, moving away ~/.config/dnfdrake doesn't change anything.

**Comment by seb62** [comment]
For information, on the same PC, under the same Virtualbox, this problement doesn't appear with OMLx 5.0.

**Comment by rugyada** [comment]
I cannot reproduce.
Same as https://github.com/OpenMandrivaAssociation/distribution/issues/2976#issuecomment-2158763658

**Comment by seb62** [comment]
I can observe the same problem under OMLx ROME plasma 6 up to date installed on a PC, in dual-boot with other linux (Slackware 15.0).
