### ISSUE TITLE
Epson L3250 printer not working in Cooker/ROME Plasma6

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2980]
**OpenMandriva version**:
Cooker or ROME Plasma6
**Describe the bug**:
Epson L3250 printer not working, _it was working last time I tried to use the printer_.
**Steps to reproduce**:
Install `task-printing-epson`, which uses `epson-inkjet-printer-escpr-1.8.3-1` and plug in printer with usb cable and try to set it up and print test page. OR install `epson-inkjet-printer-escpr-1.8.5-1.x86_64` and plug in printer with usb cable and try to set it up and print test page.
**Observed behavior**:
Printer does not print
**Expected behavior**:
Printer prints test page
**Additional comment**:
With `epson-inkjet-printer-escpr-1.8.5-1.x86_64` printer works in Cooker Plasma5. I am confident it would work with the OM ``epson-inkjet-printer-escpr-1.8.3-1` also.
**Logs and screenshots if relevant**
This is screen-shot of working printer config in localhost:631:

![Screenshot_20240621_155750](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/6833d571-6bb4-4728-af3c-555c12309423)

Also from the Cooker P5 system:

[omdv-bug-report-20240621160238.log](https://github.com/user-attachments/files/15933624/omdv-bug-report-20240621160238.log)

I'll post more when I can.

**Comment by benbullard79** [comment]
For the sake of this report I removed the Epson .rpm's and installed `task-printing-epson`. The problem remains.

**Comment by benbullard79** [comment]
This a screen-shot from Cooker P6:

![Screenshot_20240621_191226](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/ef5bd8b9-8cbd-4605-8f66-e4454565cd9e)

FWIW I can setup the printer any number of ways in Cooker P6. The problem is any attempt to print something produces a "filter-failed" error in localhost:631.

The Cooker P6 omdv-bug-report:

[omdv-bug-report-20240621191353.log](https://github.com/user-attachments/files/15934560/omdv-bug-report-20240621191353.log)

**Comment by benbullard79** [comment]
Added berolinux to assigned list in hopes he can help when he is able.

**Comment by AngryPenguinPL** [comment]
Added to cooker repo updated version also changed some stuff. No promise of a fix, but you can check out the new version.

**Comment by benbullard79** [comment]
I setup printer yesterday as usb connected in Cooker P6 and it would not print giving error "filter failed" in localhost:631. Today it printed. I can only guess that rebooting may have restarted something like cups and enable printer to work. Makes no sense to me. But working is working and working is not a bug...

This is the setup:

![Screenshot_20240622_101046](https://github.com/OpenMandrivaAssociation/distribution/assets/5704386/00901eba-5150-4f36-b1b6-13d352636969)

```
$ rpm -qa | grep epson
task-printing-epson-4.0-7.znver1
epson-inkjet-printer-escpr-1.8.5-1.znver1
```
```
$ rpm -qa | grep cups
python-cups-1.9.74-4.znver1
cups-filters-2.0.0-1.znver1
lib64cupsfilters-2.0.0-3.znver1
libcupsfilters-2.0.0-3.znver1
lib64cups-2.4.10-1.znver1
cups-common-2.4.10-1.znver1
cups-2.4.10-1.znver1
gutenprint-cups-5.3.4-1.znver1
lib64cupsimage-2.4.10-1.znver1
```
