### ISSUE TITLE
KImageFormats HEIC support

### ISSUE THREAD

**Issue by Idesmi** [OpenMandrivaAssociation/distribution#2981]
When installing codecs from om-welcome > Applications > Multimedia > Codecs, `qt-heif-image-plugin` is pulled.

The problem is that qt-heif-image-plugin depends on KDE Frameworks 5. So it pulls a lot of dependencies that are not needed by KDE Plasma 6 and current KDE Apps.

KImageFormats, which in installed by default in OpenMandriva Rome 24.07 with Plasma 6, has support for HEIC images behind the build flag "KIMAGEFORMATS_HEIF".

I know that it's not build with support by default because of patents, but could be a separate build in the Restricted repo.

**Comment by rugyada** [comment]
> The problem is that qt-heif-image-plugin depends on KDE Frameworks 5. So it pulls a lot of dependencies that are not needed by KDE Plasma 6 and current KDE Apps.

Fixed in `om-welcome-2.7.6`

**Comment by Idesmi** [comment]
Is there a reason why not to use KImageFormats?

**Comment by AngryPenguinPL** [comment]
I just prepared a kf6-kimageformats-heif version and it is in restricted repository. To download it you must first activate the restricted repository.

For now, change only applies to the Cooker release, if everything goes well it should also appear in ROME.

**Comment by rugyada** [comment]
Now also in ROME /testing repo.

Run command:
`$ sudo dnf --refresh --enablerepo=rolling-x86_64-restricted --enablerepo=rolling-testing-x86_64-restricted upgrade kf6-kimageformats`

**Comment by Idesmi** [comment]
With heif support in KImageFormats, `heifthumbnailer` and `qt-heic-image-plugin` can be removed from this line: https://github.com/OpenMandrivaSoftware/om-welcome/blob/55a25d58d47b36e353eced64fc0a61b777669651/usr/share/om-welcome/apps/install-codecs.run#L9 and replaced with `kf6-kimageformats-heif`.

**Comment by rugyada** [comment]
I would have expected some feedback.

**Comment by Idesmi** [comment]
> I would have expected some feedback.

I am new to OpenMandriva so I don't know how you do it here.

I tested the changes in a VM and everything is working fine.

I can also confirm that HEIF image preview in Dolphin is still shown even with the further modifications I proposed.

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/heic-heif-codecs-support/5394/5
