### ISSUE TITLE
Corectrl does not start

### ISSUE THREAD

**Issue by Podberezovik34** [OpenMandrivaAssociation/distribution#2992]
**OpenMandriva Lx Rome 24.09:** (KDE6)
I installed corectrl from the repository, but it does not start.

$ corectrl
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:7:1: module “QtQuick.Layouts” is not installed
[13-10-24 18:39:29.720][W] QML engine failed to load main interface!
[13-10-24 18:39:29.720][W] Initialization failed
[13-10-24 18:39:29.720][W] Exiting…
terminate called without an active exception
Аварийный останов (образ памяти сброшен на диск)

I don't know where else to report the error, so I'll write here. Corectrl does not start, gives an error about the absence of the module, it is not in the repository...

**Comment by Podberezovik34** [comment]
By trial, it turned out to run corectrl by installing the package qt5-qtdeclarative with dependencieslib64qt5quickparticles5-5.15.15-1.znver1
lib64qt5quickshapes5-5.15.15-1.znver1
lib64qt5quicktest5-5.15.15-1.znver1
lib64qt5test5-5.15.15-1.znver1

**Comment by AngryPenguinPL** [comment]
I will try to add these dependencies to the package.
Thanks
