### ISSUE TITLE
F3D: 2.2.1 -> 2.5.0

### ISSUE THREAD

**Issue by luzpaz** [OpenMandrivaAssociation/distribution#2993]
Current stable release is 2.5.0 [Release v2.5.0 · f3d-app/f3d · GitHub](https://github.com/f3d-app/f3d/releases/tag/v2.5.0)
Mandriva Rolling 2.2.1 [GitHub - OpenMandrivaAssociation/f3d at rolling](https://github.com/OpenMandrivaAssociation/f3d/tree/rolling)
Mandriva Cooker 2.2.1 [GitHub - OpenMandrivaAssociation/f3d](https://github.com/OpenMandrivaAssociation/f3d/tree/master)

**Comment by omakuta** [comment]
This issue has been mentioned on **OpenMandriva forum**. There might be relevant details there:

https://forum.openmandriva.org/t/f3d-2-2-1-2-5-0/5417/4

**Comment by luzpaz** [comment]
I was directed from there to here.

**Comment by luzpaz** [comment]
Please change the tag from 'enhancement' to 'package-update'. TIA

**Comment by AngryPenguinPL** [comment]
Updated to 2.5.0 in Cooker.
