### ISSUE TITLE
Request for intel-undervolt to be added to OM repository

### ISSUE THREAD

**Issue by coaxguy99** [OpenMandrivaAssociation/distribution#2999]
Official package name:  intel-undervolt

License (must be an OSI approved Open Source license): GPL-3.0 license

Download URL of latest release:  https://github.com/kitsunyan/intel-undervolt

Latest release date (must be recent):  July 6, 2019

Description: Intel CPU undervolting and throttling configuration tool.  This package is included in Fedora, Mageia, and other popular RPM/DNF based distros.  It is very helpful for improving battery life. on supported processors.

**Comment by AngryPenguinPL** [comment]
Package added to repos.
Cooker and ROME.
Please test it (I don't have an Intel processor)

**Comment by AngryPenguinPL** [comment]
Done and closing because no response, so we cant test if app works or not.
